#include "AnimationRetarget.h"
#include "ModelCook.h"
#include "ModelArchive.h"
#include "ModelLoader.h"
#include "PoseComposition.h"
#include "SceneFingerprint.h"
#include "../third_party/nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <set>
#include <cmath>
namespace fs=std::filesystem;using Json=nlohmann::json;
namespace {
unsigned checks=0,failures=0;
void Check(bool ok,const char* message){++checks;failures+=!ok;std::cout<<(ok?"PASS ":"FAIL ")<<message<<'\n';}
Json Read(const fs::path& p){std::ifstream file(p);return Json::parse(file);}
void Write(const fs::path& p,const Json& j){fs::create_directories(p.parent_path());std::ofstream(p)<<j.dump(2)<<'\n';}
std::string Hash(const fs::path& p){std::string hash,error;if(!SceneFingerprintSha256File(p.string(),hash,error))throw std::runtime_error(error);return hash;}
bool Cook(const std::string& recipe,ModelCookTask& task){std::string error;bool ok=CookModelRecipe(recipe,task)&&PublishModelImport(task,error);if(!ok)std::cout<<"DIAGNOSTIC "<<task.error<<" "<<error<<'\n';return ok;}
const AnimationClip& Clip(const MeshData& mesh,const char* name){auto& clips=mesh.skeletal->clips;auto it=std::find_if(clips.begin(),clips.end(),[&](const auto& c){return c.name==name;});if(it==clips.end())throw std::runtime_error(std::string("test clip missing: ")+name);return *it;}
}
int main(int argc,char** argv){try{
 fs::path root=argc>1?argv[1]:".cache/m74/cook-tests";if(fs::exists(root)){std::cerr<<"Use a fresh test-owned directory: "<<root<<'\n';return 2;}fs::create_directories(root);
 std::string recipe,error;Check(CreateModelRecipe(root.string(),"tests/fixtures/m66/capacity256.gltf","Assets/target.judasmodel",recipe,error),"ordinary target recipe copies normalized source fixture");if(recipe.empty())throw std::runtime_error(error);
 auto recipeJson=Read(recipe);auto sourcePath=root/"Sources"/"motion.gltf";fs::copy_file("tests/fixtures/m66/capacity256.gltf",sourcePath);
 MeshData target,source;ModelImportSettings targetSettings,sourceSettings;ModelImportReport report;std::string projectRoot;
 Check(LoadModelRecipeTarget(recipe,target,targetSettings,projectRoot,error)&&ImportMotionSource(sourcePath.string(),sourceSettings,source,report,error),"shared editor/CLI target and complete motion-source inputs decode");if(!target.skeletal||!source.skeletal)throw std::runtime_error(error);
 auto key=SkeletonJointKey(target.skeletal->skeleton,1);RetargetProfile profile;profile.sourceIdentity="Sources/motion.gltf";profile.targetIdentity=recipeJson.at("assetId");profile.sourceSignature=SkeletonRetargetSignature(source.skeletal->skeleton);profile.targetSignature=SkeletonRetargetSignature(target.skeletal->skeleton);profile.mapping={{key,key}};profile.translationJoints={key};auto profilePath=root/"Imports"/"shared.judasretarget";
 Check(SaveRetargetProfile(profilePath.string(),profile,error),"reusable named authoring profile saves through shared bounded serializer");
 recipeJson["clips"]=Json::array({{{"sourceClip","Translate"},{"name","Native"},{"loop",true}}});
 recipeJson["motions"]=Json::array({{{"source","Sources/motion.gltf"},{"take","Translate"},{"name","Borrowed"},{"retargetProfile","Imports/shared.judasretarget"},{"trim",{.25,.75}},{"sampleRate",90}},{{"source","Sources/motion.gltf"},{"take","Translate"},{"name","Extracted"},{"retargetProfile","Imports/shared.judasretarget"},{"sampleRate",90},{"rootMotion",{{"policy","extract"},{"node",key},{"translation",{true,false,false}}}}}});Write(recipe,recipeJson);
 ModelCookTask initial;Check(Cook(recipe,initial),"two retarget operations reuse profile and publish beside native target clip");if(!initial.success)throw std::runtime_error(initial.error);auto accepted=Hash(initial.output);MeshData cooked;
 Check(LoadModelMesh(initial.output,cooked,error)&&cooked.skeletal->clips.size()==3,"ordinary runtime loader sees native and both borrowed named clips");
 Check(Clip(cooked,"Native").duration==1&&Clip(cooked,"Borrowed").duration==.5f,"native clip timing preserved and retarget trim has explicit duration");
 auto targetSample=SampleClip(cooked.skeletal->skeleton,Clip(cooked,"Borrowed"),.25f);auto expectedSample=SampleClip(source.skeletal->skeleton,source.skeletal->clips[0],.5f);
 Check(glm::length(targetSample.local[1].translation-expectedSample.local[1].translation)<1e-6f,"trimmed borrowed output samples expected source interval");
 Check(!Clip(cooked,"Extracted").motion.empty()&&glm::length(RootMotionInterval(Clip(cooked,"Extracted"),.75,1.25,true).translation-glm::vec3(.25f,0,0))<1e-6f,"ordinary extracted root-motion loop composes without doubled displacement");
 // The editor uses the same CPU bake and root policy, with no publication.
 RetargetBakeSettings bake;bake.name="Extracted";bake.sampleRate=90;AnimationClip preview;RetargetBakeReport bakeReport;auto previewAsset=*target.skeletal;ModelRootMotionSettings rootSettings;rootSettings.policy="extract";rootSettings.node=key;rootSettings.translation={{true,false,false}};
 Check(BakeRetargetClip(source.skeletal->skeleton,source.skeletal->clips[0],target.skeletal->skeleton,profile,bake,preview,error,&bakeReport)&&ApplyModelRootMotionPolicy(previewAsset,preview,rootSettings,90,error),"shared preview uses production retarget and ordinary root-motion policy");
 auto previewPose=ResolveJointMatrices(previewAsset.skeleton,SampleClip(previewAsset.skeleton,preview,.371f));auto cookedPose=ResolveJointMatrices(cooked.skeletal->skeleton,SampleClip(cooked.skeletal->skeleton,Clip(cooked,"Extracted"),.371f));float worst=0;for(size_t i=0;i<previewPose.size();++i)for(int c=0;c<4;++c)for(int r=0;r<4;++r)worst=std::max(worst,std::abs(previewPose[i][c][r]-cookedPose[i][c][r]));Check(worst<1e-6f,"preview and reloaded recipe bake agree within 1 micrometre matrix tolerance");
 ModelCookTask unchanged;unchanged.previewRequired=false;Check(Cook(recipe,unchanged)&&unchanged.unchanged&&unchanged.receiptHit&&unchanged.decodedProducts==0&&Hash(initial.output)==accepted,"unchanged recipe verifies receipt and does not decode or append duplicates");
 profile.translationScale=2;Check(SaveRetargetProfile(profilePath.string(),profile,error),"same reusable profile accepts explicit translation calibration edit");ModelCookTask changed;Check(Cook(recipe,changed)&&!changed.unchanged&&changed.assetId==initial.assetId&&Hash(initial.output)!=accepted,"profile content edit rebakes while retaining logical output identity");accepted=Hash(initial.output);
 auto originalProfile=profile;profile.mapping[0].source="missing/key";SaveRetargetProfile(profilePath.string(),profile,error);ModelCookTask invalid;Check(!CookModelRecipe(recipe,invalid)&&Hash(initial.output)==accepted,"missing mapping fails transactionally and preserves last accepted product");profile=originalProfile;SaveRetargetProfile(profilePath.string(),profile,error);
 auto collision=recipeJson;collision["motions"][0]["name"]="Translate";Write(recipe,collision);ModelCookTask nameCollision;Check(!CookModelRecipe(recipe,nameCollision)&&Hash(initial.output)==accepted,"retarget output collision never overwrites a native target clip");Write(recipe,recipeJson);
 ModelCookTask cancelled;cancelled.cancel=true;Check(!CookModelRecipe(recipe,cancelled)&&Hash(initial.output)==accepted,"cancelled cook leaves accepted generation unchanged");
 // Input changes after the worker result are checked before atomic publication.
 auto staleRecipe=recipeJson;staleRecipe["motions"][0]["sampleRate"]=91;Write(recipe,staleRecipe);ModelCookTask staged;Check(CookModelRecipe(recipe,staged),"changed operation stages an immutable candidate generation");profile.translationScale=3;SaveRetargetProfile(profilePath.string(),profile,error);Check(!PublishModelImport(staged,error)&&Hash(initial.output)==accepted,"profile change between cook and publication rejects stale worker output");profile=originalProfile;SaveRetargetProfile(profilePath.string(),profile,error);Write(recipe,recipeJson);
 // glTF animation-only sources still retain the complete ancestor hierarchy.
 auto animationOnly=Read(sourcePath);animationOnly.erase("meshes");animationOnly.erase("skins");for(auto& node:animationOnly["nodes"]){node.erase("mesh");node.erase("skin");}auto motionOnlyPath=root/"Sources"/"motion-only.gltf";Write(motionOnlyPath,animationOnly);MeshData motionOnly;Check(ImportMotionSource(motionOnlyPath.string(),sourceSettings,motionOnly,report,error)&&motionOnly.vertices.empty()&&motionOnly.skeletal->skeleton.names.size()==source.skeletal->skeleton.names.size(),"animation-only glTF decodes all ancestor joints without manufactured geometry");
 // An extracted source must never be mistaken for stationary pose-only motion.
 auto sourceWithMotion=source.skeletal->clips[0];sourceWithMotion.motionTimes={0,1};JointTransform translated;translated.translation={.5f,0,0};sourceWithMotion.motion={{},translated};AnimationClip retained=preview;Check(!BakeRetargetClip(source.skeletal->skeleton,sourceWithMotion,target.skeletal->skeleton,profile,bake,retained,error)&&retained.name==preview.name,"already-extracted source reports unsupported contract without partial output mutation");
 ModelCookTask restored;Check(Cook(recipe,restored)&&Hash(initial.output)==accepted,"restored input bytes reproduce deterministic accepted generation");
 fs::remove_all(root/".cache");fs::remove(initial.output+".import-report.json");ModelCookTask cold;Check(Cook(recipe,cold)&&cold.unchanged&&Hash(initial.output)==accepted,"lost disposable cache/receipt still preserves validated ordinary output");
 auto steppedSource=Read(sourcePath);for(auto& animation:steppedSource["animations"])for(auto& sampler:animation["samplers"])sampler["interpolation"]="STEP";Write(sourcePath,steppedSource);ModelCookTask stepped;Check(!CookModelRecipe(recipe,stepped)&&Hash(initial.output)==accepted,"unsupported animated STEP discontinuity is explicit and preserves last-good output");
 auto changedSource=Read("tests/fixtures/m66/capacity256.gltf");float values[]={0,0,0,.75f,0,0};std::ofstream motionBytes(root/"Sources"/"edited-motion.bin",std::ios::binary);motionBytes.write(reinterpret_cast<const char*>(values),sizeof(values));motionBytes.close();int buffer=int(changedSource["buffers"].size());changedSource["buffers"].push_back({{"uri","edited-motion.bin"},{"byteLength",sizeof(values)}});int view=int(changedSource["bufferViews"].size());changedSource["bufferViews"].push_back({{"buffer",buffer},{"byteLength",sizeof(values)}});int accessor=int(changedSource["accessors"].size());changedSource["accessors"].push_back({{"bufferView",view},{"componentType",5126},{"count",2},{"type","VEC3"}});for(auto& animation:changedSource["animations"])for(auto& sampler:animation["samplers"])sampler["output"]=accessor;auto stamp=fs::last_write_time(sourcePath);Write(sourcePath,changedSource);fs::last_write_time(sourcePath,stamp);ModelCookTask sourceEdit;Check(Cook(recipe,sourceEdit)&&!sourceEdit.unchanged&&Hash(initial.output)!=accepted,"same-mtime legal source/dependency edit invalidates baked motion by content hash");
 // Legal original Blender-authored FBX -> GLB exercises both format decoders
 // and the same ordinary recipe/publication path, not only native structs.
 std::string fbxRecipe;Check(CreateModelRecipe(root.string(),"tests/fixtures/m74/borrow_source.glb","Assets/fbx-target.judasmodel",fbxRecipe,error),"original GLB target copies through the normal import boundary");if(fbxRecipe.empty())throw std::runtime_error(error);auto fbxRecipeJson=Read(fbxRecipe);auto fbxPath=root/"Sources"/"borrow.fbx";fs::copy_file("tests/fixtures/m74/borrow_source.fbx",fbxPath);MeshData fbxMotion,glbTarget;ModelImportReport fbxReport;ModelImportSettings fbxSettings,glbSettings;
 Check(ImportMotionSource(fbxPath.string(),fbxSettings,fbxMotion,fbxReport,error)&&LoadModelRecipeTarget(fbxRecipe,glbTarget,glbSettings,projectRoot,error),"complete original FBX motion and GLB target decode with normal axis/unit normalization");if(!fbxMotion.skeletal||!glbTarget.skeletal||fbxMotion.skeletal->clips.empty())throw std::runtime_error(error);RetargetProfile fbxProfile;fbxProfile.sourceIdentity="Sources/borrow.fbx";fbxProfile.targetIdentity=fbxRecipeJson.at("assetId");fbxProfile.sourceSignature=SkeletonRetargetSignature(fbxMotion.skeletal->skeleton);fbxProfile.targetSignature=SkeletonRetargetSignature(glbTarget.skeletal->skeleton);
 for(const char* role:{"Base","Reach","Tip","Opposite"}){int a=FindSkeletonJoint(fbxMotion.skeletal->skeleton,role),b=FindSkeletonJoint(glbTarget.skeletal->skeleton,role);if(a<0||b<0)throw std::runtime_error("original FBX/GLB role missing");auto targetKey=SkeletonJointKey(glbTarget.skeletal->skeleton,b);fbxProfile.mapping.push_back({SkeletonJointKey(fbxMotion.skeletal->skeleton,a),targetKey});if(std::string(role)=="Base"||std::string(role)=="Reach")fbxProfile.translationJoints.push_back(targetKey);}
 Check(SaveRetargetProfile((root/"Imports"/"fbx.judasretarget").string(),fbxProfile,error),"original FBX source profile retains stable full ancestor keys");fbxRecipeJson["motions"]=Json::array({{{"source","Sources/borrow.fbx"},{"take",fbxMotion.skeletal->clips[0].name},{"name","BorrowFBX"},{"retargetProfile","Imports/fbx.judasretarget"}}});Write(fbxRecipe,fbxRecipeJson);ModelCookTask fbxCook;Check(Cook(fbxRecipe,fbxCook),"FBX performance bakes and publishes ordinary GLB-compatible named clip");MeshData fbxCooked;Check(LoadModelMesh(fbxCook.output,fbxCooked,error)&&fbxCooked.skeletal->clips.size()==glbTarget.skeletal->clips.size()+1&&Clip(fbxCooked,"BorrowFBX").duration==fbxMotion.skeletal->clips[0].duration,"reloaded FBX recipe output preserves target originals and source playback timing");
 // Secondary trim of a dense retarget clip must sample once per UNION time,
 // not once per track/time. This 258-node fixture yields over 500 baked tracks.
 auto denseRoot=root/"dense-secondary-trim";std::string denseRecipe;
 Check(CreateModelRecipe(denseRoot.string(),"tests/fixtures/m66/capacity256.gltf","Assets/dense.judasmodel",denseRecipe,error),"dense secondary-trim target uses ordinary recipe infrastructure");
 if(denseRecipe.empty())throw std::runtime_error(error);
 auto denseJson=Read(denseRecipe);fs::copy_file("tests/fixtures/m66/capacity256.gltf",denseRoot/"Sources"/"motion.gltf");
 RetargetProfile denseProfile;denseProfile.sourceIdentity="Sources/motion.gltf";denseProfile.targetIdentity=denseJson.at("assetId");denseProfile.sourceSignature=SkeletonRetargetSignature(source.skeletal->skeleton);denseProfile.targetSignature=SkeletonRetargetSignature(target.skeletal->skeleton);
 for(size_t i=0;i<target.skeletal->skeleton.names.size();++i){auto fullKey=SkeletonJointKey(target.skeletal->skeleton,int(i));denseProfile.mapping.push_back({fullKey,fullKey});denseProfile.translationJoints.push_back(fullKey);}
 Check(SaveRetargetProfile((denseRoot/"Imports"/"dense.judasretarget").string(),denseProfile,error),"dense profile maps complete stable target hierarchy");
 denseJson["motions"]=Json::array({{{"source","Sources/motion.gltf"},{"take","Translate"},{"name","Dense"},{"retargetProfile","Imports/dense.judasretarget"},{"sampleRate",90}}});
 denseJson["clips"]=Json::array({{{"sourceClip","Translate"},{"name","Native"}},{{"sourceClip","Dense"},{"name","DenseTrim"},{"trim",{.2,.8}}}});Write(denseRecipe,denseJson);
 RetargetBakeSettings denseSettings;denseSettings.name="Dense";denseSettings.sampleRate=90;AnimationClip denseBake;
 Check(BakeRetargetClip(source.skeletal->skeleton,source.skeletal->clips[0],target.skeletal->skeleton,denseProfile,denseSettings,denseBake,error)&&denseBake.tracks.size()>500,"dense retarget fixture genuinely produces hundreds of ordinary tracks");
 if(denseBake.tracks.empty())throw std::runtime_error(error);
 const float trimBegin=.2f,trimEnd=.8f;std::set<float> denseTimes{trimBegin,trimEnd};for(float time:denseBake.tracks[0].times)if(time>trimBegin&&time<trimEnd)denseTimes.insert(time);for(size_t i=1;i<size_t(std::ceil((trimEnd-trimBegin)*90));++i)denseTimes.insert(trimBegin+float(i/90.0));
 ModelCookTask denseCook;Check(Cook(denseRecipe,denseCook),"secondary recipe trim of dense retarget output publishes normally");
 if(!denseCook.success)throw std::runtime_error(denseCook.error);
 MeshData denseCooked;
 Check(LoadModelMesh(denseCook.output,denseCooked,error),"dense trimmed output remains an ordinary runtime asset");
 if(!denseCooked.skeletal)throw std::runtime_error(error);
 Check(denseCook.trimPoseSamples==denseTimes.size()&&denseCook.trimNodeEvaluations==denseTimes.size()*denseCooked.skeletal->skeleton.names.size(),"secondary trim samples each union pose once, with exact bounded evaluation telemetry");
 const auto& trimmed=Clip(denseCooked,"DenseTrim");bool schedulesMatch=trimmed.tracks.size()==denseBake.tracks.size();float denseValueError=0;
 size_t denseAt=0;for(float time:denseTimes){auto known=SampleClip(target.skeletal->skeleton,denseBake,time);for(const auto& track:trimmed.tracks){schedulesMatch&=denseAt<track.times.size()&&track.times[denseAt]==time-trimBegin;if(denseAt>=track.values.size()){schedulesMatch=false;continue;}const auto& joint=known.local[track.node];glm::vec4 expected=track.path==TrackPath::Translation?glm::vec4(joint.translation,0):glm::vec4(joint.rotation.x,joint.rotation.y,joint.rotation.z,joint.rotation.w);denseValueError=std::max(denseValueError,glm::length(track.values[denseAt]-expected));}++denseAt;}
 for(const auto& track:trimmed.tracks)schedulesMatch&=denseAt==track.times.size();
 Check(schedulesMatch&&denseValueError<1e-6f&&trimmed.duration==trimEnd-trimBegin,"shared sampling retains prior per-track timestamps, endpoints and exact sampled values");
 ModelCookTask trimCancelled;auto cancelDense=denseJson;cancelDense["clips"][1]["trim"]={.21,.8};Write(denseRecipe,cancelDense);const auto denseAccepted=Hash(denseCook.output);trimCancelled.workerCancelled=[&]{return trimCancelled.trimPoseSamples>=2;};
 Check(!CookModelRecipe(denseRecipe,trimCancelled)&&trimCancelled.trimPoseSamples==2&&Hash(denseCook.output)==denseAccepted,"secondary trim cancellation during shared sampling preserves accepted generation");
 Json result={{"checks",checks},{"failures",failures},{"previewMatrixMaxError",worst},{"bakeSamples",bakeReport.samples},{"bakeMs",bakeReport.milliseconds},{"outputBytes",fs::file_size(initial.output)},{"secondaryTrimPoseSamples",denseCook.trimPoseSamples},{"secondaryTrimFormerPoseSamples",denseCook.trimPoseSamples*denseBake.tracks.size()},{"secondaryTrimNodeEvaluations",denseCook.trimNodeEvaluations},{"secondaryTrimMaxValueError",denseValueError}};Write(root/"results.json",result);std::cout<<result.dump(2)<<'\n';return failures?1:0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
