#include "Application.h"
#include "TestInput.h"
#include "EngineHost.h"
#include "InteractivePlay.h"
#include "RuntimeWorld.h"
#include "SceneSession.h"
#include "WorldPersistence.h"
#include "SaveService.h"
#include "WorldStreaming.h"
#include "ScreenshotWriter.h"
#include "UniformGravity.h"
#include "PoseComposition.h"
#include "PerformanceProfiler.h"
#include "WorldPresentation.h"
#include <SDL2/SDL.h>
#include <filesystem>
#include <thread>
#include <cstdio>
#include <algorithm>
namespace {
int checks=0,failures=0;void check(bool ok,const char* label){++checks;failures+=!ok;std::printf("%s %s\n",ok?"PASS":"FAIL",label);std::fflush(stdout);} }
int main(int argc,char** argv){if(argc<4){std::fprintf(stderr,"usage: %s <project.judasproj> <probe|write|read|stream|lifetime> <output-dir>\n",argv[0]);return 2;}std::string project=argv[1],mode=argv[2],out=argv[3];std::filesystem::create_directories(out);unsigned frame=0,phase=0,restoredFrame=0;bool frozen=false;RuntimeWorld* initial=nullptr;GameSnapshot expected;std::string error,annexState;uint64_t region=0;uint64_t originalEpoch=0,radialEpoch=0;EntityId oldAnnex=0;std::vector<glm::dvec3> suspended;ApplicationControl control;control.hidden=true;setenv("JUDAS_PROFILE","1",1);control.hostReady=[](EngineHost& h){h.GetWindow().SetTestInputMode(true);SDL_GL_SetSwapInterval(0);std::string e;h.Audio().Init(e,true);};control.frameSeconds=[&](float){return frozen?0.f:1.f/60;};control.worldReady=[&](EngineHost&,RuntimeWorld& w,InteractivePlay&){initial=&w;};
 control.beforeFrame=[&](EngineHost& h,RuntimeWorld& w,InteractivePlay&){h.GetRenderer().ResetStats();if(mode=="lifetime"&&(frame==60||frame==61))QueueTestKey(h.GetWindow(),SDL_SCANCODE_2,frame==60);if(mode=="lifetime"&&(frame==100||frame==101))QueueTestKey(h.GetWindow(),SDL_SCANCODE_F9,frame==100);if(mode!="read"&&(frame==35||frame==36)){QueueTestKey(h.GetWindow(),SDL_SCANCODE_B,frame==35);QueueTestKey(h.GetWindow(),SDL_SCANCODE_V,frame==35);}if(mode=="write"&&(frame==150||frame==151))QueueTestKey(h.GetWindow(),SDL_SCANCODE_F5,frame==150);if(mode=="read"&&phase==1){QueueTestKey(h.GetWindow(),SDL_SCANCODE_F8,true);phase=4;}else if(mode=="read"&&phase==4)QueueTestKey(h.GetWindow(),SDL_SCANCODE_F8,false);if(mode=="probe"&&(frame==45||frame==46))QueueTestKey(h.GetWindow(),SDL_SCANCODE_P,frame==45);if(mode=="probe"&&(frame==65||frame==66||frame==85||frame==86))QueueTestKey(h.GetWindow(),SDL_SCANCODE_H,frame==65||frame==85);
  if(mode=="read"&&&w!=initial&&!restoredFrame){restoredFrame=frame;frozen=true;std::map<std::string,SaveChunk> chunks;WorldPersistence::Capture(w,chunks,error);check(chunks.count("deformables")&&chunks.at("deformables").data==expected.participants.at("deformables").data,"cold process reconstructs exact cloth motion and plastic rest state before resume");auto* sim=w.RuntimeDeformable(301,error);double dent=0;for(size_t i=0;i<sim->plasticRest.size();++i)dent+=glm::length(sim->plasticRest[i][0]-sim->asset->solids[i].rest[0]);check(dent>.001,"cold process retains physical plastic deformation");check(sim->settings.attachments[0].group=="left"&&sim->generation!=0,"fresh deformable handle with saved attachment group");phase=2;}
 };
 control.beforeShutdown=[&](EngineHost&,RuntimeWorld&,InteractivePlay&){auto& prof=PerformanceProfiler::Get();prof.Export((std::filesystem::path(out)/"profile.json").string(),error);auto summary=prof.Summary();std::printf("FRAME median_ms=%.6f p95_ms=%.6f max_ms=%.6f\n",summary.median,summary.p95,summary.maximum);auto snap=prof.Snapshot(prof.FrameId()-1);std::map<std::string,double> phases;for(auto& scope:snap.scopes)phases[scope.name.c_str()]+=double(scope.end-scope.start)*1e-6;for(auto& [name,ms]:phases)if(name.find("Deformable")!=std::string::npos)std::printf("PHASE %s %.6fms\n",name.c_str(),ms);};
 control.afterFrame=[&](EngineHost& h,RuntimeWorld& w,InteractivePlay& play){++frame;bool healthy=w.Scripts()&&w.Scripts()->Diagnostics().empty();if(!healthy){if(w.Scripts())for(auto& d:w.Scripts()->Diagnostics())std::printf("SCRIPT %s %s\n",d.callback.c_str(),d.message.c_str());check(false,"ordinary project VM callbacks healthy");w.UI().RequestQuit();return;}
  bool ready=true;for(auto id:{100,201,300,301,400,401,501}){auto* s=w.RuntimeDeformable(id,error);ready&=s!=nullptr;if(s&&!s->error.empty()){std::printf("DEFORM %d %s minJ=%g\n",id,s->error.c_str(),s->stats.minimumJacobian);check(false,"combined simulation stays finite/capacity-safe");w.UI().RequestQuit();return;}}
  if(frame==40){check(ready,"ordinary project asynchronously publishes all seven deformable instances");check(w.RuntimeAnimation(200)&&w.RuntimeAnimation(200)->asset,"real animated target shares normal skeletal resource");check(w.UI().Document(w.UI().Find("lab"))!=nullptr,"normal authored UI loaded");auto* cape=w.RuntimeDeformable(201,error);if(cape){check(cape->released[0]==0,"cape resolves authored stable bone attachment");auto* animation=w.RuntimeAnimation(200);auto joint=FindSkeletonJoint(animation->asset->skeleton,"Root/Elbow");double mismatch=0;for(auto n:cape->asset->groups.at("top")){auto expected=glm::dvec3(glm::dmat4(animation->recentWorld[joint])*glm::dvec4(cape->asset->nodes[n]+cape->settings.attachments[0].offset,1));mismatch=std::max(mismatch,glm::length(expected-cape->positions[n]));}check(mismatch<1e-6,"cape pins consume exact resolved joint pose without another animation clock");}
   originalEpoch=w.RuntimeDeformable(100,error)->generation;
   auto t=w.RuntimeDefinition(100)->transform;t.scale={2,2,2};check(!w.SetRuntimeTransform(100,t),"runtime scale change rejects unsupported deformable scale");if(mode=="read"){auto* service=w.SceneControl()->Saves(h.Resources());SaveStorage store(service->Root());bool recovered=false;check(store.Read("deformable-lab",expected,recovered,error),"cold process reads committed M61 slot");check(expected.participants.count("deformables"),"M61 required deformable participant present");phase=1;}}
  if(mode=="read"&&restoredFrame){if(frame==restoredFrame+1){frozen=false;phase=3;}if(frame>restoredFrame+15){check(ready&&healthy,"resumed cloth/solid and restore-aware JS continue without explosion");w.UI().RequestQuit();phase=9;}}
  if(mode=="write"&&frame>150){auto* service=w.SceneControl()->Saves(h.Resources());for(uint64_t id=1;id<16;++id)if(auto* status=service->Status(id)){if(status->state=="failed"){std::printf("SAVE %s\n",status->error.c_str());check(false,"save completes");w.UI().RequestQuit();phase=9;}else if(status->state=="completed"){check(status->operation=="save","public JS save commits M61 slot");std::printf("SAVE capture_ms=%.5f worker_ms=%.5f bytes=%zu root=%s\n",status->captureMs,status->workerMs,status->bytes,service->Root().c_str());w.UI().RequestQuit();phase=9;}}}
  if(mode=="stream"&&frame>40){auto* stream=w.SceneControl()->Streaming(w,error);if(phase==0){region=stream->Request("annex",false,error);check(region!=0,"ordinary region activation request");phase=1;}auto status=stream->Regions().front();if(!status.error.empty()){std::printf("REGION %s\n",status.error.c_str());check(false,"region lifecycle healthy");w.UI().RequestQuit();phase=9;}if(phase==1&&status.state=="active"){oldAnnex=stream->Resolve("annex",1);auto* sim=w.RuntimeDeformable(oldAnnex,error);if(sim){sim->Impulse("",{.1,0,.2});sim->Step(1./60,w.Physics(),UniformGravity({0,0,0}),{});suspended=sim->positions;auto* attached=w.RuntimeDeformable(100,error);attached->settings.attachments[0].kind=DeformableAttachment::Kind::Body;attached->settings.attachments[0].target=stream->Resolve("annex",2);attached->released[0]=0;w.InvalidateDeformableTargets(100);stream->Release(region);frozen=true;phase=4;}}if(phase==4&&status.state=="active"&&!status.pins.empty()){check(true,"live cross-region attachment pins target region against teardown");w.RuntimeDeformable(100,error)->Release("top");frozen=false;phase=2;}if(phase==2&&status.state=="unloaded"){check(!w.RuntimeDefinition(oldAnnex)&&status.retained>0,"region teardown retains deformable snapshot and invalidates old owner");region=stream->Request("annex",false,error);frozen=true;phase=3;}if(phase==3&&status.state=="active"){auto current=stream->Resolve("annex",1);auto* sim=w.RuntimeDeformable(current,error);check(current!=oldAnnex&&sim&&sim->positions==suspended,"revisit restores node state with fresh identity without authored reset");frozen=false;w.UI().RequestQuit();phase=9;}}
  if(mode=="lifetime"&&frame==85){auto* sim=w.RuntimeDeformable(100,error);radialEpoch=sim->generation;check(radialEpoch!=originalEpoch&&w.SceneControl()->Current().find("radial")!=std::string::npos,"normal scene transition destroys old nodes and builds independent radial instances");auto sample=w.Gravity().Sample({6,2,0});check(sample.x<-.1&&sample.y<0,"lab radial scene uses actual selected radial acceleration");}
  if(mode=="lifetime"&&frame==140){check(w.RuntimeDeformable(100,error)->generation!=radialEpoch,"authored reload reconstructs fresh deformable handles");auto* cape=w.RuntimeDeformable(201,error);w.DestroyEntity(200);w.UpdateDeformables(1./60);check(cape->released[0],"destroyed skeleton target releases group instead of retaining a stale pose");check(w.Scripts()->Diagnostics().empty(),"remaining scripts safely survive target destruction");w.UI().RequestQuit();phase=9;}
  if(mode=="probe"&&frame==120){auto camera=w.view->pose;auto v=glm::mat4_cast(glm::inverse(camera.rotation))*glm::translate(glm::mat4(1),-camera.position),p=glm::perspective(glm::radians(65.f),1.f,.1f,100.f);auto* cloth=w.RuntimeDeformable(100,error);auto positions=cloth->positions;RenderWorldFrame(h.GetRenderer(),640,360,w,nullptr,v,p,camera.position,.5f);check(cloth->positions==positions,"main/secondary/shadow presentation never advances or changes physics");check(w.PresentationCameras().size()==1&&w.PresentationCameras()[0].updates>0,"normal M33 camera renders deformable scene independently");check(ready&&healthy,"real VM controls airflow/load and prefab spawn safely");auto objects=w.ScriptObjects();check(std::any_of(objects.begin(),objects.end(),[](const auto& o){return o.id>=kRuntimeEntityIdBase&&bool(o.deformable);}),"runtime prefab adds independent deformable owner");std::vector<unsigned char> pixels;h.GetRenderer().CaptureFrame(h.GetWindow().Width(),h.GetWindow().Height(),pixels);WriteRgbPng((std::filesystem::path(out)/"lab.png").string(),h.GetWindow().Width(),h.GetWindow().Height(),pixels);size_t contacts=0;for(auto id:{100,201,300,301,400,401,501})contacts+=w.RuntimeDeformable(id,error)->stats.contacts;std::printf("LAB contacts=%zu bodies=%zu fixed_ms=%.6f draws=%u\n",contacts,w.Physics().AliveBodyCount(),play.LastFixedStepMilliseconds(),h.GetRenderer().Stats().drawCalls);w.UI().RequestQuit();phase=9;}
  std::this_thread::sleep_for(std::chrono::milliseconds(1));if(frame>600){check(false,"bounded application deadline");w.UI().RequestQuit();}
 };
 Application app;char name[]="judas";char* args[]={name,project.data()};check(app.Run(2,args,&control)==0&&phase==9,"normal startup and clean shutdown");std::printf("SUMMARY mode=%s checks=%d failures=%d frames=%u\n",mode.c_str(),checks,failures,frame);return failures?1:0;}
