#include "Application.h"
#include "EngineHost.h"
#include "InteractivePlay.h"
#include "RuntimeWorld.h"
#include "SceneSession.h"
#include "WorldPersistence.h"
#include "SaveService.h"
#include "WorldStreaming.h"
#include "ScreenshotWriter.h"
#include "PerformanceProfiler.h"
#include "WorldPresentation.h"
#include <SDL2/SDL.h>
#include <filesystem>
#include <thread>
#include <cstdio>
namespace {unsigned checks=0,failures=0;void check(bool v,const char* msg){++checks;failures+=!v;std::printf("%s %s\n",v?"PASS":"FAIL",msg);std::fflush(stdout);}void key(SDL_Scancode k,bool down){SDL_Event e{};e.type=down?SDL_KEYDOWN:SDL_KEYUP;e.key.keysym.scancode=k;e.key.keysym.sym=SDL_GetKeyFromScancode(k);SDL_PushEvent(&e);}}
int main(int argc,char** argv){if(argc<4){std::fprintf(stderr,"usage: %s <project.judasproj> <mode> <output-dir> (modes: probe write read stream lifetime game input mechanics support radial perf-baseline perf-failing perf-settled)\n",argv[0]);return 2;}std::string project=argv[1],mode=argv[2],out=argv[3],error;std::filesystem::create_directories(out);unsigned frame=0,phase=0,resumed=0;uint64_t epoch=0,region=0;uint64_t resumedRevision=0;EntityId removed=0,travel=0,annex=0;RuntimeWorld* initial=nullptr;bool frozen=false;GameSnapshot expected;glm::vec3 propBefore{};std::vector<EntityId> performanceOwners;ApplicationControl control;control.hidden=mode!="input";setenv("JUDAS_PROFILE","1",1);control.hostReady=[&](EngineHost& h){h.GetWindow().SetTestInputMode(mode!="input");SDL_GL_SetSwapInterval(0);std::string e;h.Audio().Init(e,true);};control.frameSeconds=[&](float){return frozen?0.f:1.f/60;};control.worldReady=[&](EngineHost&,RuntimeWorld& w,InteractivePlay&){initial=&w;};
control.beforeFrame=[&](EngineHost& h,RuntimeWorld& w,InteractivePlay&){h.GetRenderer().ResetStats();
 if(mode=="write"&&frame>=140&&phase==1){auto* stream=w.SceneControl()->Streaming(w,error);if(stream->Regions().front().state=="active"){key(SDL_SCANCODE_F5,true);phase=5;}}else if(mode=="write"&&phase==5)key(SDL_SCANCODE_F5,false);
 if(mode=="read"&&phase==1){key(SDL_SCANCODE_F8,true);phase=2;}else if(mode=="read"&&phase==2)key(SDL_SCANCODE_F8,false);
 if(mode=="read"&&&w!=initial&&!resumed){resumed=frame;frozen=true;std::map<std::string,SaveChunk> chunks;bool captured=WorldPersistence::Capture(w,chunks,error);std::printf("RESTORE capture=%d error=%s bodies=%zu\n",captured,error.c_str(),w.Physics().AliveBodyCount());check(captured||error.find("required script instance not initialized")!=std::string::npos,"capture defers before restored JS lifecycle initialization");check(chunks.count("deformables")&&chunks.at("deformables").data==expected.participants.at("deformables").data,"cold process restores exact plastic/topology/motion and owned constraint history");check(w.RuntimeDeformable(100,error)->fracture.removed[8]&&!w.FracturePartEntity(100,8),"removed fragment is not resurrected");phase=3;}
};
control.afterFrame=[&](EngineHost& h,RuntimeWorld& w,InteractivePlay& play){++frame;bool healthy=w.Scripts()&&w.Scripts()->Diagnostics().empty();if(!healthy){for(auto& d:w.Scripts()->Diagnostics())std::printf("SCRIPT %s %s\n",d.callback.c_str(),d.message.c_str());check(false,"public project scripts healthy");w.UI().RequestQuit();return;}
 auto* panel=w.RuntimeDeformable(100,error);auto* beam=w.RuntimeDeformable(200,error);bool game=mode=="game";bool probe=mode=="probe"||mode=="radial";if(panel&&!panel->error.empty()){std::printf("ERROR %s\n",panel->error.c_str());check(false,"fracture solve healthy");w.UI().RequestQuit();return;}if(beam&&!beam->error.empty()){std::printf("ERROR beam %s\n",beam->error.c_str());check(false,"deformed fracture solve healthy");w.UI().RequestQuit();return;}
 if(frame==40&&beam)std::printf("BEAM initial revision=%llu peak=%.6g\n",(unsigned long long)beam->fracture.revision,std::max(*std::max_element(beam->fracture.tensionDemand.begin(),beam->fracture.tensionDemand.end()),*std::max_element(beam->fracture.shearDemand.begin(),beam->fracture.shearDemand.end())));
 if(mode=="input"){
  auto& window=h.GetWindow();auto click=[&](bool down){SDL_Event e{};e.type=down?SDL_MOUSEBUTTONDOWN:SDL_MOUSEBUTTONUP;e.button.windowID=SDL_GetWindowID(window.NativeWindow());e.button.button=SDL_BUTTON_LEFT;SDL_PushEvent(&e);};
  auto aim=[&](glm::vec3 origin,glm::vec3 target){w.Scripts()->SetView(glm::lookAt(origin,target,glm::vec3(0,0,1)));};
  auto shots=[&](){for(auto& state:w.Scripts()->Capture())if(state.entity==11)return state.json;return std::string();};
  if(frame==40){
   check(w.pointerCapture,"project requests gameplay pointer capture");
   std::printf("CAPTURE initial requested=%d relative=%d grab=%d flags=%u\n",window.IsMouseCaptured(),SDL_GetRelativeMouseMode(),SDL_GetWindowGrab(window.NativeWindow()),SDL_GetWindowFlags(window.NativeWindow()));
   check(SDL_GetRelativeMouseMode()&&SDL_GetWindowGrab(window.NativeWindow()),"visible window initially owns backend relative mode and mouse grab");
   SDL_SetRelativeMouseMode(SDL_FALSE);SDL_SetWindowGrab(window.NativeWindow(),SDL_FALSE);
  }
  if(frame==41){
   check(SDL_GetRelativeMouseMode()&&SDL_GetWindowGrab(window.NativeWindow()),"backend capture loss without a focus event is reconciled");
   aim({20,2,8},{20,0,8});click(true);
  }
  if(frame==42){click(false);check(shots().find("\"shots\":1")!=std::string::npos,"click on static floor is handled once without disabling controls");}
  if(frame==43){aim({20,2,8},{20,0,8});click(true);}
  if(frame==44){click(false);check(shots().find("\"shots\":2")!=std::string::npos,"subsequent click still reaches project script");key(SDL_SCANCODE_ESCAPE,true);}
  if(frame==45){key(SDL_SCANCODE_ESCAPE,false);check(play.IsPaused()&&!window.IsMouseCaptured()&&!SDL_GetRelativeMouseMode()&&!SDL_GetWindowGrab(window.NativeWindow()),"pause still releases actual capture after floor clicks");click(true);}
  if(frame==46){click(false);check(shots().find("\"shots\":2")!=std::string::npos,"menu click cannot apply a gameplay impulse");key(SDL_SCANCODE_ESCAPE,true);}
  if(frame==47){key(SDL_SCANCODE_ESCAPE,false);check(!play.IsPaused()&&window.IsMouseCaptured()&&SDL_GetRelativeMouseMode()&&SDL_GetWindowGrab(window.NativeWindow()),"resume restores windowed relative capture and grab");
   auto body=w.RuntimeBody(400);propBefore=w.Physics().GetLinearVelocity(body);auto point=w.Physics().GetTransform(body).position;aim(point+glm::vec3(0,2,2),point);click(true);
  }
  if(frame==48){click(false);check(glm::length(w.Physics().GetLinearVelocity(w.RuntimeBody(400))-propBefore)>1,"ordinary tagged dynamic prop receives real hit-point impulse");check(shots().find("\"shots\":3")!=std::string::npos,"dynamic prop shot counted once");}
  if(frame==49){key(SDL_SCANCODE_ESCAPE,true);}
  if(frame==50){key(SDL_SCANCODE_ESCAPE,false);check(play.IsPaused(),"pause remains functional after all representative clicks");w.UI().RequestQuit();phase=9;}
 }
 if(frame==40&&mode!="input"){check(panel&&panel->asset->fracture,"normal asynchronous fracture asset publication");if(!panel){w.UI().RequestQuit();return;}epoch=panel->generation;if(game)check(!w.AudioEmitters().empty()&&w.AudioEmitters().front().obstruction>0,"normal audio obstruction observes intact barrier");check(!w.RuntimeBody(100).IsValid(),"logical family owner has no duplicate collider/mass");double mass=0;for(unsigned p=0;p<panel->asset->fracture->parts.size();++p){auto id=w.FracturePartEntity(100,p);check(id&&w.Physics().IsDynamicBody(w.RuntimeBody(id)),"every stiff part is an ordinary safe rigid body");mass+=w.RuntimeDefinition(id)->body->mass;}check(std::abs(mass-panel->Mass())<1e-4,"published cells partition material mass exactly once");check(panel->fracture.revision==1,"modest supported gravity load survives");if(mode=="read"){auto* service=w.SceneControl()->Saves(h.Resources());SaveStorage store(service->Root());bool recovered=false;check(store.Read("fracture-current",expected,recovered,error),"cold process reads real M61 slot");phase=1;}
 else if(probe||mode=="write"||game){w.LoadFracturePart(100,4,{0,0,-120},true);phase=1;}

 else if(mode.rfind("perf-",0)==0){
  for(auto id:{200u,300u,450u,501u})w.DestroyEntity(id);
  if(mode=="perf-baseline")w.DestroyEntity(100);else{performanceOwners.push_back(100);for(unsigned i=0;i<9;++i){auto d=*w.RuntimeDefinition(100);d.id=0;d.scripts.clear();d.transform.position={float((i%3)*4),2,float(-5-int(i/3)*4)};performanceOwners.push_back(w.CreateEntity(d,nullptr,&error));}}phase=1;
 }
 else if(mode=="mechanics"){
  auto definition=*w.RuntimeDefinition(100);definition.id=0;definition.scripts.clear();definition.deformable->attachments.clear();definition.transform.position={50,30,0};definition.transform.rotation=glm::angleAxis(.65f,glm::normalize(glm::vec3(1,2,3)));auto id=w.CreateEntity(definition,nullptr,&error);auto* sim=w.RuntimeDeformable(id,error);check(sim!=nullptr,"independent runtime family shares immutable cook");
  glm::dvec3 velocity(1,2,3),omega(.2,.4,.6),com(0),linear(0),angular(0);double mass=sim->Mass();for(unsigned n=0;n<sim->positions.size();++n)com+=sim->positions[n]*sim->NodeMass(n);com/=mass;
  for(unsigned n=0;n<sim->positions.size();++n){sim->velocities[n]=velocity+glm::cross(omega,sim->positions[n]-com);linear+=sim->velocities[n]*sim->NodeMass(n);angular+=glm::cross(sim->positions[n]-com,sim->velocities[n]*sim->NodeMass(n));}
  check(w.PrepareRigidFracture(id,error),"finite rigid ownership publication prepares all cells");glm::dvec3 childLinear(0),childAngular(0),childCom(0);double childMass=0;
  for(unsigned part=0;part<sim->asset->fracture->parts.size();++part){auto body=w.RuntimeBody(w.FracturePartEntity(id,part));double m=w.RuntimeDefinition(w.FracturePartEntity(id,part))->body->mass;auto pose=w.Physics().GetTransform(body);glm::dvec3 v=w.Physics().GetLinearVelocity(body),o=w.Physics().GetAngularVelocity(body);childMass+=m;childCom+=glm::dvec3(pose.position)*m;childLinear+=m*v;childAngular+=glm::cross(glm::dvec3(pose.position)-com,m*v)+glm::dmat3(w.Physics().GetInertiaWorld(body))*o;
   check(glm::length(v-(velocity+glm::cross(omega,glm::dvec3(pose.position)-com)))<1e-4&&glm::length(o-omega)<1e-4,"child receives source point and angular velocity without a new impulse");
  }
  std::printf("MOMENTUM mass=%.9g com_error=%.9g linear_error=%.9g angular_error=%.9g\n",childMass,glm::length(childCom/childMass-com),glm::length(childLinear-linear),glm::length(childAngular-angular));check(std::abs(childMass-mass)<1e-4&&glm::length(childCom/childMass-com)<1e-5&&glm::length(childLinear-linear)<1e-3&&glm::length(childAngular-angular)<1e-3,"lumped material mass COM linear/angular momentum preserved by rigid fit");
  auto requiredChild=w.FracturePartEntity(id,0);w.SetTransientEntity(requiredChild,true,error);std::map<std::string,SaveChunk> unsupported;check(!WorldPersistence::Capture(w,unsupported,error)&&error.find("required fracture body missing/transient")!=std::string::npos,"save preflight rejects omitted required physical material");w.SetTransientEntity(requiredChild,false,error);
  auto positions=sim->positions;auto velocities=sim->velocities;for(unsigned b=0;b<sim->asset->fracture->bonds.size();++b)sim->fracture.Request(*sim->asset->fracture,b,sim->fracture.revision);w.UpdateRigidFracture(id,1./60);double difference=0;for(unsigned n=0;n<positions.size();++n)difference=std::max(difference,glm::length(positions[n]-sim->positions[n])+glm::length(velocities[n]-sim->velocities[n]));check(difference<1e-5&&sim->Mass()==mass,"unforced complete cut retains current positions/motion and exact mass");
  auto child=w.FracturePartEntity(id,0);auto oldBody=w.RuntimeBody(child);JointSettings attachment;attachment.bodyA=oldBody;attachment.bodyB=w.RuntimeBody(400);attachment.type=JointType::Ball;auto point=w.Physics().GetTransform(oldBody).position;auto target=w.Physics().GetTransform(attachment.bodyB);attachment.anchorB=glm::inverse(target.rotation)*(point-target.position);auto joint=w.Physics().CreateJoint(attachment);sim->fracture.RequestRemoval(*sim->asset->fracture,1,sim->fracture.revision);w.UpdateRigidFracture(id,1./60);JointState state;check(w.Physics().GetJoint(joint,state)&&state.settings.bodyA.id==oldBody.id,"ordinary attachment on surviving material remains valid after another part is removed");
  w.SetDeformableEnabled(id,false);check(!w.Physics().IsBodyEnabled(oldBody),"family disable immediately disables descendant colliders");w.SetDeformableEnabled(id,true);check(w.Physics().IsBodyEnabled(oldBody),"family enable resumes retained material");auto softRevision=beam->fracture.revision;beam->fracture.Request(*beam->asset->fracture,0,softRevision);w.SetDeformableEnabled(200,false);w.UpdateDeformables(1./60);check(beam->fracture.revision==softRevision,"disabled soft family defers topology publication");w.SetDeformableEnabled(200,true);w.UpdateDeformables(1./60);check(beam->fracture.revision>softRevision,"reenabled soft family publishes pending cut at normal fixed boundary");
  w.DestroyEntity(id);check(!w.Physics().GetJoint(joint,state)&&!w.Physics().IsDynamicBody(oldBody),"family destruction removes bodies and attached constraints safely");auto replacementDefinition=*w.RuntimeDefinition(400);replacementDefinition.id=0;auto replacement=w.CreateEntity(replacementDefinition,nullptr,&error);check(replacement&&w.RuntimeBody(replacement).id!=oldBody.id,"body slot reuse cannot alias old generation");w.UI().RequestQuit();phase=9;
 }
 else if(mode=="stream"){region=w.SceneControl()->Streaming(w,error)->Request("annex",false,error);phase=1;}
 else if(mode=="support"){phase=1;}
 else if(mode=="lifetime"){w.SceneControl()->Request("Scenes/radial.judas",error);phase=1;}
 }
 if((probe||mode=="write"||game)&&frame==65){check(panel->fracture.revision>1,"real impulse causes physically detected failure without explicit release");check(std::any_of(panel->fracture.broken.begin(),panel->fracture.broken.end(),[](auto b){return b==1;}),"physical failure cause distinct from tool release");check(panel->Mass()>0,"remaining material persists");for(unsigned b=0;b<panel->fracture.broken.size();++b)std::printf("BOND %u broken=%u tension=%g shear=%g\n",b,panel->fracture.broken[b],panel->fracture.tensionDemand[b],panel->fracture.shearDemand[b]);if(beam)beam->Force("right",{0,0,5});}
 if((probe||mode=="write")&&frame>65&&frame<115)beam->Force("right",{0,0,frame<90?5.:120.});
 if((probe||mode=="write")&&frame==89){double dent=0;for(unsigned t=0;t<beam->plasticRest.size();++t)dent+=glm::length(beam->plasticRest[t][0]-beam->asset->solids[t].rest[0]);std::printf("PREBREAK plastic=%g revision=%llu peak=%.6g\n",dent,(unsigned long long)beam->fracture.revision,std::max(*std::max_element(beam->fracture.tensionDemand.begin(),beam->fracture.tensionDemand.end()),*std::max_element(beam->fracture.shearDemand.begin(),beam->fracture.shearDemand.end())));check(dent>.0001&&beam->fracture.revision==1,"modest load yields material without breaking it");}
 if((probe||mode=="write")&&frame==115){double dent=0;for(unsigned t=0;t<beam->plasticRest.size();++t)dent+=glm::length(beam->plasticRest[t][0]-beam->asset->solids[t].rest[0]);std::printf("BEAM plastic=%g revision=%llu peak=%.6g\n",dent,(unsigned long long)beam->fracture.revision,std::max(*std::max_element(beam->fracture.tensionDemand.begin(),beam->fracture.tensionDemand.end()),*std::max_element(beam->fracture.shearDemand.begin(),beam->fracture.shearDemand.end())));check(dent>.0001&&beam->fracture.revision>1,"yielding soft specimen breaks from current plastic state");
  if(mode=="write"){auto* structure=w.RuntimeDeformable(300,error);check(structure->fracture.Request(*structure->asset->fracture,0,structure->fracture.revision),"save fixture retains an opened interface with an alternate connected load path");}
  travel=w.FracturePartEntity(100,4);removed=w.FracturePartEntity(100,8);check(travel&&removed,"source-part mapping reacquires current descendants");if(travel){auto t=w.RuntimeDefinition(travel)->transform;t.position={43,2,0};w.SetRuntimeTransform(travel,t);w.Physics().SetLinearVelocity(w.RuntimeBody(travel),{.2f,0,0});}if(removed)w.DestroyEntity(removed);region=w.SceneControl()->Streaming(w,error)->Request("annex",false,error);
 }
 if(probe&&frame==160){check(panel->fracture.removed[8]&&!w.RuntimeDefinition(removed),"explicit piece cleanup leaves durable tombstone");check(w.Physics().AliveBodyCount()>10,"ordinary surviving rubble remains simulated");auto poses=panel->positions;auto camera=w.view->pose;auto v=glm::mat4_cast(glm::inverse(camera.rotation))*glm::translate(glm::mat4(1),-camera.position),p=glm::perspective(glm::radians(65.f),1.f,.1f,100.f);RenderWorldFrame(h.GetRenderer(),640,360,w,nullptr,v,p,camera.position,.5f);check(panel->positions==poses,"main/secondary/shadow passes do not rerun fracture");std::vector<unsigned char> pixels;h.GetRenderer().CaptureFrame(h.GetWindow().Width(),h.GetWindow().Height(),pixels);WriteRgbPng((std::filesystem::path(out)/"lab.png").string(),h.GetWindow().Width(),h.GetWindow().Height(),pixels);std::printf("LAB bodies=%zu fixed_ms=%.6f draws=%u\n",w.Physics().AliveBodyCount(),play.LastFixedStepMilliseconds(),h.GetRenderer().Stats().drawCalls);w.UI().RequestQuit();phase=9;}
 if(mode=="write"&&frame>141){auto* service=w.SceneControl()->Saves(h.Resources());for(uint64_t id=1;id<16;++id)if(auto* s=service->Status(id)){if(s->state=="failed"){std::printf("SAVE ERROR %s\n",s->error.c_str());check(false,"save completes");w.UI().RequestQuit();phase=9;}else if(s->state=="completed"){check(s->operation=="save","public JS saves complete fracture family through M61");w.UI().RequestQuit();phase=9;}}}
 if(mode=="support"){auto* structure=w.RuntimeDeformable(300,error);if(frame>40&&frame<80)w.LoadFracturePart(300,5,{0,-100,0},false);if(frame==80){check(structure&&structure->fracture.revision==1,"multi-supported structure holds modest load");check(structure->Release("right"),"ordinary right support release");}if(frame>80&&frame<170)w.LoadFracturePart(300,5,{0,-4000,0},false);if(frame==170){check(structure->fracture.revision>1&&std::any_of(structure->fracture.broken.begin(),structure->fracture.broken.end(),[](auto b){return b==1;}),"remaining load path fails from solved redistribution after support release");w.UI().RequestQuit();phase=9;}}
 if(mode=="read"&&resumed){if(frame==resumed+1)frozen=false;if(frame==resumed+4){check(panel&&panel->fracture.revision>1&&!panel->error.size(),"first resumed fracture state remains healthy");auto* structure=w.RuntimeDeformable(300,error);resumedRevision=structure->fracture.revision;check(resumedRevision>1&&std::any_of(structure->fracture.broken.begin(),structure->fracture.broken.end(),[](auto b){return !b;}),"cold save includes partially broken surviving connected material");check(w.LoadFracturePart(300,4,{0,-1000,0},true),"surviving connected material accepts another physical load after cold restore");}
  if(frame>resumed+15){check(healthy&&!panel->error.size()&&w.RuntimeDeformable(300,error)->fracture.revision>resumedRevision,"cold restore continues ordinary dynamics without healing/replayed notifications");w.UI().RequestQuit();phase=9;}}
 if(mode=="stream"&&frame>40){auto* stream=w.SceneControl()->Streaming(w,error);auto status=stream->Regions().front();if(phase==1&&status.state=="active"){annex=stream->Resolve("annex",1);auto* s=w.RuntimeDeformable(annex,error);if(s&&w.FracturePartEntity(annex,0)){w.LoadFracturePart(annex,0,{20,0,0},true);stream->Release(region);phase=2;}}
  if(phase==2&&status.state=="active"&&!status.pins.empty()){check(w.RuntimeDefinition(annex)&&status.pins[0].find("fracture")!=std::string::npos,"travelling live family explicitly pins its source region; never pretends unloaded");auto id=w.FracturePartEntity(annex,0);auto t=w.RuntimeDefinition(id)->transform;t.position={0,4,0};w.SetRuntimeTransform(id,t);region=stream->Request("annex",false,error);check(stream->Resolve("annex",1)==annex,"revisit retained region does not duplicate/recreate original material");stream->Release(region);key(SDL_SCANCODE_H,true);phase=7;}
  if(phase==7){key(SDL_SCANCODE_H,false);if(stream->Owner(annex)=="root"){check(true,"authored H input drives public JS adoption to root residency");phase=3;}}
  if(phase==3&&status.state=="unloaded"){check(w.RuntimeDefinition(annex)&&w.FracturePartEntity(annex,0),"source region truly unloads while adopted travelling material remains");region=stream->Request("annex",false,error);phase=4;}if(phase==4&&status.state=="active"){check(!stream->Resolve("annex",1)&&w.RuntimeDefinition(annex),"revisit does not resurrect adopted authored family");auto child=w.FracturePartEntity(annex,0);auto body=w.RuntimeBody(child);w.DestroyEntity(annex);check(!w.RuntimeDefinition(child)&&!w.Physics().IsDynamicBody(body),"full-family removal cleans adopted descendants and constraints");stream->Release(region);w.UI().RequestQuit();phase=9;}}
 if(mode=="lifetime"&&frame==90){check(panel&&panel->generation!=epoch&&w.SceneControl()->Current().find("radial")!=std::string::npos,"scene transition reconstructs fresh independent fracture state");check(w.Gravity().Sample({6,2,0}).x<-.1,"actual radial gravity selected away from local oblique zone");epoch=panel->generation;w.SceneControl()->Reload(error);}
 if(mode=="lifetime"&&frame==140){check(panel&&panel->generation!=epoch&&panel->fracture.revision==1,"reload destroys old families/joints and reconstructs intact authored state");w.UI().RequestQuit();phase=9;}
 if((mode=="perf-failing"||mode=="perf-settled")&&frame==100)for(auto id:performanceOwners)w.LoadFracturePart(id,4,{0,0,-120},true);
 if(mode.rfind("perf-",0)==0&&frame==(mode=="perf-settled"?360u:mode=="perf-failing"?160u:120u)){unsigned bonds=0,broken=0,nodes=0,tets=0;for(auto id:performanceOwners){auto* s=w.RuntimeDeformable(id,error);if(!s)continue;nodes+=s->positions.size();tets+=s->asset->solids.size();bonds+=s->fracture.broken.size();for(auto b:s->fracture.broken)broken+=b!=0;}std::printf("PERFORMANCE mode=%s parts=%zu bodies=%zu nodes=%u tets=%u interfaces=%u broken=%u fixed_ms=%.6f draws=%u\n",mode.c_str(),performanceOwners.size()*9,w.Physics().AliveBodyCount(),nodes,tets,bonds,broken,play.LastFixedStepMilliseconds(),h.GetRenderer().Stats().drawCalls);w.UI().RequestQuit();phase=9;}
 if(game&&frame==70)w.LoadFracturePart(100,1,{0,0,-120},true);
 if(game&&frame==160)std::printf("OPENING early_clear=%d (moving debris can still cross ray)\n",!w.Physics().Raycast({0,1,2},{0,0,-1},4).hit);
 if(game&&frame==300){auto* agent=w.RuntimeCharacter(600);check(!w.RuntimeDefinition(550)->navigationObstacle->enabled,"project policy opens normal navigation obstacle only after a physical hole");check(agent&&agent->position.z>1,"public JS navigation + motor pass through fractured opening");check(!w.Physics().Raycast({0,1,2},{0,0,-1},4).hit,"ordinary ray/audio obstruction path sees physical opening");check(!w.AudioEmitters().empty()&&w.AudioEmitters().front().obstruction==0,"normal audio path clears obstruction after physical opening");w.UI().RequestQuit();phase=9;}
 std::this_thread::sleep_for(std::chrono::milliseconds(1));if(frame>600){check(false,"bounded application deadline");w.UI().RequestQuit();}
};
control.beforeShutdown=[&](EngineHost&,RuntimeWorld&,InteractivePlay&){PerformanceProfiler::Get().Export((std::filesystem::path(out)/"profile.json").string(),error);};if(mode=="radial")project=(std::filesystem::path(project).parent_path()/"Scenes/radial.judas").string();if(mode=="game")project=(std::filesystem::path(project).parent_path()/"Scenes/game.judas").string();Application app;char name[]="judas";char* args[]={name,project.data()};check(app.Run(2,args,&control)==0&&phase==9,"ordinary startup and clean shutdown");std::printf("SUMMARY mode=%s checks=%u failures=%u\n",mode.c_str(),checks,failures);return failures?1:0;}
