#include "EngineHost.h"
#include "Material.h"
#include "Environment.h"
#include "SceneSerialization.h"
#include "SceneFingerprint.h"
#include "GltfLoader.h"
#include "Tangents.h"
#include "SkeletalAnimation.h"
#include <glm/gtc/matrix_transform.hpp>
#include <filesystem>
#include <cstdio>
#include <fstream>
int main(int argc,char** argv){std::string error;unsigned checks=0,failures=0;auto check=[&](bool ok,const char* message){++checks;failures+=!ok;std::printf("%s %s\n",ok?"PASS":"FAIL",message);};std::filesystem::path out=argc>1?argv[1]:"build/m57-tests";std::filesystem::create_directories(out);
 MaterialDefinition m,round;m.metallic=.3;m.maps[0].asset="57575757575757575757575757575701";check(ParseMaterial(SerializeMaterial(m),round,error)&&SerializeMaterial(round)==SerializeMaterial(m),"material round trip");check(!ParseMaterial("JudasMaterial 1 roughness -1",round,error),"invalid parameter rejected");MaterialOverride o;o.roughness=.9;check(ApplyMaterialOverride(m,o).roughness==.9f&&m.roughness==.5f,"isolated instance override");check(ApplyMaterialOverride(m,{}).roughness==m.roughness,"revert returns source");std::vector<MaterialSlot> slots{{m.maps[0].asset,o}},back;check(DecodeMaterialSlots(EncodeMaterialSlots(slots),back,error)&&EncodeMaterialSlots(back)==EncodeMaterialSlots(slots),"slot overrides round trip");
 EngineHost host;check(host.Init("M57 GL material checks",256,256,false,error),"actual OpenGL host");if(failures){std::puts(error.c_str());return 1;}auto& r=host.GetRenderer();std::printf("GPU %s / %s\n",glGetString(GL_VENDOR),glGetString(GL_RENDERER));auto view=glm::lookAt(glm::vec3(0,0,4),glm::vec3(0),glm::vec3(0,1,0));auto projection=glm::perspective(glm::radians(45.f),1.f,.1f,20.f);r.SetCamera(view,projection);r.SetLighting({0,0,1},{1,1,1},{0,0,0});
 // M71's ordinary primitive-only lab exposed a sampler-type conflict that
 // rendering a skinned asset earlier accidentally hid. Prove a cold first
 // draw and shadow without warming either shader with a skin palette.
 check(glGetError()==GL_NO_ERROR,"cold Renderer initialization has no GL errors");
 r.BeginFrame(256,256);r.SetCamera(view,projection);r.SetMaterialBindings({});
 r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,0,0});r.EndFrame();
 std::vector<unsigned char> firstPixels;r.CaptureFrame(256,256,firstPixels);
 const auto firstPixel=(128*256+128)*3;
 check(firstPixels[firstPixel]>150&&firstPixels[firstPixel+1]<30,"first unskinned primitive renders before any skeleton");
 check(glGetError()==GL_NO_ERROR,"first unskinned color draw has no sampler conflict");
 r.BeginShadowPass(0,glm::ortho(-2.f,2.f,-2.f,2.f,.1f,10.f)*view);
 r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,1,1});
 GLint firstViewport[4];glGetIntegerv(GL_VIEWPORT,firstViewport);float firstDepth=1;
 glReadPixels(firstViewport[2]/2,firstViewport[3]/2,1,1,GL_DEPTH_COMPONENT,GL_FLOAT,&firstDepth);
 r.EndShadowPass();check(firstDepth<.9f&&glGetError()==GL_NO_ERROR,"first unskinned shadow writes actual depth without sampler conflict");
 auto render=[&](MaterialDefinition material,bool modern=true,float exposure=1,EnvironmentHandle env=EnvironmentHandle{},glm::quat rotation=glm::quat(1,0,0,0),glm::vec3 scale=glm::vec3(1)){
 auto handle=r.CreateMaterial(material);r.SetSceneAppearance(modern,exposure,env,1,rotation,false);r.BeginFrame(256,256);r.SetCamera(view,projection);r.SetMaterialBindings({{handle,{}}});r.DrawBox({0,0,0},{1,0,0,0},glm::vec3(1,1,.25)*scale,{1,1,1});r.EndFrame();std::vector<unsigned char> image;r.CaptureFrame(256,256,image);auto value=glm::vec3(image[(128*256+128)*3],image[(128*256+128)*3+1],image[(128*256+128)*3+2]);r.DestroyMaterial(handle);return value;};
 m=MaterialDefinition{};m.model=MaterialModel::Unlit;m.baseColor={.21404114f,.21404114f,.21404114f,1};auto value=render(m);check(std::abs(value.x-116)<4,"linear .214 -> Reinhard -> sRGB known output");auto mirror=render(m,true,1,{},glm::quat(1,0,0,0),{-1,.8f,1});check(glm::length(mirror-value)<3,"mirrored nonuniform instance keeps correct face orientation");auto bright=render(m,true,2);check(bright.x>value.x+25,"exposure changes world output");m.maps[0].embedded={1,1,{128,128,128,255}};m.baseColor={1,1,1,1};auto tex=render(m);check(std::abs(tex.x-value.x)<3,"sRGB image decoded exactly once");m.maps[0].embedded={2,1,{0,0,0,255,255,255,255,255}};auto filtered=render(m);check(std::abs(filtered.x-156)<5,"sRGB filtering/mipmaps average in linear light");m.maps[0].embedded={1,1,{255,0,0,0}};m.alpha=MaterialAlpha::Mask;auto masked=render(m);std::printf("PIXEL masked %.0f %.0f %.0f\n",masked.x,masked.y,masked.z);check(std::abs(masked.x-77)<4&&masked.y>75,"alpha cutout discards actual fragments");
 m=MaterialDefinition{};m.roughness=.5f;auto dielectric=render(m);m.metallic=1;auto metal=render(m);std::printf("PIXEL metal %.0f die %.0f\n",metal.x,dielectric.x);check(metal!=dielectric&&metal.x>0,"metallic changes actual GPU response at controlled roughness");m.roughness=1;auto rough=render(m);check(glm::length(rough-metal)>10,"roughness changes GPU specular response");
 m=MaterialDefinition{};m.maps[2].embedded={1,1,{255,128,128,255}};m.normalStrength=0;auto normalOff=render(m);m.normalStrength=1;auto normalOn=render(m);check(normalOff.x>normalOn.x+10,"tangent normal map affects actual direct light");
 EnvironmentData environment;if(argc>2){check(LoadEnvironment(argv[2],environment,error),"baked HDR environment loads");auto bad=environment;bad.specular[0].width=0;auto path=out/"invalid-write.judasenv";{std::ofstream file(path);file<<"keep-good-source";}bool saved=SaveEnvironment(path.string(),bad,error);std::ifstream existing(path);std::string preserved((std::istreambuf_iterator<char>(existing)),{});check(!saved&&preserved=="keep-good-source","invalid environment write preserves existing asset");auto e=r.CreateEnvironment(environment);r.SetLighting({0,0,1},{0,0,0},{0,0,0});m=MaterialDefinition{};m.metallic=1;m.roughness=.06;auto sharp=render(m,true,1,e);m.roughness=.95;auto smooth=render(m,true,1,e);check(glm::length(sharp-smooth)>5,"roughness selects prefiltered environment mip");m.roughness=.06;auto rotated=render(m,true,1,e,glm::angleAxis(glm::radians(90.f),glm::vec3(0,1,0)));check(glm::length(rotated-sharp)>5,"environment authored orientation changes reflection");r.DestroyEnvironment(e);}

 m=MaterialDefinition{};m.model=MaterialModel::Unlit;auto legacyImage=r.CreateTexture({2,1,{0,0,0,255,255,255,255,255}});auto viewMaterial=r.CreateMaterial(m);r.SetSceneAppearance(true,1,{},1,{1,0,0,0},false);r.BeginFrame(256,256);r.SetCamera(view,projection);r.SetMaterialBindings({{viewMaterial,{}}});r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,1,1},1,legacyImage);r.EndFrame();std::vector<unsigned char> viewPixels;r.CaptureFrame(256,256,viewPixels);check(std::abs(int(viewPixels[(128*256+128)*3])-156)<5,"ordinary Render texture slot also filters sRGB in linear light");r.DestroyTexture(legacyImage);r.DestroyMaterial(viewMaterial);
 m=MaterialDefinition{};m.emissive={100000,100000,100000};m.emissiveIntensity=100000;m.roughness=0;auto ceiling=render(m);check(ceiling.x>250&&ceiling.y>250&&ceiling.z>250,"maximum material emission stays finite in HDR and output");
 // Same RGBA bytes retain linear data roles, independent of colour usage.
 r.SetLighting(glm::normalize(glm::vec3(.4f,.2f,1)),{1,1,1},{0,0,0});
 m=MaterialDefinition{};m.metallic=1;m.roughness=1;m.maps[1].embedded={1,1,{128,128,128,255}};auto packed=render(m);m.maps[1].embedded={};m.metallic=128.f/255;m.roughness=128.f/255;auto factors=render(m);check(glm::length(packed-factors)<4,"MR G/B channels sample raw linear values, not sRGB");
 m=MaterialDefinition{};m.emissive={.5f,.1f,.02f};m.emissiveIntensity=4;m.maps[3].embedded={1,1,{0,0,0,255}};auto ao=render(m);m.maps[3].embedded={};auto noAO=render(m);check(glm::length(ao-noAO)<4,"occlusion does not darken direct light or emission");
 auto uiPixel=[&](float exposure){m=MaterialDefinition{};m.model=MaterialModel::Unlit;render(m,true,exposure);r.BeginUIFrame(256,256);r.DrawUIRect({110,110},{36,36},{.2f,.4f,.6f,1});r.EndUIFrame();std::vector<unsigned char> image;r.CaptureFrame(256,256,image);return glm::vec3(image[(128*256+128)*3],image[(128*256+128)*3+1],image[(128*256+128)*3+2]);};check(uiPixel(.5f)==uiPixel(4.f),"display UI remains independent of world exposure");
 // Read the actual shadow depth, not a CPU copy of the alpha predicate.
 auto shadow=[&](bool mask){m=MaterialDefinition{};m.alpha=mask?MaterialAlpha::Mask:MaterialAlpha::Opaque;m.maps[0].embedded={1,1,{255,255,255,0}};auto handle=r.CreateMaterial(m);r.SetMaterialBindings({{handle,{}}});auto matrix=glm::ortho(-2.f,2.f,-2.f,2.f,.1f,10.f)*view;r.BeginShadowPass(0,matrix);r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,1,1});GLint viewport[4];glGetIntegerv(GL_VIEWPORT,viewport);float depth=0;glReadPixels(viewport[2]/2,viewport[3]/2,1,1,GL_DEPTH_COMPONENT,GL_FLOAT,&depth);r.EndShadowPass();r.DestroyMaterial(handle);return depth;};check(shadow(true)>.999f&&shadow(false)<.9f,"cutout shadow silhouette uses actual alpha discard");
 m=MaterialDefinition{};m.alpha=MaterialAlpha::Blend;m.baseColor={.1f,.3f,.6f,.4f};render(m);float depth=0;glReadPixels(128,128,1,1,GL_DEPTH_COMPONENT,GL_FLOAT,&depth);check(depth>.999f,"blended material has no depth writes");

 // A modern secondary target stores radiance, not exposed/display-encoded pixels.
 m=MaterialDefinition{};m.model=MaterialModel::Unlit;m.baseColor={.21404114f,.21404114f,.21404114f,1};auto source=r.CreateMaterial(m);r.SetSceneAppearance(true,4,{},1,{1,0,0,0},false);auto target=r.CreateRenderTarget(64,64,error);check(target.IsValid()&&r.BeginRenderTarget(target),"scene-linear secondary target allocates");r.SetCamera(view,projection);r.SetMaterialBindings({{source,{}}});r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,1,1});r.EndRenderTarget();TextureData cameraPixels;check(r.ReadTextureForDiagnostics(r.RenderTargetTexture(target),cameraPixels)&&std::abs(int(cameraPixels.pixels[(32*64+32)*4])-55)<3,"secondary readback is linear and excludes exposure");
 r.SetSceneAppearance(true,1,{},1,{1,0,0,0},false);r.BeginFrame(256,256);r.SetCamera(view,projection);m.baseColor={1,1,1,1};auto display=r.CreateMaterial(m);r.SetMaterialBindings({{display,{}}});r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,1,1},1,r.RenderTargetTexture(target));r.EndFrame();std::vector<unsigned char> displayPixels;r.CaptureFrame(256,256,displayPixels);check(std::abs(int(displayPixels[(128*256+128)*3])-116)<4,"camera material screen receives one tone/output conversion");
 auto beforeFeedback=r.Stats().feedbackFallbacks;r.BeginRenderTarget(target);r.SetCamera(view,projection);r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,1,1},1,r.RenderTargetTexture(target));r.EndRenderTarget();check(r.Stats().feedbackFallbacks>beforeFeedback,"modern camera self-feedback is rejected");check(r.ResizeRenderTarget(target,96,64,error)&&r.RenderTargetSize(target)==glm::ivec2(96,64),"modern target resize retains ordinary API");r.DestroyRenderTarget(target);r.DestroyMaterial(source);r.DestroyMaterial(display);

 auto fallback=[&](bool failed){r.SetSceneAppearance(true,1,{},1,{1,0,0,0},false);r.BeginFrame(256,256);r.SetCamera(view,projection);r.SetMaterialBindings({{{},{},true,failed}});r.DrawBox({0,0,0},{1,0,0,0},{1,1,.25f},{1,1,1});r.EndFrame();std::vector<unsigned char> pixels;r.CaptureFrame(256,256,pixels);return glm::vec3(pixels[(128*256+128)*3],pixels[(128*256+128)*3+1],pixels[(128*256+128)*3+2]);};auto missing=fallback(true),loading=fallback(false);check(missing.x>missing.y*2&&missing.z>missing.y*2,"missing material uses explicit magenta GPU fallback");check(std::abs(loading.x-loading.y)<3&&loading.x>60,"pending material uses neutral GPU fallback");
 // Mirrored UVs and a degenerate triangle exercise commodity/fallback tangents.
 MeshData tangentMesh;for(auto v:std::vector<MeshVertex>{{{0,0,0},{0,0,1},{0,0}},{{1,0,0},{0,0,1},{1,0}},{{0,1,0},{0,0,1},{0,1}}})tangentMesh.vertices.push_back(v);tangentMesh.indices={0,1,2};check(GenerateMeshTangents(tangentMesh)&&std::abs(tangentMesh.vertices[0].tangent.x)>.9f,"Mikk tangents follow actual UV basis");auto handedness=tangentMesh.vertices[0].tangent.w;for(auto& v:tangentMesh.vertices)v.uv.x=-v.uv.x;check(GenerateMeshTangents(tangentMesh)&&tangentMesh.vertices[0].tangent.w==-handedness,"mirrored UV changes tangent handedness");for(auto& v:tangentMesh.vertices)v.uv={0,0};check(GenerateMeshTangents(tangentMesh)&&std::isfinite(tangentMesh.vertices[0].tangent.x),"degenerate UV fallback remains finite");
 // Normal maps use the same palette and inverse-transpose instance path as geometry.
 MeshData skinned;std::ifstream glb("projects/material_lab/Assets/models/bend_bar.glb",std::ios::binary);std::string glbBytes((std::istreambuf_iterator<char>(glb)),{});check(ParseGltfMesh(glbBytes.data(),glbBytes.size(),skinned,error)&&bool(skinned.skeletal),"normal-map skinned fixture import");
 if(skinned.skeletal){auto gpu=r.CreateMesh(skinned);const auto& a=*skinned.skeletal;auto wave=ResolveSkinMatrices(a.skeleton,SampleClip(a.skeleton,a.clips[0],.5f));auto drawSkin=[&](float strength,const std::vector<glm::mat4>* palette){MaterialDefinition normal;normal.maps[2].embedded={1,1,{220,128,220,255}};normal.normalStrength=strength;auto h=r.CreateMaterial(normal);r.SetSceneAppearance(true,1,{},1,{1,0,0,0},false);r.BeginFrame(256,256);r.SetCamera(glm::lookAt(glm::vec3(0,1.5,6),glm::vec3(0,1.5,0),glm::vec3(0,1,0)),glm::ortho(-2.f,2.f,-1.7f,1.7f,.1f,20.f));r.SetLighting(glm::normalize(glm::vec3(.7f,.3f,1)),{1,1,1},{0,0,0});r.SetMaterialBindings({{h,{}}});r.DrawMesh(gpu,{0,0,0},glm::angleAxis(.4f,glm::normalize(glm::vec3(1,2,3))),{.8f,1.1f,.7f},{},{1,1,1},1,palette);r.EndFrame();std::vector<unsigned char> pixels;r.CaptureFrame(256,256,pixels);r.DestroyMaterial(h);return pixels;};auto noMap=drawSkin(0,&wave),mapped=drawSkin(1,&wave),rest=drawSkin(1,nullptr);check(mapped!=noMap,"actual rotated/nonuniform skinned normal-map path changes lighting");check(mapped!=rest,"moving skin palette deforms normal-mapped geometry");r.DestroyMesh(gpu);}
 check(glGetError()==GL_NO_ERROR,"normal GL3.3 material path produces no GL errors");host.Shutdown();std::printf("M57 %u checks %u failures\n",checks,failures);return failures?1:0;}
