// M66 normal-loop proof: public project scripts, streaming and fresh-process slots.
#include "Application.h"
#include "EngineHost.h"
#include "InteractivePlay.h"
#include "RuntimeWorld.h"
#include "SceneSession.h"
#include "WorldStreaming.h"
#include "SaveService.h"
#include "WorldPersistence.h"
#include "TestInput.h"
#include "PerformanceProfiler.h"
#include "ScreenshotWriter.h"
#include "../third_party/nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <thread>
#include <cstdio>
using Json=nlohmann::json;namespace fs=std::filesystem;
namespace {int checks=0,failures=0;void Check(bool b,const char* s){++checks;failures+=!b;printf("%s %s\n",b?"PASS":"FAIL",s);fflush(stdout);}void Quit(){SDL_Event e{};e.type=SDL_QUIT;SDL_PushEvent(&e);}}
int main(int argc,char** argv){if(argc<4)return 2;std::string project=argv[1],mode=argv[2];fs::path out=argv[3];fs::create_directories(out);bool freeze=false,ready=false,done=false;unsigned frame=0,at=0,phase=0;uint64_t request=0,demand=0;EntityId old=0;std::string error;RuntimeWorld* before=nullptr;Json expected;std::string suspended;bool streamSlot=mode=="stream-write"||mode=="stream-read",streamPrepared=false;bool writing=mode=="write"||mode=="stream-write",reading=mode=="read"||mode=="stream-read";ApplicationControl control;control.hidden=true;
 control.hostReady=[](EngineHost& host){std::string e;SDL_GL_SetSwapInterval(0);host.GetWindow().SetTestInputMode(true);host.Audio().Init(e,true);};control.frameSeconds=[&](float){return freeze?0.f:1.f/60;};
 auto fingerprint=[&](RuntimeWorld& w){auto* a=w.RuntimeAnimation(10);Json j={{"clip",a->playback.clip},{"time",a->playback.time},{"fade",a->mixer.elapsed},{"layers",a->layers.size()},{"ragdoll",w.RagdollActive(11)},{"hidden",w.RuntimeDefinition(10)->render->hiddenParts}};return j;};
 control.beforeFrame=[&](EngineHost& host,RuntimeWorld& w,InteractivePlay&){if(mode=="probe"&&ready){unsigned n=frame-at;for(auto [f,key]:{std::pair<unsigned,SDL_Scancode>{1,SDL_SCANCODE_G},{4,SDL_SCANCODE_J},{7,SDL_SCANCODE_K},{10,SDL_SCANCODE_I},{13,SDL_SCANCODE_T},{16,SDL_SCANCODE_P},{20,SDL_SCANCODE_B},{24,SDL_SCANCODE_F},{45,SDL_SCANCODE_F}}){if(n==f||n==f+1)QueueTestKey(host.GetWindow(),key,n==f);}}
  if(reading&&phase==1&&before!=&w){freeze=true;auto now=fingerprint(w);Check(now.at("clip")==expected.at("clip")&&std::abs(now.at("time").get<float>()-expected.at("time").get<float>())<1e-5,"fresh process restores imported clip time at safe boundary");Check(now.at("hidden")==expected.at("hidden")&&now.at("layers")==expected.at("layers"),"fresh process restores part visibility and mixer layers");Check(now.at("ragdoll")==expected.at("ragdoll"),"fresh process restores full-rig physical subset");SceneTransform hand;Check(w.JointPose(10,"mixamorig:RightHand","world",1,hand),"cold restored socket resolves stable original joint");phase=2;}
 };
 control.afterFrame=[&](EngineHost& host,RuntimeWorld& w,InteractivePlay&){++frame;if(done)return;if(w.Scripts()&&!w.Scripts()->Diagnostics().empty()){for(auto& d:w.Scripts()->Diagnostics())printf("FAULT %s %s\n",d.callback.c_str(),d.message.c_str());Check(false,"ordinary import lab JS callbacks healthy");Quit();return;}
  auto* a=w.RuntimeAnimation(10);if(!ready&&a&&a->asset&&w.BaselineFingerprint().size()==64){ready=true;at=frame;Check(a->asset->skeleton.names.size()==73&&a->asset->skeleton.skinNodes.size()==109,"normal app loads complete original hierarchy plus root-track helper");Check(w.RuntimeAnimation(11)->asset==a->asset&&w.RuntimeAnimation(11)->playback.clip!=a->playback.clip,"normal app shares immutable asset with independent instances");}
  if(!ready){std::this_thread::sleep_for(std::chrono::milliseconds(2));if(frame>1500){Check(false,"bounded cold asset readiness");Quit();}return;}
  if(mode=="probe"){
   auto* stream=w.SceneControl()->Streaming(w,error);if(!stream){Check(false,error.c_str());Quit();return;}
   if(phase==0&&frame-at>240){Check(a->layers.size()==2&&w.RuntimeDefinition(10)->animation->limbs.size()==1,"real logical input drives masked/additive contributions and IK");Check(w.RuntimeDefinition(10)->render->hiddenParts.size()==1,"real JS controls stable part identity");unsigned instances=0;for(auto& o:w.ScriptObjects())instances+=o.render&&o.render->meshAsset==w.RuntimeDefinition(10)->render->meshAsset;Check(instances==4,"real JS spawned original multipart prefab");auto* motor=w.RuntimeCharacter(12);auto p=w.RuntimeDefinition(12)->transform.position;printf("ROOT MOTOR %.5f %.5f %.5f\n",p.x,p.y,p.z);Check(motor&&p.z<-2.3f&&p.z>-5.1f,"extracted root intent moves through motor and stops at ordinary wall");Check(!w.RagdollActive(10),"real activation/deactivation returns through pose resolver");PhysicsQueryFilter proxyFilter;proxyFilter.ignoredBodies={w.RuntimeBody(1),w.RuntimeBody(13),w.RuntimeBody(12)};auto hit=w.Physics().Raycast({-6,4,-8},{0,-1,0},5,proxyFilter);Check(hit.hit&&w.EntityIdOfBody(hit.body)==50&&std::abs(hit.point.y-.28f)<.03f,"clean concave source raycast agrees with analytical visible ramp, not a hull");CharacterMotor probe;probe.settings=w.RuntimeCharacter(12)->settings;probe.Reset({-6,.35f,-8},{1,0,0,0});for(int step=0;step<120;++step){probe.velocity={0,0,0};probe.Step(w.Physics(),w.Gravity(),1.f/60);}printf("PROXY motor %.6f %.6f %.6f support=%llu expected_y=%.6f supported=%d\n",probe.position.x,probe.position.y,probe.position.z,(unsigned long long)w.EntityIdOfBody(probe.result.support),hit.point.y,probe.result.supported);Check(probe.result.supported&&w.EntityIdOfBody(probe.result.support)==50&&std::abs(probe.position.y-hit.point.y)<.04f,"ordinary CharacterMotor stands on matching cooked concavity");demand=stream->Request("rig",false,error);Check(demand!=0,"normal stream request");phase=1;}
   if(phase==1&&(old=stream->Resolve("rig",1))){auto* rig=w.RuntimeAnimation(old);if(!rig||!rig->asset)return;AnimationLayerSettings layer;layer.id="retained";layer.clip="Walking";layer.weight=.3;Check(w.SetAnimationLayer(old,layer,false,error),"streamed full rig uses ordinary mixer");rig->playback.time=.37;rig->playback.speed=0;w.ResolveAnimationPose(*rig,0);freeze=true;Check(WorldPersistence::CaptureAnimation(w,old,suspended,error),"capture exact streamed pose/mixer before retirement");Check(stream->Release(demand)&&stream->Unload("rig"),"complete imported dependency graph retires normally");phase=2;}
   if(phase==2&&!w.RuntimeDefinition(old)){Check(!w.RuntimeAnimation(old),"retired instance exposes no stale animation pointer");demand=stream->Request("rig",false,error);phase=3;}
   if(phase==3){auto id=stream->Resolve("rig",1);if(id&&w.RuntimeAnimation(id)&&w.RuntimeAnimation(id)->asset){Check(id!=old&&w.RuntimeAnimation(id)->layers.size()==1,"stream revisit gets fresh entity and retains mixer state");std::string resumed;Check(WorldPersistence::CaptureAnimation(w,id,resumed,error)&&resumed==suspended,"stream revisit retains exact clip/layers/source/final pose payload");Check(w.Scripts()->Diagnostics().empty(),"normal JS survives stream retirement/revisit");SceneTransform hand;Check(w.JointPose(id,"mixamorig:RightHand","world",1,hand),"stream revisit sockets use retained full hierarchy");before=&w;Check(w.SceneControl()->Reload(error),"ordinary scene reload queued");phase=4;}}
   if(phase==4&&before!=&w&&w.RuntimeBody(50).IsValid()){freeze=false;if(!w.RuntimeBody(12).IsValid())return;Check(w.RuntimeAnimation(10)&&w.RuntimeDefinition(1000)==nullptr,"reload reconstructs scene-owned instances and removes spawned state");printf("RELOAD bodies=%zu\n",w.Physics().AliveBodyCount());for(auto h:w.Physics().AliveBodies())printf("BODY %llu\n",(unsigned long long)w.EntityIdOfBody(h));Check(w.Physics().AliveBodyCount()==4,"reload leaves only authored floor, wall and motor proxy");PerformanceProfiler::Get().Export((out/"profile.json").string(),error);std::vector<unsigned char> pixels;host.GetRenderer().CaptureFrame(host.GetWindow().Width(),host.GetWindow().Height(),pixels);WriteRgbPng((out/"runtime.png").string(),host.GetWindow().Width(),host.GetWindow().Height(),pixels);done=true;Quit();}
  }else{
   auto* service=w.SceneControl()->Saves(host.Resources());
   if(streamSlot&&writing&&!streamPrepared){auto* stream=w.SceneControl()->Streaming(w,error);
    if(phase==0){demand=stream->Request("rig",false,error);phase=10;}
    if(phase==10&&(old=stream->Resolve("rig",1))){auto* rig=w.RuntimeAnimation(old);if(!rig||!rig->asset)return;AnimationLayerSettings layer;layer.id="saved-region";layer.clip="Walking";layer.weight=.3;Check(w.SetAnimationLayer(old,layer,false,error),"retained save region uses full-rig mixer");rig->playback.time=.37;rig->playback.speed=0;w.ResolveAnimationPose(*rig,0);freeze=true;Check(WorldPersistence::CaptureAnimation(w,old,suspended,error),"capture retained save animation");std::ofstream(out/"region-animation.bin",std::ios::binary)<<suspended;Check(stream->Release(demand)&&stream->Unload("rig"),"suspend imported region before disk save");phase=11;}
    if(phase==11&&!w.RuntimeDefinition(old)){streamPrepared=true;phase=0;}
    if(!streamPrepared)return;
   }
   if(phase==0&&frame-at>10){freeze=true;if(writing){AnimationLayerSettings layer;layer.id="persisted";layer.clip="Walking";layer.weight=.4;layer.mask={"mixamorig:Spine"};Check(w.SetAnimationLayer(10,layer,false,error),"saved instance layer uses stable skeleton identity");a->playback.clip="Cruise";a->playback.time=.35;a->mixer.CrossFade(a->playback,"Walking",2);w.ResolveAnimationPose(*a,.3);auto parts=host.Resources().TryGetModelParts(w.RuntimeDefinition(10)->render->meshAsset);Check(parts&&!parts->empty()&&w.SetModelPartVisible(10,parts->front().part,false),"saved instance part visibility authored by stable key");Check(w.EnterRagdoll(11,error),"saved independent original rig physical subset");expected=fingerprint(w);std::ofstream(out/"expected.json")<<expected.dump(2)<<'\n';request=service->Request("save","m66","Original full rig","{}",error);}else{std::ifstream file(out/"expected.json");file>>expected;before=&w;request=service->Request("load","m66","","{}",error);}Check(request!=0,error.empty()?"modern slot request":error.c_str());phase=1;}
   if(request){auto* status=service->Status(request);if(status&&status->state=="failed"){Check(mode=="reject"&&&w==before,"changed imported content rejects old save without replacing world");printf("SAVE ERROR %s\n",status->error.c_str());done=mode=="reject";Quit();}else if(status&&status->state=="completed"&&writing){Check(true,"unchanged imported content committed through normal SaveService");done=true;Quit();}else if(reading&&phase==2){if(streamSlot){auto* stream=w.SceneControl()->Streaming(w,error);if(!demand){demand=stream->Request("rig",false,error);return;}auto id=stream->Resolve("rig",1);if(!id||!w.RuntimeAnimation(id)||!w.RuntimeAnimation(id)->asset)return;std::ifstream original(out/"region-animation.bin",std::ios::binary);suspended.assign(std::istreambuf_iterator<char>(original),{});std::string resumed;Check(WorldPersistence::CaptureAnimation(w,id,resumed,error)&&resumed==suspended,"fresh process reactivates retired full-rig pose/mixer snapshot exactly");}Check(w.Scripts()->Diagnostics().empty(),"restore lifecycle binds UI without resetting saved motor/mixer");done=true;Quit();}}
  }
  std::this_thread::sleep_for(std::chrono::milliseconds(1));if(frame>2400){Check(false,"normal-loop bounded completion");Quit();}
 };
 Application app;char name[]="judas";char* args[]={name,project.data()};Check(app.Run(2,args,&control)==0&&done,"ordinary project process startup/lifecycle/shutdown");printf("SUMMARY mode=%s checks=%d failures=%d frames=%u\n",mode.c_str(),checks,failures,frame);return failures?1:0;
}
