#include "EngineHost.h"
#include "RuntimeWorld.h"
#include "WorldPresentation.h"
#include "SceneSerialization.h"
#include "ModelLoader.h"
#include "SkeletalAnimation.h"
#include "PoseComposition.h"
#include "PerformanceProfiler.h"
#include "ScreenshotWriter.h"
#include "Project.h"
#include "Prefab.h"
#include <glm/gtc/matrix_transform.hpp>
#include <filesystem>
#include <cstdio>
#include <chrono>
#include <algorithm>
namespace fs=std::filesystem;
unsigned checks=0,failures=0;void Check(bool ok,const char* s){++checks;failures+=!ok;printf("%s %s\n",ok?"PASS":"FAIL",s);fflush(stdout);}
int main(int argc,char** argv){fs::path out=argc>1?argv[1]:"/tmp/m66-runtime";fs::create_directories(out);std::string error;Project project;Check(project.Load("projects/import_lab/import_lab.judasproj",error),"ordinary registered import project");Scene scene;Check(LoadSceneFromFile(project.StartupScenePath(),scene,error),"import lab authored scene parses");if(failures){puts(error.c_str());return 1;}
 EngineHost host;Check(host.Init("M66 runtime GL",640,480,false,error),"normal GL 3.3 EngineHost");if(failures)return 1;host.OpenProjectAssets(project.RootDir(),project.AssetsDir());auto& r=host.GetRenderer();auto& resources=host.Resources();auto asset=scene.Find(10)->render->meshAsset;auto begin=std::chrono::steady_clock::now();resources.AddRef(asset);resources.GetMesh(asset,error);resources.WaitForAll();auto model=resources.GetMesh(asset,error);double cold=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();Check(model.IsValid()&&resources.TryGetSkeletal(asset),"cold cooked async load and owner-thread GPU publication");if(!model.IsValid()){puts(error.c_str());return 1;}
 auto frame=[&](MeshHandle mesh,const std::vector<glm::mat4>* palette,const std::vector<std::string>* hidden=nullptr){r.BeginFrame(640,480);r.SetSceneAppearance(true,1,{},1,{1,0,0,0},false,{0,0,0});r.SetDynamicLights({});r.SetMaterialBindings({});r.SetLighting({0,0,1},{1,1,1},{.2,.2,.2});r.SetCamera(glm::lookAt(glm::vec3(1,1,8),glm::vec3(1,1,0),glm::vec3(0,1,0)),glm::ortho(-2.f,2.f,-1.5f,1.5f,.1f,30.f));r.DrawMesh(mesh,{0,0,0},{1,0,0,0},{1,1,1},{},{1,1,1},1,palette,hidden);r.EndFrame();std::vector<unsigned char> p;r.CaptureFrame(640,480,p);return p;};
 auto capacityId=scene.Find(20)->render->meshAsset;resources.AddRef(capacityId);resources.GetMesh(capacityId,error);resources.WaitForAll();auto capacity=resources.GetMesh(capacityId,error);auto high=resources.TryGetSkeletal(capacityId);Check(capacity.IsValid()&&high&&high->skeleton.skinNodes.size()==256,"256-joint resource reaches same GPU architecture");if(!high)return 1;auto p0=ResolveSkinMatrices(high->skeleton,SampleClip(high->skeleton,high->clips[0],0)),p1=ResolveSkinMatrices(high->skeleton,SampleClip(high->skeleton,high->clips[0],1));auto pixels0=frame(capacity,&p0),pixels1=frame(capacity,&p1);auto centroid=[](auto& p){double x=0,n=0;for(size_t i=0;i<p.size();i+=3)if(p[i]>40||p[i+1]>40||p[i+2]>40){x+=(i/3)%640;++n;}return n?x/n:-1;};double shift=centroid(pixels1)-centroid(pixels0);Check(std::abs(shift-80)<2,"actual high-index eight-influence GPU skinning moves image by analytic 0.5 metres");WriteRgbPng((out/"capacity-256.png").string(),640,480,pixels1);
 auto full=resources.TryGetSkeletal(asset);auto rest=ResolveSkinMatrices(full->skeleton,full->skeleton.rest),moving=ResolveSkinMatrices(full->skeleton,SampleClip(full->skeleton,full->clips[0],.5));auto a=frame(model,&rest),b=frame(model,&moving);Check(a!=b,"all original parts use sampled full-rig skinning");std::vector<std::string> hidden;for(auto& part:*resources.TryGetModelParts(asset))hidden.push_back(part.part);auto blank=frame(model,&moving,&hidden);Check(blank!=b&&centroid(blank)<0,"all six original material parts can be hidden independently in normal renderer");WriteRgbPng((out/"original-rest.png").string(),640,480,a);WriteRgbPng((out/"original-push.png").string(),640,480,b);
 MeshData uvProof;Check(LoadModelMesh("tests/fixtures/m66/material-uv.gltf",uvProof,error),"normal glTF UV1/mirrored/mask material fixture");auto uvMesh=r.CreateMesh(uvProof);auto uvPixels=frame(uvMesh,nullptr);size_t red=0,blue=0;for(size_t i=0;i<uvPixels.size();i+=3){red+=uvPixels[i]>uvPixels[i+2]+15;blue+=uvPixels[i+2]>uvPixels[i]+15;}Check(red>500&&blue==0,"actual GL samples opaque red UV1, not transparent blue UV0, on both reflected parts");uvProof.materials[0].maps[2].embedded={};uvProof.materials[0].maps[2].encodedImage.clear();auto plain=r.CreateMesh(uvProof);auto noNormal=frame(plain,nullptr);Check(noNormal!=uvPixels,"UV1 Mikk tangent-space normal map changes actual lighting");r.DestroyMesh(uvMesh);r.DestroyMesh(plain);
 RuntimeWorld world;Check(world.Build(scene,&resources,error,&project.Settings().classification),"ordinary RuntimeWorld full rig with socket IK ragdoll and motor");resources.WaitForAll();world.UpdateAnimations(.4);auto* first=world.RuntimeAnimation(10);auto* second=world.RuntimeAnimation(11);Check(first&&second&&first->asset==second->asset&&first->playback.clip!=second->playback.clip,"immutable asset shared, independent resolved poses");SceneTransform hand;Check(world.JointPose(10,"mixamorig:RightHand","world",1,hand),"full source hierarchy resolved socket joint access");AnimationLayerSettings layer;layer.id="masked";layer.clip="Walking";layer.mask={"mixamorig:RightArm"};layer.weight=.5;Check(world.SetAnimationLayer(10,layer,false,error),"full rig masked pose contribution");LimbIKSettings ik;ik.id="arm";ik.root="mixamorig:RightArm";ik.middle="mixamorig:RightForeArm";ik.end="mixamorig:RightHand";ik.target={.3,1.2,.4};ik.pole={1,1,0};Check(world.SetLimbIK(10,ik,false,error),"full rig two-bone IK uses normalized metre hierarchy");world.UpdateAnimations(.1);
 r.ResetStats();RenderWorldFrame(r,640,480,world,nullptr,glm::lookAt(glm::vec3(0,3,9),glm::vec3(0,1,0),glm::vec3(0,1,0)),glm::perspective(glm::radians(60.f),640.f/480,.1f,100.f),{0,1,0},1);TextureData secondary;Check(r.Stats().shadowPasses>0&&r.Stats().offscreenPasses==1&&r.ReadTextureForDiagnostics(world.CameraTexture(40),secondary),"full multipart character submitted through normal shadows and secondary camera");size_t occupied=0;for(size_t i=0;i<secondary.pixels.size();i+=4)occupied+=secondary.pixels[i]>50||secondary.pixels[i+1]>50;Check(occupied>100,"secondary camera contains actual rendered content");std::vector<unsigned char> screenshot;r.CaptureFrame(640,480,screenshot);WriteRgbPng((out/"lab-world.png").string(),640,480,screenshot);
 Check(world.EnterRagdoll(10,error),"full original rig accepts existing explicit 13-body physical subset");world.UpdateRagdolls(.016f);Check(world.RagdollActive(10)&&world.AnimationSkin(10)->size()==109,"articulation contributes pose to all per-skin bindings");Check(world.LeaveRagdoll(10,.5,error),"ragdoll leaves through existing pose transition");SceneTransform placement;placement.position={0,2,-3};auto prefab=world.SpawnPrefab("94da9a1a019e04a190341bf4f0d18212",placement,error);world.UpdateAnimations(.1);Check(prefab&&world.RuntimeAnimation(prefab)&&world.DestroyHierarchy(prefab,error),"full multipart prefab runtime lifetime");
 // M56 scopes and actual GL query timings, with CPU submission separated from GPU wait.
 auto& profiler=PerformanceProfiler::Get();profiler.Enable(true);for(int count:{1,10}){std::vector<double> poseTimes,renderTimes;std::vector<AnimationPlayback> players(count);std::vector<std::vector<glm::mat4>> palettes(count);for(int i=0;i<count;++i){players[i].clip="Push";players[i].time=float(i)*.1f;}for(int f=0;f<35;++f){ProfileFrame pf("M66-full-rig");auto start=std::chrono::steady_clock::now();{JUDAS_PROFILE_SCOPE("M66 full rig pose composition");for(int i=0;i<count;++i){auto sampled=players[i].Evaluate(*full,1.f/60);palettes[i]=ResolveSkinMatrices(full->skeleton,sampled);if(palettes[i].size()!=109)return 1;}}poseTimes.push_back(std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count());r.FinishForDiagnostics();start=std::chrono::steady_clock::now();r.BeginFrame(640,480);r.SetCamera(glm::lookAt(glm::vec3(0,3,12),glm::vec3(0,1,0),glm::vec3(0,1,0)),glm::perspective(glm::radians(60.f),640.f/480,.1f,100.f));r.SetLighting({1,2,3},{1,1,1},{.2,.2,.2});RendererProfileScope modelGPU(r,"M66 complete model rendering");for(int i=0;i<count;++i)r.DrawMesh(model,{float(i%5)-2,0,float(i/5)*-2},{1,0,0,0},{1,1,1},{},{1,1,1},1,&palettes[i]);r.EndFrame();modelGPU.End();r.FinishForDiagnostics();renderTimes.push_back(std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count());}std::sort(poseTimes.begin(),poseTimes.end());std::sort(renderTimes.begin(),renderTimes.end());printf("PERF instances=%d cold_load_upload_ms=%.4f pose_median_ms=%.4f pose_p95_ms=%.4f GL_complete_median_ms=%.4f GL_complete_p95_ms=%.4f GL_max_ms=%.4f parts_per_instance=6 palette_bytes_per_instance=%zu\n",count,cold,poseTimes[17],poseTimes[33],renderTimes[17],renderTimes[33],renderTimes.back(),moving.size()*sizeof(glm::mat4));profiler.Export((out/("instances-"+std::to_string(count)+"-profile.json")).string(),error);}
 world.Destroy();Check(!world.AnimationSkin(10)&&world.Build(scene,&resources,error,&project.Settings().classification),"Stop and rebuild release runtime pose and consumer state");world.Destroy();host.Shutdown();printf("SUMMARY checks=%u failures=%u\n",checks,failures);return failures?1:0;}
