#include "ModelCook.h"
#include "PoseComposition.h"
#include "ModelArchive.h"
#include "ModelLoader.h"
#include "ModelCollision.h"
#include "SceneFingerprint.h"
#include "../third_party/nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <thread>
#include <chrono>
#include <glm/gtc/matrix_transform.hpp>
using Json=nlohmann::json;namespace fs=std::filesystem;
namespace {
int checks=0,failures=0;void Check(bool ok,const char* label){++checks;failures+=!ok;std::cout<<(ok?"PASS ":"FAIL ")<<label<<'\n';}
Json Read(const fs::path& p){std::ifstream f(p);return Json::parse(f);}void Write(const fs::path& p,const Json& j){std::ofstream(p)<<j.dump(2)<<'\n';}std::string Hash(const fs::path& p){std::string h,e;SceneFingerprintSha256File(p.string(),h,e);return h;}
bool Cook(const std::string& recipe,ModelCookTask& t){std::string error;bool ok=CookModelRecipe(recipe,t)&&PublishModelImport(t,error);if(!ok)std::cout<<"DIAGNOSTIC "<<t.error<<" "<<error<<'\n';return ok;}
}
int main(int argc,char** argv){try{
 fs::path root=argc>1?argv[1]:"/tmp/judas-m66-reimport";fs::create_directories(root);std::string recipe,error;Check(CreateModelRecipe(root.string(),"tests/fixtures/m66/external.gltf","Assets/model.judasmodel",recipe,error),"recipe copies approved external image and buffer into owned sources");if(recipe.empty()){std::cerr<<error;return 1;}
 ModelCookTask first;Check(Cook(recipe,first),"initial coherent generation publishes");if(!first.success)return 1;auto initial=Hash(first.output);auto settings=Read(recipe);auto owned=root/settings.at("source").get<std::string>();MeshData model;Check(LoadModelMesh(first.output,model,error),"normal runtime loader reads cooked asset without source parser");auto materialKeys=model.materialKeys;std::vector<std::string> parts;for(auto& p:model.primitives)parts.push_back(p.part);
 ModelCookTask same;Check(Cook(recipe,same)&&same.unchanged&&Hash(first.output)==initial,"unchanged recipe preserves output bytes and asset identity");
 auto source=Read(owned);std::swap(source["nodes"][1],source["nodes"][2]); // exchange node records and explicitly repair every index
 auto swapIndex=[](Json& x){int i=x.get<int>();if(i==1)x=2;else if(i==2)x=1;};for(auto& n:source["nodes"])if(n.contains("children"))for(auto& i:n["children"])swapIndex(i);for(auto& scene:source["scenes"])for(auto& i:scene["nodes"])swapIndex(i);for(auto& skin:source["skins"]){for(auto& i:skin["joints"])swapIndex(i);if(skin.contains("skeleton"))swapIndex(skin["skeleton"]);}if(source.contains("animations"))for(auto& a:source["animations"])for(auto& channel:a["channels"])swapIndex(channel["target"]["node"]);Write(owned,source);
 ModelCookTask reorder;Check(Cook(recipe,reorder)&&reorder.assetId==first.assetId,"source node reordering reimports without retargeting asset");MeshData reordered;LoadModelMesh(first.output,reordered,error);std::vector<std::string> reorderedParts;for(auto& p:reordered.primitives)reorderedParts.push_back(p.part);Check(reordered.materialKeys==materialKeys&&reorderedParts==parts,"part and material slot identities survive source order changes");auto accepted=Hash(first.output);
 auto retainedName=source["nodes"][1]["name"].get<std::string>();source["nodes"][1]["name"]="DeletedIdentity";Write(owned,source);ModelCookTask removed;Check(!CookModelRecipe(recipe,removed)&&Hash(first.output)==accepted&&removed.error.find("renamed/deleted")!=std::string::npos,"deleted required joint blocks publication and keeps last generation");// Resolve a reported rename using the actual authored local-name alias seam.
 MeshData renamed;ModelImportSettings aliasOptions;ModelImportReport aliasReport;
 if(!ImportModelSource(owned.string(),aliasOptions,renamed,aliasReport,error))throw std::runtime_error(error);
 std::string renamedKey;for(size_t i=0;i<renamed.skeletal->skeleton.names.size();++i)if(renamed.skeletal->skeleton.names[i]=="DeletedIdentity")renamedKey=SkeletonJointKey(renamed.skeletal->skeleton,int(i));
 auto aliasRecipe=Read(recipe);aliasRecipe["settings"]["nodeAliases"][renamedKey]=retainedName;Write(recipe,aliasRecipe);ModelCookTask alias;
 Check(!renamedKey.empty()&&Cook(recipe,alias),"explicit retained local-name alias resolves reported joint rename");Write(recipe,settings);
 source["nodes"][1]["name"]="Tip"; // restore exact accepted source instead below
 auto original=Read("tests/fixtures/m66/external.gltf");Write(owned,original);ModelCookTask restored;Check(Cook(recipe,restored),"source correction retries normally");accepted=Hash(first.output);
 auto image=owned.parent_path()/"café color.png";auto missing=image.string()+".missing";fs::rename(image,missing);ModelCookTask dependency;Check(!CookModelRecipe(recipe,dependency)&&Hash(first.output)==accepted,"missing dependency preserves accepted generation");Check(!VerifyImportedModelFresh(root.string(),first.output,error),"export rejects stale/missing source instead of silently shipping last-good");fs::rename(missing,image);
 // A first import with missing files must be editable/retryable; explicit
 // remaps point only at already project-owned buffer/image dependencies.
 auto brokenSource=root/"unresolved.gltf";auto unresolved=original;
 unresolved["buffers"][0]["uri"]="missing-geometry.bin";unresolved["images"][0]["uri"]="missing texture.png";Write(brokenSource,unresolved);
 std::string missingRecipe;Check(CreateModelRecipe(root.string(),brokenSource.string(),"Assets/missing.judasmodel",missingRecipe,error),"first missing-dependency import retains editable recipe");
 ModelCookTask missingFirst;Check(!CookModelRecipe(missingRecipe,missingFirst)&&!fs::exists(root/"Assets/missing.judasmodel"),"first missing dependencies do not publish incomplete content");
 auto remapped=Read(missingRecipe);remapped["settings"]["dependencyRemaps"]={{"missing-geometry.bin",(owned.parent_path()/"geometry.bin").lexically_relative(root).generic_string()},{"missing texture.png",image.lexically_relative(root).generic_string()}};Write(missingRecipe,remapped);ModelCookTask remap;
 Check(Cook(missingRecipe,remap),"explicit project-owned glTF buffer and image remaps retry through shared service");
 ModelCookTask cancelled;cancelled.cancel=true;Check(!CookModelRecipe(recipe,cancelled)&&Hash(first.output)==accepted,"cancel before parsing leaves accepted generation intact");fs::remove_all(root/".cache");ModelCookTask rebuilt;Check(Cook(recipe,rebuilt)&&Hash(first.output)==accepted,"empty cache reproduces accepted bytes and stable mappings");
 auto malformed=original;malformed["nodes"][0]["children"]={0};Write(owned,malformed);ModelCookTask bad;Check(!CookModelRecipe(recipe,bad)&&Hash(first.output)==accepted,"cyclic malformed source fails without publication");Write(owned,original);
 // A worker result may become obsolete while waiting for the Edit boundary.
 ModelCookTask staged;auto changedRecipe=Read(recipe);changedRecipe["settings"]["sampleRate"]=61;Write(recipe,changedRecipe);Check(CookModelRecipe(recipe,staged),"asynchronous generation stages before publication");auto staleRecipe=changedRecipe;staleRecipe["settings"]["sampleRate"]=62;Write(recipe,staleRecipe);Check(!PublishModelImport(staged,error)&&Hash(first.output)==accepted,"recipe change between cook and publication rejects obsolete generation");Write(recipe,settings);
 // Change a real dependency without changing its dimensions: use a valid image
 // from the repository, preserving IDs/slots independently of texture content.
 auto savedImage=root/"saved-image.png";fs::copy_file(image,savedImage);fs::copy_file("projects/pose_demo/Assets/textures/particle_soft.png",image,fs::copy_options::overwrite_existing);ModelCookTask texture;Check(Cook(recipe,texture)&&!texture.unchanged&&Hash(first.output)!=accepted,"changed copied texture invalidates its cooked generation");MeshData textured;LoadModelMesh(first.output,textured,error);Check(textured.materialKeys==materialKeys,"changed texture retains authored material slot identities");fs::copy_file(savedImage,image,fs::copy_options::overwrite_existing);ModelCookTask textureRestored;Check(Cook(recipe,textureRestored)&&Hash(first.output)==accepted,"restored dependency reproduces deterministic accepted bytes");
 // Explicit selected displacement is reconstructed on a known analytic fixture.
 std::string motionRecipe;Check(CreateModelRecipe(root.string(),"tests/fixtures/m66/capacity256.gltf","Assets/motion.judasmodel",motionRecipe,error),"root-motion fixture recipe created");auto selection=Read(motionRecipe);MeshData reference;ModelImportSettings options;ModelImportReport report;ImportModelSource("tests/fixtures/m66/capacity256.gltf",options,reference,report,error);auto clipName=reference.skeletal->clips[0].name;auto motionNode=SkeletonJointKey(reference.skeletal->skeleton,1);selection["clips"]=Json::array({{{"sourceClip",clipName},{"name","Extracted"},{"rootMotion",{{"policy","extract"},{"node",motionNode},{"translation",{true,false,false}}}}}});Write(motionRecipe,selection);ModelCookTask extraction;Check(Cook(motionRecipe,extraction),"explicit model-axis root extraction publishes");MeshData extracted;if(LoadModelMesh(extraction.output,extracted,error)){auto& clip=extracted.skeletal->clips[0];double worst=0;for(float time:{0.f,.123f,.5f,1.f}){auto sourcePose=SampleClip(reference.skeletal->skeleton,reference.skeletal->clips[0],time);auto complementary=SampleClip(extracted.skeletal->skeleton,clip,time);auto motion=SampleRootMotion(clip,time,false);auto sourcePalette=ResolveSkinMatrices(reference.skeletal->skeleton,sourcePose),result=ResolveSkinMatrices(extracted.skeletal->skeleton,complementary);auto transform=glm::translate(glm::mat4(1),motion.translation)*glm::mat4_cast(motion.rotation);for(size_t i=0;i<result.size();++i)for(int c=0;c<4;++c)for(int r=0;r<4;++r)worst=std::max(worst,double(std::abs((transform*result[i])[c][r]-sourcePalette[i][c][r])));}Check(worst<1e-5,"extracted motion reconstructs complementary pose without losing unselected axes");}
 auto motionSource=root/"Sources/motion-reordered.gltf";auto motionJson=Read("tests/fixtures/m66/capacity256.gltf");std::swap(motionJson["nodes"][1],motionJson["nodes"][2]);for(auto& n:motionJson["nodes"])if(n.contains("children"))for(auto& i:n["children"])swapIndex(i);for(auto& g:motionJson["scenes"])for(auto& i:g["nodes"])swapIndex(i);for(auto& skin:motionJson["skins"]){for(auto& i:skin["joints"])swapIndex(i);}for(auto& anim:motionJson["animations"])for(auto& channel:anim["channels"])swapIndex(channel["target"]["node"]);Write(motionSource,motionJson);std::vector<AnimationClip> mapped;ModelImportReport mappedReport;Check(ImportCompatibleMotion(motionSource.string(),options,reference.skeletal->skeleton,mapped,mappedReport,error)&&mapped.size()==1,"animation-only source ordering maps by verified hierarchy and skin binding");motionJson["nodes"][1]["name"]="Joint000";Write(motionSource,motionJson);Check(!ImportCompatibleMotion(motionSource.string(),options,reference.skeletal->skeleton,mapped,mappedReport,error),"ambiguous same-path motion joints reject safely");
 Write(motionSource,Read("tests/fixtures/m66/capacity256.gltf"));selection["motions"]=Json::array({{{"source",motionSource.lexically_relative(root).generic_string()},{"take","Translate"},{"name","External"}}});selection["clips"]=Json::array({{{"sourceClip","External"},{"name","External"}}});Write(motionRecipe,selection);ModelCookTask motionFirst;Check(Cook(motionRecipe,motionFirst),"same-rig motion recipe assembles through shared service");auto beforeMotion=Hash(motionFirst.output);std::map<std::string,std::string> baseCaches;for(auto& f:fs::directory_iterator(root/".cache/model-import"))if(f.path().extension()==".judasmodel"&&f.path().string().find(".motion.")==std::string::npos)baseCaches[f.path().string()]=Hash(f.path());auto stepped=Read(motionSource);for(auto& anim:stepped["animations"])for(auto& sampler:anim["samplers"])sampler["interpolation"]="STEP";Write(motionSource,stepped);ModelCookTask motionChanged;bool unchangedBases=true;Check(Cook(motionRecipe,motionChanged)&&Hash(motionChanged.output)!=beforeMotion,"changed compatible clip republishes coherent animation generation");for(auto& [path,hash]:baseCaches)unchangedBases&=Hash(path)==hash;Check(unchangedBases,"motion reimport preserves unrelated cached geometry/material products");
 // Precise defective seam and explicit derived repair preserve source bytes.
 MeshData seam;seam.sourceNodes={"Surface"};seam.vertices.resize(4);seam.vertices[0].position={0,0,0};seam.vertices[1].position={1,0,0};seam.vertices[2].position={0,0,1};seam.vertices[3].position={1,0,1};seam.indices={0,1,2,1,2,3};seam.faceLocations={{0,17},{0,22}};seam.vertexLocations={{0,5},{0,6},{0,7},{0,8}};CollisionAsset collision;CollisionCookSettings cook;CollisionDiagnostic location;Check(!CookCollision(seam,cook,collision,error,&location)&&location.node=="Surface"&&(location.sourceFace==17||location.sourceFace==22),"bad shared-edge winding reports actual source node and face");ModelCollisionCleanup cleanup;cleanup.orientPatches=true;ModelCollisionCleanupReport cleanupReport;MeshData repaired;Check(CleanModelCollision(seam,cleanup,repaired,cleanupReport,error)&&cleanupReport.flipped==1&&CookCollision(repaired,cook,collision,error)&&seam.indices==std::vector<uint32_t>({0,1,2,1,2,3}),"explicit derived orientation repairs one patch and preserves original geometry");
 // Explicit selected twist about a nonzero initial pivot, with vertical
 // motion deliberately unselected. The fixture's axis is Z, not world-up.
 auto turnDirectory=root/"turn-source";fs::create_directories(turnDirectory);
 auto turn=Read("tests/fixtures/m66/capacity256.gltf");
 std::vector<float> turnData={2,1,3,3,2,4,0,0,std::sin(glm::radians(15.f)),std::cos(glm::radians(15.f)),0,0,std::sin(glm::radians(60.f)),std::cos(glm::radians(60.f))};
 std::ofstream turnBytes(turnDirectory/"turn.bin",std::ios::binary);turnBytes.write(reinterpret_cast<const char*>(turnData.data()),std::streamsize(turnData.size()*sizeof(float)));turnBytes.close();
 int buffer=int(turn["buffers"].size());turn["buffers"].push_back({{"uri","turn.bin"},{"byteLength",turnData.size()*sizeof(float)}});
 int view=int(turn["bufferViews"].size());turn["bufferViews"].push_back({{"buffer",buffer},{"byteOffset",0},{"byteLength",24}});turn["bufferViews"].push_back({{"buffer",buffer},{"byteOffset",24},{"byteLength",32}});
 int accessor=int(turn["accessors"].size());turn["accessors"].push_back({{"bufferView",view},{"componentType",5126},{"count",2},{"type","VEC3"}});turn["accessors"].push_back({{"bufferView",view+1},{"componentType",5126},{"count",2},{"type","VEC4"}});
 int timeAccessor=turn["animations"][0]["samplers"][0]["input"];turn["nodes"][1]["translation"]={2,1,3};
 turn["animations"]=Json::array({{{"name","Turn"},{"samplers",Json::array({{{"input",timeAccessor},{"output",accessor},{"interpolation","LINEAR"}},{{"input",timeAccessor},{"output",accessor+1},{"interpolation","LINEAR"}}})},{"channels",Json::array({{{"sampler",0},{"target",{{"node",1},{"path","translation"}}}},{{"sampler",1},{"target",{{"node",1},{"path","rotation"}}}}})}}});
 auto turnPath=turnDirectory/"turn.gltf";Write(turnPath,turn);MeshData turnReference;
 if(!ImportModelSource(turnPath.string(),options,turnReference,report,error))throw std::runtime_error(error);
 std::string turnRecipe;if(!CreateModelRecipe(root.string(),turnPath.string(),"Assets/turn.judasmodel",turnRecipe,error))throw std::runtime_error(error);
 auto chosen=Read(turnRecipe);chosen["clips"]=Json::array({{{"sourceClip","Turn"},{"name","TurnExtract"},{"rootMotion",{{"policy","extract"},{"node",SkeletonJointKey(turnReference.skeletal->skeleton,1)},{"translation",{true,false,true}},{"rotationAxis",{0,0,1}}}}}});Write(turnRecipe,chosen);ModelCookTask turnCook;
 if(!Cook(turnRecipe,turnCook))throw std::runtime_error(turnCook.error);
 MeshData turning;
 if(!LoadModelMesh(turnCook.output,turning,error))throw std::runtime_error(error);
 auto& turnClip=turning.skeletal->clips[0];float turnError=0;
 for(float t:{0.f,.25f,.5f,1.f}){auto expected=ResolveSkinMatrices(turnReference.skeletal->skeleton,SampleClip(turnReference.skeletal->skeleton,turnReference.skeletal->clips[0],t));auto result=ResolveSkinMatrices(turning.skeletal->skeleton,SampleClip(turning.skeletal->skeleton,turnClip,t));auto motion=SampleRootMotion(turnClip,t,false);auto transform=glm::translate(glm::mat4(1),motion.translation)*glm::mat4_cast(motion.rotation);for(size_t i=0;i<result.size();++i)for(int c=0;c<4;++c)for(int r=0;r<4;++r)turnError=std::max(turnError,std::abs((transform*result[i])[c][r]-expected[i][c][r]));}
 Check(turnError<1e-5f,"selected Z twist and nonzero pivot reconstruct source while preserving vertical motion");
 auto half=SampleRootMotion(turnClip,.5,false);auto expectedRotation=glm::angleAxis(glm::radians(45.f),glm::vec3(0,0,1));auto expectedOffset=glm::vec3(.5f,0,.5f)+glm::vec3(2,1,3)-expectedRotation*glm::vec3(2,1,3);
 Check(glm::length(half.translation-expectedOffset)<1e-5f&&std::abs(glm::dot(half.rotation,expectedRotation))>1-1e-6f,"root extraction matches independent analytic selected translation and twist");
 // Real worker cancellation while a selected source is being parsed, followed
 // by bookkeeping retirement. Neither staging nor accepted file is published.
 std::string workerRecipe;Check(CreateModelRecipe(root.string(),".cache/m66/originals/Skateboarder.fbx","Assets/worker.judasmodel",workerRecipe,error),"background source recipe created");JobSystem jobs(1);auto worker=QueueModelImport(jobs,workerRecipe);for(int i=0;i<10000&&!worker->done&&worker->progress<5;++i)std::this_thread::sleep_for(std::chrono::milliseconds(1));worker->cancel=true;jobs.Cancel(worker->job);jobs.Wait(worker->job);Check(!PublishModelImport(*worker,error)&&!fs::exists(root/"Assets/worker.judasmodel"),"running background cancellation never publishes partial rig");jobs.Forget(worker->job);Check(jobs.StateOf(worker->job)==JobState::Unknown,"finished import job record is explicitly retired");
 Json result={{"checks",checks},{"failures",failures}};std::ofstream(root/"results.json")<<result.dump(2)<<'\n';std::cout<<result.dump(2)<<'\n';return failures?1:0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
