#include "FullBodyIK.h"
#include "ModelLoader.h"
#include "Ragdoll.h"
#include <algorithm>
#include <chrono>
#include <cstdio>
#include <limits>
#include <cstdlib>
#include <new>
#include <glm/gtc/matrix_transform.hpp>
namespace AllocationProof {thread_local bool enabled=false;thread_local size_t count=0;}
#if defined(_MSC_VER)
#define JUDAS_ALLOCATION_NOINLINE __declspec(noinline)
#elif defined(__GNUC__)
#define JUDAS_ALLOCATION_NOINLINE __attribute__((noinline))
#else
#define JUDAS_ALLOCATION_NOINLINE
#endif
JUDAS_ALLOCATION_NOINLINE void* operator new(size_t size){if(AllocationProof::enabled)++AllocationProof::count;if(void* p=std::malloc(size?size:1))return p;throw std::bad_alloc();}
JUDAS_ALLOCATION_NOINLINE void* operator new[](size_t size){return ::operator new(size);}
JUDAS_ALLOCATION_NOINLINE void operator delete(void* p)noexcept{std::free(p);}
JUDAS_ALLOCATION_NOINLINE void operator delete[](void* p)noexcept{std::free(p);}
JUDAS_ALLOCATION_NOINLINE void operator delete(void* p,size_t)noexcept{std::free(p);}
JUDAS_ALLOCATION_NOINLINE void operator delete[](void* p,size_t)noexcept{std::free(p);}
namespace {
int checks=0,failures=0;
void Check(bool value,const char* text){++checks;failures+=!value;std::printf("%s %s\n",value?"PASS":"FAIL",text);}
float Angle(glm::quat a,glm::quat b){return 2*std::acos(glm::clamp(std::abs(glm::dot(glm::normalize(a),glm::normalize(b))),0.f,1.f));}
struct Fixture {Skeleton skeleton;FullBodyIKSettings settings;std::vector<int> ends;};
Fixture Make(float size,bool rename){
 Fixture f;auto& s=f.skeleton;auto node=[&](std::string name,int parent,glm::vec3 translation){int n=int(s.names.size());s.names.push_back((rename?"alias_":"fixture_")+name);s.parents.push_back(parent);s.order.push_back(n);JointTransform t;t.translation=translation*size;s.rest.local.push_back(t);return n;};
 int root=node("hub",-1,{0,1.4f,0});int first=node("branch",root,{0,.25f,0});int second=node("crown",first,{0,.25f,0});
 f.settings.bodyRoot=s.names[root];f.settings.rootRotation=false;f.settings.rootMin=glm::vec3(-.3f*size);f.settings.rootMax=glm::vec3(.3f*size);f.settings.spine={s.names[first],s.names[second]};f.settings.positionTolerance=.003f*size;f.settings.iterations=96;
 for(int side=0;side<2;++side){float sign=side?1.f:-1.f;int a=node("branchA"+std::to_string(side),second,{sign*.2f,0,0});int b=node("branchB"+std::to_string(side),a,{sign*.5f,0,0});int c=node("terminalA"+std::to_string(side),b,{sign*.45f,0,0});f.ends.push_back(c);f.settings.chains.push_back({"top"+std::to_string(side),{s.names[a],s.names[b],s.names[c]}});FullBodyIKJointLimit l;l.joint=s.names[b];l.min=glm::vec3(-2.8f);l.max=glm::vec3(2.8f);l.preferred={0,0,sign*.2f};l.preferenceWeight=.4f;f.settings.limits.push_back(l);}
 for(int side=0;side<2;++side){float sign=side?1.f:-1.f;int a=node("branchC"+std::to_string(side),root,{sign*.17f,0,0});int b=node("branchD"+std::to_string(side),a,{0,-.7f,0});int c=node("terminalB"+std::to_string(side),b,{0,-.7f,0});f.ends.push_back(c);f.settings.chains.push_back({"bottom"+std::to_string(side),{s.names[a],s.names[b],s.names[c]}});FullBodyIKJointLimit l;l.joint=s.names[b];l.min={-2.8f,-.2f,-.2f};l.max={.2f,.2f,.2f};l.preferred={-.12f,0,0};l.preferenceWeight=.5f;f.settings.limits.push_back(l);}
 // Helper nodes and a singular uninvolved head-hiding layer are retained.
 int hidden=node("concealed",second,{0,.3f,0});s.rest.local[hidden].scale=glm::vec3(0);for(int i=0;i<50;++i)node("helper"+std::to_string(i),hidden,{.01f,0,0});for(size_t i=0;i<s.names.size();++i){s.skinNodes.push_back(int(i));s.inverseBind.push_back(glm::mat4(1));}
 return f;
}
std::vector<FullBodyIKTarget> KnownTargets(const Fixture& f,float size){auto known=f.skeleton.rest;known.local[0].translation+=size*glm::vec3(.16f,-.085f,.1f);known.local[1].rotation=glm::angleAxis(.16f,glm::normalize(glm::vec3(.2f,1,.1f)));known.local[2].rotation=glm::angleAxis(-.1f,glm::normalize(glm::vec3(1,.4f,.2f)));for(int end:f.ends){known.local[end].rotation=glm::angleAxis(.18f,glm::normalize(glm::vec3(1,2,3)));}
 // The expected pose is explicitly authored independently of the solver. FK
 // resolves the contact frames, as it does for imported source animation.
 auto globals=ResolveJointMatrices(f.skeleton,known);std::vector<FullBodyIKTarget> targets;for(size_t i=0;i<f.ends.size();++i){FullBodyIKTarget t;t.id="contact"+std::to_string(i);t.chain=f.settings.chains[i].id;t.offset=size*glm::vec3(0,-.03f,.06f);t.frame=glm::angleAxis(.2f,glm::normalize(glm::vec3(1,.2f,0)));t.orientationWeight=1;JointTransform value;std::string error;DecomposeRigidPose(globals[f.ends[i]],value,error);t.position=glm::dvec3(globals[f.ends[i]]*glm::vec4(t.offset,1));t.orientation=value.rotation*t.frame;targets.push_back(t);}return targets;}
bool ConservesLengths(const Skeleton&,const SkeletalPose& a,const SkeletalPose& b){for(size_t i=0;i<a.local.size();++i)if(a.local[i].translation!=b.local[i].translation&&i!=0)return false;return true;}
void Print(const char* label,const FullBodyIKResult& r){std::printf("IK_RESULT %s iterations=%u cost_us=%.3f root=%.6f,%.6f,%.6f\n",label,r.iterations,r.solveMicroseconds,r.rootCorrection.x,r.rootCorrection.y,r.rootCorrection.z);for(const auto& t:r.targets)std::printf("IK_CONTACT %s id=%s status=%s position_m=%.8f orientation_deg=%.8f\n",label,t.id.c_str(),t.status.c_str(),t.positionError,glm::degrees(t.orientationError));}
}
int main(){std::string error;auto fixture=Make(1,false);const auto& s=fixture.skeleton;FullBodyIKMapping map;Check(PrepareFullBodyIK(s,fixture.settings,map,error),"full helper-preserving mapping validates without inverting hidden subtree");auto targets=KnownTargets(fixture,1);FullBodyIKResult result;bool solved=SolveFullBodyIK(s,s.rest,map,targets,result,error);Check(solved,"four contacts solve in one bounded system");if(!solved){std::printf("DIAGNOSTIC %s\n",error.c_str());return 1;}Print("human-scale",result);bool all=true;for(const auto& t:result.targets)all&=t.positionError<=.01f&&t.orientationError<=glm::radians(2.f);Check(all&&result.converged,"each independently specified contact within 1 cm and 2 degrees");Check(glm::length(result.rootCorrection)>.025f&&Angle(result.pose.local[1].rotation,s.rest.local[1].rotation)>.025f,"shared root and spine participate");Check(ConservesLengths(s,s.rest,result.pose),"all non-root translations and bone lengths remain unchanged");Check(result.pose.local[15].scale==s.rest.local[15].scale,"unmapped hidden/helper branch remains unchanged");
 auto noParticipation=fixture.settings;noParticipation.rootMin=noParticipation.rootMax=glm::vec3(0);noParticipation.spine.clear();FullBodyIKMapping negative;FullBodyIKResult failed;Check(PrepareFullBodyIK(s,noParticipation,negative,error)&&SolveFullBodyIK(s,s.rest,negative,targets,failed,error)&&!failed.converged,"negative control cannot replace required root/spine participation with stretch");Print("participation-disabled",failed);
 auto copy=result;Check(SolveFullBodyIK(s,s.rest,map,targets,result,error)&&result.pose.local[0].translation==copy.pose.local[0].translation,"repeated reference sampling has no cumulative correction drift");auto order=targets;std::reverse(order.begin(),order.end());FullBodyIKResult ordered;Check(SolveFullBodyIK(s,s.rest,map,order,ordered,error)&&ordered.pose.local[0].translation==result.pose.local[0].translation,"target identity defines deterministic order independent of update order");
 auto other=Make(1.65f,true);FullBodyIKMapping otherMap;FullBodyIKResult otherResult;Check(PrepareFullBodyIK(other.skeleton,other.settings,otherMap,error)&&SolveFullBodyIK(other.skeleton,other.skeleton.rest,otherMap,KnownTargets(other,1.65f),otherResult,error),"renamed/proportioned skeleton uses explicit mapping");all=true;for(const auto& t:otherResult.targets)all&=t.positionError<=.0165f&&t.orientationError<=glm::radians(2.f);Check(all,"renamed 1.65 scale fixture meets scaled contact tolerance");Print("renamed-proportioned",otherResult);
 auto positionOnly=targets;for(auto& t:positionOnly)t.orientationWeight=0;FullBodyIKResult positionResult;Check(SolveFullBodyIK(s,s.rest,map,positionOnly,positionResult,error)&&positionResult.converged,"position-only targets");auto orientationOnly=targets;for(auto& t:orientationOnly){t.positionWeight=0;t.position={500,500,500};}FullBodyIKResult orientationResult;Check(SolveFullBodyIK(s,s.rest,map,orientationOnly,orientationResult,error)&&orientationResult.converged&&glm::length(orientationResult.rootCorrection)<1e-6f,"orientation-only targets do not drag root toward unused position");
 auto unreachable=targets;unreachable[0].position={30,30,30};FullBodyIKResult bounded;Check(SolveFullBodyIK(s,s.rest,map,unreachable,bounded,error)&&!bounded.converged&&bounded.iterations<=fixture.settings.iterations&&glm::all(glm::lessThanEqual(bounded.rootCorrection,fixture.settings.rootMax))&&glm::all(glm::greaterThanEqual(bounded.rootCorrection,fixture.settings.rootMin)),"unreachable target returns finite bounded compromise and residual");
 auto conflicting=targets;auto duplicate=conflicting[0];duplicate.id="contradiction";duplicate.position+=glm::dvec3(1,0,0);conflicting.push_back(duplicate);Check(SolveFullBodyIK(s,s.rest,map,conflicting,bounded,error)&&!bounded.converged&&bounded.targets.size()==5,"competing same-effector constraints give explicit residuals");
 auto disabled=targets;for(auto& t:disabled){t.positionWeight=t.orientationWeight=0;t.enabled=false;}Check(SolveFullBodyIK(s,s.rest,map,disabled,bounded,error)&&bounded.pose.local[0].translation==s.rest.local[0].translation&&bounded.iterations==0,"disabled/zero influences preserve reference exactly");Check(SolveFullBodyIK(s,s.rest,map,{},bounded,error)&&bounded.targets.empty()&&bounded.pose.local[0].translation==s.rest.local[0].translation,"target removal restores reference without stale state");
 auto invalid=targets;invalid[1].orientation={0,0,0,0};Check(!SolveFullBodyIK(s,s.rest,map,invalid,bounded,error)&&error.find("target[1]")!=std::string::npos,"invalid quaternion diagnosed by target index without publication");invalid=targets;invalid[0].chain="absent";Check(!SolveFullBodyIK(s,s.rest,map,invalid,bounded,error),"missing chain rejected safely");auto replaced=s;replaced.names[1]="replacement";Check(!SolveFullBodyIK(replaced,s.rest,map,targets,bounded,error),"skeleton replacement invalidates prepared identities");
 glm::dvec3 origin(1e11,-2e11,3e11);auto rotation=glm::angleAxis(.91f,glm::normalize(glm::vec3(1,2,-3)));auto worldTargets=targets;for(auto& t:worldTargets){t.position=origin+glm::dvec3(rotation*glm::vec3(t.position));t.orientation=rotation*t.orientation;t.space=IKTargetSpace::World;}std::vector<FullBodyIKTarget> modelTargets;Check(FullBodyIKTargetsToModel(worldTargets,origin,rotation,{1,1,1},modelTargets,error)&&SolveFullBodyIK(s,s.rest,map,modelTargets,bounded,error)&&bounded.converged,"arbitrarily rotated large-coordinate world converts relative offsets before float solving");
 auto translated=targets;for(auto& t:translated){t.position+=glm::dvec3(.025,0,.02);t.orientation=glm::angleAxis(.025f,glm::vec3(0,0,1))*t.orientation;}Check(SolveFullBodyIK(s,s.rest,map,translated,bounded,error)&&bounded.converged,"translated/rotated contact support solved with same primitive");
 auto constrained=fixture.settings;FullBodyIKJointLimit limit;limit.joint=s.names[1];limit.frame=glm::angleAxis(.3f,glm::normalize(glm::vec3(1,1,0)));limit.min=glm::vec3(-.04f);limit.max=glm::vec3(.04f);constrained.limits.push_back(limit);FullBodyIKMapping constrainedMap;Check(PrepareFullBodyIK(s,constrained,constrainedMap,error)&&SolveFullBodyIK(s,s.rest,constrainedMap,targets,bounded,error),"authored joint frame range participates");auto delta=glm::inverse(limit.frame)*glm::inverse(s.rest.local[1].rotation)*bounded.pose.local[1].rotation*limit.frame;float maxAngle=2*std::acos(glm::clamp(std::abs(delta.w),0.f,1.f));Check(maxAngle<=glm::length(limit.max)+1e-4f,"declared joint range is not exceeded");
 std::string text=SerializeFullBodyIKSettings(fixture.settings);FullBodyIKSettings round;Check(ParseFullBodyIKSettings(text,round,error)&&SerializeFullBodyIKSettings(round)==text,"mapping numerical policy and frames round trip exactly");round.targets=targets;text=SerializeFullBodyIKSettings(round);Check(ParseFullBodyIKSettings(text,round,error)&&round.targets.size()==4&&SerializeFullBodyIKSettings(round)==text,"target positions/frames/weights round trip");Check(!ParseFullBodyIKSettings("{\"bodyRoot\":\"x\",\"chains\":[],\"iterations\":9999}",round,error),"unbounded iteration request rejected");
 MeshData multipart;bool loaded=LoadModelMesh("projects/import_lab/Assets/models/multipart.judasmodel",multipart,error);Check(loaded&&multipart.skeletal&&multipart.primitives.size()>1,"current full imported multipart resource loads unreduced");if(loaded&&multipart.skeletal){auto& imported=multipart.skeletal->skeleton;FullBodyIKSettings importedSettings;importedSettings.rootRotation=false;int root=-1,end=-1;for(int node:imported.order)if(imported.parents[node]>=0&&imported.parents[imported.parents[node]]>=0){end=node;root=imported.parents[imported.parents[node]];break;}if(root>=0){importedSettings.bodyRoot=SkeletonJointKey(imported,root);importedSettings.chains={{"mapped",{SkeletonJointKey(imported,root),SkeletonJointKey(imported,imported.parents[end]),SkeletonJointKey(imported,end)}}};FullBodyIKMapping importedMap;auto globals=ResolveJointMatrices(imported,imported.rest);FullBodyIKTarget t;t.id="imported";t.chain="mapped";t.position=glm::dvec3(globals[end][3]);Check(PrepareFullBodyIK(imported,importedSettings,importedMap,error)&&SolveFullBodyIK(imported,imported.rest,importedMap,{t},bounded,error)&&bounded.pose.local.size()==imported.names.size(),"full imported hierarchy/helpers and multipart bindings remain intact in shared solve");}}
 for(int variant=0;variant<2;++variant){MeshData rig;auto path=variant?"projects/character_lab/Assets/models/alternate.judasmodel":"projects/character_lab/Assets/models/figure.judasmodel";bool ready=LoadModelMesh(path,rig,error);Check(ready&&rig.skeletal&&rig.primitives.size()==6&&rig.skeletal->skeleton.names.size()>=65,"actual CC0 full multipart rig imports with all source joints and bindings");if(!ready||!rig.skeletal)continue;const auto& skeleton=rig.skeletal->skeleton;
  std::vector<std::string> keys=variant?std::vector<std::string>{"Q01","Q02","Q03","Q07","Q08","Q09","Q30","Q31","Q32","Q25","Q26","Q27","Q48","Q49","Q50"}:std::vector<std::string>{"Pivot","Vertebra0","Vertebra1","ShoulderA","ElbowA","PalmA","ShoulderB","ElbowB","PalmB","ThighA","ShinA","SoleA","ThighB","ShinB","SoleB"};
  FullBodyIKSettings settings;settings.bodyRoot=keys[0];settings.rootRotation=false;settings.spine={keys[1],keys[2]};settings.rootMin=glm::vec3(-.3f);settings.rootMax=glm::vec3(.3f);settings.iterations=96;for(int contact=0;contact<4;++contact)settings.chains.push_back({"fullContact"+std::to_string(contact),{keys[3+3*contact],keys[4+3*contact],keys[5+3*contact]}});
  auto reference=skeleton.rest;for(const auto& clip:rig.skeletal->clips)if(clip.name=="HeadHidden")reference=SampleClip(skeleton,clip,.5f);
  auto authored=reference;int body=FindSkeletonJoint(skeleton,keys[0]);authored.local[body].translation+=glm::vec3(.12f,-.035f,.09f);authored.local[FindSkeletonJoint(skeleton,keys[1])].rotation=glm::angleAxis(.12f,glm::normalize(glm::vec3(.3f,1,0)));authored.local[FindSkeletonJoint(skeleton,keys[2])].rotation=glm::angleAxis(-.08f,glm::normalize(glm::vec3(1,.2f,0)));
  auto actual=ResolveJointMatrices(skeleton,authored);std::vector<FullBodyIKTarget> fullTargets;for(int contact=0;contact<4;++contact){int end=FindSkeletonJoint(skeleton,keys[5+3*contact]);FullBodyIKTarget t;t.id="fullFrame"+std::to_string(contact);t.chain=settings.chains[contact].id;t.offset=contact<2?glm::vec3(0,0,.07f):glm::vec3(0,-.04f,.12f);t.frame=glm::angleAxis(.1f,glm::normalize(glm::vec3(.2f,1,.3f)));JointTransform frame;DecomposeRigidPose(actual[end],frame,error);t.position=glm::dvec3(actual[end]*glm::vec4(t.offset,1));t.orientation=frame.rotation*t.frame;t.orientationWeight=1;fullTargets.push_back(t);}
  FullBodyIKMapping prepared;FullBodyIKResult fullResult;bool completed=PrepareFullBodyIK(skeleton,settings,prepared,error)&&SolveFullBodyIK(skeleton,reference,prepared,fullTargets,fullResult,error);Check(completed,"full imported four-contact solve retains singular head-hiding and helper nodes");if(completed){Print(variant?"full-import-renamed":"full-import",fullResult);bool reached=true;for(const auto& t:fullResult.targets)reached&=t.positionError<=.01f&&t.orientationError<=glm::radians(2.f);Check(reached,"each actual full imported contact within 1 cm and 2 degrees");Check(fullResult.pose.local.size()==reference.local.size()&&ResolveSkinMatrices(skeleton,fullResult.pose).size()==130,"both complete skin palettes preserve final pose identity");}else std::printf("FULL_IMPORT_DIAGNOSTIC %s\n",error.c_str());
 }
 // The same immutable asset can have unrelated target/result state.
 FullBodyIKResult independent;Check(SolveFullBodyIK(s,s.rest,map,targets,independent,error)&&SolveFullBodyIK(s,s.rest,map,{},bounded,error)&&independent.rootCorrection!=bounded.rootCorrection,"two instances sharing a skeleton keep independent target/solve state");
 std::vector<double> costs;size_t lastAllocations=0;for(int i=0;i<40;++i){FullBodyIKResult measured;AllocationProof::count=0;AllocationProof::enabled=true;SolveFullBodyIK(s,s.rest,map,targets,measured,error);AllocationProof::enabled=false;lastAllocations=AllocationProof::count;if(i>=10)costs.push_back(measured.solveMicroseconds);}std::sort(costs.begin(),costs.end());std::printf("IK_PERFORMANCE nodes=%zu contacts=4 median_us=%.3f p95_us=%.3f max_us=%.3f iterations=%u allocations_per_solve=%zu\n",s.names.size(),costs[costs.size()/2],costs[size_t((costs.size()-1)*.95)],costs.back(),result.iterations,lastAllocations);
 std::printf("SUMMARY %d checks %d failures\n",checks,failures);return failures?1:0;
}
