#include "AnimationRetarget.h"
#include "ModelCook.h"
#include "ModelLoader.h"
#include "PoseComposition.h"
#include "../third_party/nlohmann/json.hpp"
#include <glm/gtc/matrix_transform.hpp>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <set>
#include <algorithm>
namespace fs=std::filesystem;using Json=nlohmann::json;
namespace {
unsigned checks=0,failures=0;void Check(bool ok,const char* text){++checks;failures+=!ok;std::cout<<(ok?"PASS ":"FAIL ")<<text<<'\n';}
Json Read(const fs::path& p){std::ifstream file(p);return Json::parse(file);}
const AnimationClip& Clip(const MeshData& mesh,const char* name){auto& clips=mesh.skeletal->clips;auto i=std::find_if(clips.begin(),clips.end(),[&](const auto& clip){return clip.name==name;});if(i==clips.end())throw std::runtime_error(std::string("fixture missing clip: ")+name);return *i;}
glm::quat Rotation(const glm::mat4& matrix){glm::mat3 basis;for(int i=0;i<3;++i)basis[i]=glm::normalize(glm::vec3(matrix[i]));return glm::normalize(glm::quat_cast(basis));}
double Angle(glm::quat a,glm::quat b){a=glm::normalize(a);b=glm::normalize(b);auto d=glm::normalize(glm::inverse(a)*b);return 2*std::atan2(double(glm::length(glm::vec3(d.x,d.y,d.z))),double(std::abs(d.w)));}
SkeletalPose Reference(const Skeleton& skeleton,const std::vector<RetargetReferenceCorrection>& corrections){auto pose=skeleton.rest;for(const auto& correction:corrections){int joint=FindSkeletonJoint(skeleton,correction.joint);if(joint<0)throw std::runtime_error("fixture reference key absent");pose.local[joint].rotation=glm::normalize(pose.local[joint].rotation*correction.rotation);}return pose;}
bool SameGeometry(const MeshData& a,const MeshData& b){if(a.vertices.size()!=b.vertices.size()||a.skinVertices.size()!=b.skinVertices.size()||a.indices!=b.indices||a.materialKeys!=b.materialKeys||a.primitives.size()!=b.primitives.size())return false;for(size_t i=0;i<a.vertices.size();++i){auto& x=a.vertices[i];auto& y=b.vertices[i];if(x.position!=y.position||x.normal!=y.normal||x.uv!=y.uv||x.uv1!=y.uv1||x.tangent!=y.tangent)return false;}for(size_t i=0;i<a.skinVertices.size();++i){auto& x=a.skinVertices[i];auto& y=b.skinVertices[i];if(x.joints!=y.joints||x.joints1!=y.joints1||x.weights!=y.weights||x.weights1!=y.weights1)return false;}for(size_t i=0;i<a.primitives.size();++i){auto& x=a.primitives[i];auto& y=b.primitives[i];if(x.first!=y.first||x.count!=y.count||x.material!=y.material||x.part!=y.part||x.node!=y.node)return false;}return true;}
}
int main(int argc,char** argv){try{
 fs::path root=argc>1?argv[1]:"projects/retarget_lab";fs::path results=argc>2?argv[2]:".cache/m74/lab-checks.json";auto roles=Read(root/"Authoring"/"roles.json");std::string error;
 ModelImportSettings sourceSettings;ModelImportReport sourceReport;MeshData source;Check(ImportMotionSource((root/"Sources"/"source.gltf").string(),sourceSettings,source,sourceReport,error),"original multi-part source enters normal M66 glTF boundary");if(!source.skeletal)throw std::runtime_error(error);
 const auto& sourceRig=source.skeletal->skeleton;Check(sourceRig.names.size()>64&&source.skeletal->clips.size()==3,"source retains full helpers and three reusable performances");Json observations=Json::array();double angularError=0,positionError=0,restOffsetError=0,rootError=0,previewError=0;
 // Tolerances are fixed in advance: 2e-5 radians, 20 micrometres for direct
 // analytic knots, 0.001 radians / 0.2 mm for off-grid baked interpolation.
 for(const char* rigName:{"broad","tall"}){
  auto recipe=root/"Imports"/(std::string(rigName)+".judasimport");auto recipeJson=Read(recipe);MeshData raw,cooked;ModelImportSettings targetSettings;std::string projectRoot;Check(LoadModelRecipeTarget(recipe.string(),raw,targetSettings,projectRoot,error),"target input uses shared recipe normalization and authored identities");if(!raw.skeletal)throw std::runtime_error(error);
  Check(LoadModelMesh((root/recipeJson.at("output").get<std::string>()).string(),cooked,error),"ordinary runtime asset loads target with native and borrowed clips");if(!cooked.skeletal)throw std::runtime_error(error);
  auto profilePath=root/recipeJson.at("motions").at(0).at("retargetProfile").get<std::string>();RetargetProfile profile;Check(LoadRetargetProfile(profilePath.string(),profile,error)&&ValidateRetargetProfile(sourceRig,raw.skeletal->skeleton,profile,error),"one saved correspondence validates for all source performances");if(profile.mapping.empty())throw std::runtime_error(error);
  RetargetBakeSettings timing;timing.name="Wave";timing.sampleRate=60;RetargetBakeReport timingReport;AnimationClip timedBake;Check(BakeRetargetClip(sourceRig,Clip(source,"Wave"),raw.skeletal->skeleton,profile,timing,timedBake,error,&timingReport)&&timingReport.mappedJoints==profile.mapping.size()&&timingReport.samples>=121,"representative authoring bake measures mapped joints, 121 samples and bounded working buffers");
  auto& targetRig=raw.skeletal->skeleton;auto reference=Reference(targetRig,profile.targetReference);auto referenceGlobal=ResolveJointMatrices(targetRig,reference);auto sourceReference=Reference(sourceRig,profile.sourceReference);SkeletalPose referenceResult;Check(RetargetPose(sourceRig,targetRig,profile,sourceReference,referenceResult,error),"declared source reference transfers transactionally");
  double refPosition=0,refAngle=0;auto referenceResultGlobal=ResolveJointMatrices(targetRig,referenceResult);for(size_t i=0;i<referenceGlobal.size();++i){refPosition=std::max(refPosition,double(glm::length(glm::vec3(referenceGlobal[i][3]-referenceResultGlobal[i][3]))));refAngle=std::max(refAngle,Angle(Rotation(referenceGlobal[i]),Rotation(referenceResultGlobal[i])));}Check(refPosition<2e-5&&refAngle<2e-5,"declared reference maps to target reference within 20 micrometres / 20 microradians");
  Check(SameGeometry(raw,cooked),"target mesh positions/normals/UVs/weights/indices/material and part identities stay exact");bool bindSame=targetRig.skinNodes==cooked.skeletal->skeleton.skinNodes&&targetRig.inverseBind==cooked.skeletal->skeleton.inverseBind;Check(bindSame,"all original target skin palette and inverse binds remain exact");
  bool restSame=true;for(size_t i=0;i<targetRig.names.size();++i){auto& a=targetRig.rest.local[i];auto& b=cooked.skeletal->skeleton.rest.local[i];restSame&=targetRig.names[i]==cooked.skeletal->skeleton.names[i]&&a.translation==b.translation&&a.rotation==b.rotation&&a.scale==b.scale;}Check(restSame,"target rest skeleton and stable names retained without bind-pose calibration rewrite");
  auto& nativeRaw=Clip(raw,"Native");auto& nativeCook=Clip(cooked,"Native");auto nativeA=SampleClip(targetRig,nativeRaw,.63f),nativeB=SampleClip(cooked.skeletal->skeleton,nativeCook,.63f);bool nativeSame=nativeRaw.duration==nativeCook.duration&&nativeRaw.tracks.size()==nativeCook.tracks.size();for(size_t i=0;i<targetRig.names.size();++i)nativeSame&=nativeA.local[i].translation==nativeB.local[i].translation&&nativeA.local[i].rotation==nativeB.local[i].rotation&&nativeA.local[i].scale==nativeB.local[i].scale;Check(nativeSame,"target's own native performance remains an ordinary unchanged clip");
  int shoulder=FindSkeletonJoint(targetRig,roles[rigName]["ShoulderA"]),elbow=FindSkeletonJoint(targetRig,roles[rigName]["ElbowA"]),opposite=FindSkeletonJoint(targetRig,roles[rigName]["ShoulderB"]),pivot=FindSkeletonJoint(targetRig,roles[rigName]["Pivot"]);if(shoulder<0||elbow<0||opposite<0||pivot<0)throw std::runtime_error("lab role missing");
  for(float time:{.5f,1.f}){
   SkeletalPose transferred;Check(RetargetPose(sourceRig,targetRig,profile,SampleClip(sourceRig,Clip(source,"Wave"),time),transferred,error),"asymmetric source reach transfers across target axes and retained helpers");auto actual=ResolveJointMatrices(targetRig,transferred);
   // Independently authored fixture values: unmapped OriginHelper Y rotation,
   // left shoulder Z rotation, then left elbow Y. The right arm has only the
   // helper rotation; a swapped mapping or ignored helper cannot satisfy this.
   float helper=time==.5f?.12f:.22f,left=time==.5f?-.4f:-.7f,bend=time==.5f?.4f:-.5f;auto helperQ=glm::angleAxis(helper,glm::vec3(0,1,0)),leftQ=glm::angleAxis(left,glm::vec3(0,0,1)),bendQ=glm::angleAxis(bend,glm::vec3(0,1,0));glm::quat deltas[]={helperQ*leftQ,helperQ*leftQ*bendQ,helperQ};int joints[]={shoulder,elbow,opposite};double maxAngle=0;
   for(int i=0;i<3;++i){auto expected=profile.modelAlignment*deltas[i]*glm::inverse(profile.modelAlignment)*Rotation(referenceGlobal[joints[i]]);maxAngle=std::max(maxAngle,Angle(Rotation(actual[joints[i]]),expected));}angularError=std::max(angularError,maxAngle);Check(maxAngle<2e-5,"known source/helper/left-arm rotations match independent target-frame quaternion expectations");
   double offsets=0;for(size_t i=0;i<transferred.local.size();++i)offsets=std::max(offsets,double(glm::length(transferred.local[i].translation-reference.local[i].translation)));restOffsetError=std::max(restOffsetError,offsets);Check(offsets<2e-5,"rotation-only asymmetric motion preserves target proportions and all local rest offsets");
  }
  auto bobPose=SampleClip(cooked.skeletal->skeleton,Clip(cooked,"Bob"),1.f);auto bobGlobal=ResolveJointMatrices(cooked.skeletal->skeleton,bobPose);auto expectedBob=profile.modelAlignment*glm::vec3(0,.22f,0)*profile.translationScale;double bobError=glm::length(glm::vec3(bobGlobal[pivot][3]-referenceGlobal[pivot][3])-expectedBob);positionError=std::max(positionError,bobError);Check(bobError<2e-5,"selected pelvis bob survives in aligned model frame with explicit translation scale");
  auto travelPose=SampleClip(cooked.skeletal->skeleton,Clip(cooked,"TravelPreserve"),2.f);auto travelGlobal=ResolveJointMatrices(cooked.skeletal->skeleton,travelPose);auto expectedTravel=profile.modelAlignment*glm::vec3(1.6f,0,-1.3f)*profile.translationScale;double travelError=glm::length(glm::vec3(travelGlobal[pivot][3]-referenceGlobal[pivot][3])-expectedTravel);positionError=std::max(positionError,travelError);Check(travelError<2e-5,"preserved locomotion retains analytically expected scaled X/Z displacement");
  auto expectedTurn=profile.modelAlignment*glm::angleAxis(.8f,glm::vec3(0,1,0))*glm::inverse(profile.modelAlignment)*Rotation(referenceGlobal[pivot]);double turnError=Angle(Rotation(travelGlobal[pivot]),expectedTurn);angularError=std::max(angularError,turnError);Check(turnError<2e-5,"root turning retains independent 0.8-radian source rotation in the declared alignment frame");
  auto& extracted=Clip(cooked,"TravelExtract");auto& inPlace=Clip(cooked,"TravelInPlace");auto& preserve=Clip(cooked,"TravelPreserve");double reconstruction=0,inPlaceDifference=0;
  for(float time:{0.f,.371f,1.f,2.f}){auto original=ResolveJointMatrices(cooked.skeletal->skeleton,SampleClip(cooked.skeletal->skeleton,preserve,time));auto stripped=ResolveJointMatrices(cooked.skeletal->skeleton,SampleClip(cooked.skeletal->skeleton,extracted,time));auto stationary=ResolveJointMatrices(cooked.skeletal->skeleton,SampleClip(cooked.skeletal->skeleton,inPlace,time));auto motion=SampleRootMotion(extracted,time,false);auto transform=glm::translate(glm::mat4(1),motion.translation)*glm::mat4_cast(motion.rotation);for(size_t i=0;i<original.size();++i)for(int c=0;c<4;++c)for(int r=0;r<4;++r){reconstruction=std::max(reconstruction,double(std::abs((transform*stripped[i])[c][r]-original[i][c][r])));inPlaceDifference=std::max(inPlaceDifference,double(std::abs(stationary[i][c][r]-stripped[i][c][r])));}}
  rootError=std::max(rootError,reconstruction);Check(reconstruction<.0002&&inPlaceDifference<2e-5,"ordinary extracted track reconstructs locomotion once and in-place retains the identical complementary pose");Check(inPlace.motion.empty()&&!extracted.motion.empty(),"in-place discards only declared motion track while extraction stays queryable");
  double offgridAngle=0,offgridPosition=0;for(float time:{.137f,.613f,1.127f,1.773f}){SkeletalPose direct;RetargetPose(sourceRig,targetRig,profile,SampleClip(sourceRig,Clip(source,"Wave"),time),direct,error);auto expected=ResolveJointMatrices(targetRig,direct);auto baked=ResolveJointMatrices(cooked.skeletal->skeleton,SampleClip(cooked.skeletal->skeleton,Clip(cooked,"Wave"),time));for(size_t i=0;i<targetRig.names.size();++i){offgridAngle=std::max(offgridAngle,Angle(Rotation(expected[i]),Rotation(baked[i])));offgridPosition=std::max(offgridPosition,double(glm::length(glm::vec3(expected[i][3]-baked[i][3]))));}}
  previewError=std::max(previewError,offgridPosition);Check(offgridAngle<.001&&offgridPosition<.0002,"off-grid direct preview versus baked local tracks stays within 1 mrad / 0.2 mm");
  observations.push_back({{"rig",rigName},{"sourceJoints",sourceRig.names.size()},{"targetJoints",targetRig.names.size()},{"mappedJoints",profile.mapping.size()},{"translationScale",profile.translationScale},{"referencePositionMetres",refPosition},{"referenceAngleRadians",refAngle},{"pelvisPositionMetres",bobError},{"travelPositionMetres",travelError},{"rootReconstructionMatrixError",reconstruction},{"offgridAngleRadians",offgridAngle},{"offgridPositionMetres",offgridPosition},{"authoringBake",{{"samples",timingReport.samples},{"outputKeys",timingReport.outputKeys},{"milliseconds",timingReport.milliseconds},{"estimatedWorkingBytes",timingReport.estimatedWorkingBytes},{"bufferEstimateOnly",true}}},{"cookedOutputBytes",fs::file_size(root/recipeJson.at("output").get<std::string>())}});
 }
 Json result={{"checks",checks},{"failures",failures},{"angularErrorRadians",angularError},{"positionErrorMetres",positionError},{"restOffsetErrorMetres",restOffsetError},{"rootReconstructionMatrixError",rootError},{"previewBakePositionErrorMetres",previewError},{"conditions",observations}};fs::create_directories(results.parent_path());std::ofstream(results)<<result.dump(2)<<'\n';std::cout<<result.dump(2)<<'\n';return failures?1:0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
