#include "Application.h"
#include "TestInput.h"
#include "EngineHost.h"
#include "InteractivePlay.h"
#include "RuntimeWorld.h"
#include "SceneSession.h"
#include "SaveService.h"
#include "WorldPersistence.h"
#include "SceneSerialization.h"
#include "ScreenshotWriter.h"
#include <SDL2/SDL.h>
#include <filesystem>
#include <thread>
#include <cstdio>
#include <algorithm>
namespace {int checks=0,failures=0;void Check(bool value,const char* text){++checks;failures+=!value;std::printf("%s %s\n",value?"PASS":"FAIL",text);std::fflush(stdout);}void Quit(){SDL_Event e{};e.type=SDL_QUIT;SDL_PushEvent(&e);}}
int main(int argc,char** argv){if(argc<4){std::fprintf(stderr,"usage: %s <project.judasproj> <write|read> <output-dir>\n",argv[0]);return 2;}std::string project=argv[1],mode=argv[2],out=argv[3];std::filesystem::create_directories(out);bool reading=mode=="read";unsigned frame=0,phase=0,requestFrame=0,restoredFrame=0;uint64_t rejectedRequest=0;bool frozen=false;RuntimeWorld* initial=nullptr;GameSnapshot expected;std::string error;ApplicationControl control;control.hidden=true;
 control.hostReady=[](EngineHost& host){std::string e;host.GetWindow().SetTestInputMode(true);SDL_GL_SetSwapInterval(0);host.Audio().Init(e,true);};
 control.frameSeconds=[&](float){return frozen?0.f:1.f/60;};
 control.worldReady=[&](EngineHost&,RuntimeWorld& world,InteractivePlay&){initial=&world;};
 control.beforeFrame=[&](EngineHost& host,RuntimeWorld& world,InteractivePlay&){if(requestFrame){if(frame==requestFrame)QueueTestKey(host.GetWindow(),reading?SDL_SCANCODE_F8:SDL_SCANCODE_F5,true);if(frame==requestFrame+1)QueueTestKey(host.GetWindow(),reading?SDL_SCANCODE_F8:SDL_SCANCODE_F5,false);if(!reading&&frame==requestFrame+4)QueueTestKey(host.GetWindow(),SDL_SCANCODE_F5,true);if(!reading&&frame==requestFrame+5)QueueTestKey(host.GetWindow(),SDL_SCANCODE_F5,false);}
  if(reading&&&world!=initial&&!restoredFrame){restoredFrame=frame;SaveArchive liquid;world.Liquids().Persist(liquid);Check(liquid.bytes==expected.participants.at("liquid").data,"fresh process exact owner/cell/flow/parcel partition before resume");Check(world.RagdollActive(6100),"active articulation reconstructed, no bind-pose reset");Scene saved;WorldPersistence::SceneFrom(expected.participants,saved,error);bool poses=true;for(auto& o:saved.Objects())if(o.body){auto b=world.RuntimeBody(o.id);auto pose=world.Physics().GetTransform(b);poses&=b.IsValid()&&glm::length(pose.position-o.transform.position)<1e-5f;}Check(poses,"fresh process physical world poses match captured boundary");auto* a=world.RuntimeAnimation(6101);Check(a&&a->mixer.Transitioning()&&std::abs(a->mixer.elapsed-.4f)<1e-5f,"in-progress crossfade continues from captured contributor state");Check(world.SceneControl()->Get("labTicks")!="null","bounded game/session state restored before callbacks");Check(world.Physics().AliveBodyCount()==std::size_t(std::count_if(saved.Objects().begin(),saved.Objects().end(),[](const auto& o){return bool(o.body);})+std::count_if(saved.Objects().begin(),saved.Objects().end(),[](const auto& o){return bool(o.characterMotor);})),"mapped rigid bodies and massless motor proxies instantiated exactly once");frozen=true;}
 };
 control.afterFrame=[&](EngineHost& host,RuntimeWorld& world,InteractivePlay&){++frame;auto* service=world.SceneControl()->Saves(host.Resources());
  if(world.Scripts()&&!world.Scripts()->Diagnostics().empty()){for(auto& d:world.Scripts()->Diagnostics())std::printf("FAULT %s %s\n",d.callback.c_str(),d.message.c_str());Check(false,"ordinary project scripts remain healthy");Quit();return;}
  if(frame==30){auto doc=world.UI().Find("lab");world.UI().Document(doc)->modal=true;world.UI().Element(doc,"pause")->visible=true;}
  if(frame==31){std::vector<unsigned char> pixels;host.GetRenderer().CaptureFrame(host.GetWindow().Width(),host.GetWindow().Height(),pixels);WriteRgbPng((std::filesystem::path(out)/"save-menu.png").string(),host.GetWindow().Width(),host.GetWindow().Height(),pixels);auto doc=world.UI().Find("lab");world.UI().Document(doc)->modal=false;world.UI().Element(doc,"pause")->visible=false;}
  if(phase==0&&frame>30){if(!WorldPersistence::Prepare(world,error)){if(error!="loading"){std::printf("PREPARE %s\n",error.c_str());Check(false,"required resources prepared");Quit();}return;}
   if(reading){SaveStorage store(service->Root());bool recovered=false;if(!store.Read("slot-a",expected,recovered,error)){Check(false,error.c_str());Quit();return;}Check(!recovered,"fresh process reads committed selected slot");auto cancellation=service->Request("list","","","{}",error);Check(cancellation&&service->Cancel(cancellation)&&service->Status(cancellation)->state=="cancelled","queued operation cancels before commit boundary");auto invalid=expected;invalid.participants["motors"].version=99;Check(store.Write("invalid-participant",invalid,error),"detached incompatible fixture committed only in isolated test namespace");rejectedRequest=service->Request("load","invalid-participant","","{}",error);Check(rejectedRequest&&!service->Request("save","race","","{}",error)&&!world.SceneControl()->Request(world.SceneControl()->Current(),error),"conflicting save/scene requests return busy");frozen=true;phase=6;}
   else{auto& liquid=world.Liquids();auto main=liquid.Handle(20),cup=liquid.Handle(200);Check(main.id&&cup.id,"normal conserved pool and physical cup registered");Check(liquid.Transfer(main,cup,.003)>.0029,"actual paired transfer puts 3 litres in cup");auto t=world.RuntimeDefinition(200)->transform;t.position={-5,4,-1};t.rotation=glm::angleAxis(.35f,glm::vec3(0,0,1));Check(world.SetRuntimeTransform(200,t),"tilted physical cup current world pose");auto* water=liquid.Get(main);auto local=water->dynamicSurface->data->cells.front().centre;auto point=water->pose.position+water->pose.rotation*glm::vec3(local);Check(liquid.SurfaceImpulse(main,point,{.1f,0,0}),"disturb real dynamic surface");for(int i=0;i<8;++i)world.UpdateLiquids(1./30);Check(liquid.Emit(main,.004,{-3,6,-3},{.3f,0,0})>.0039,"detached in-flight quantity uses actual owner ledger");auto* animation=world.RuntimeAnimation(6101);animation->mixer.CrossFade(animation->playback,"Stretch",2);world.ResolveAnimationPose(*animation,.4f);Check(world.EnterRagdoll(6100,error),"physical articulation enters from current resolved pose");world.Physics().ApplyLinearImpulse(world.RuntimeBody(world.RagdollBody(6100,"Tip")),{1,0,0});Check(world.SeekAudio(6200,4),"ordinary persistent music seek");host.Audio().SetGroup("music",{.3f,false,true});host.Audio().SetGroup("master",{.19f,false,false});frozen=true;phase=1;}
  }else if(phase==6){auto* status=service->Status(rejectedRequest);if(status&&status->state=="failed"){Check(&world==initial&&world.Scripts()->Diagnostics().empty(),"unsupported participant leaves original live world playable");requestFrame=frame+1;phase=2;}}else if(phase==1){AudioVoiceSnapshot voice;for(auto& e:world.AudioEmitters())if(e.id==6200)host.Audio().Snapshot(e.voice,voice);host.Audio().AdvanceWithoutDevice(128);if(voice.ready&&!voice.seeking&&voice.positionSeconds>=3.99){requestFrame=frame+1;phase=2;}}
  else if(phase==2){auto records=world.Scripts()->Capture();for(auto& r:records)if(r.entity==11){if(r.json.find("completed")!=std::string::npos){} }bool committed=false;for(uint64_t id=1;id<64;++id)if(auto* status=service->Status(id))if(status->operation=="save"){if(status->state=="completed")committed=true;if(status->state=="failed"){Check(false,status->error.c_str());Quit();return;}}if(committed&&!service->Busy()&&frame>requestFrame+5&&!reading){SaveStorage store(service->Root());GameSnapshot captured;bool recovered=false;if(store.Read("slot-a",captured,recovered,error)){Check(!recovered&&captured.displayName.find("Water")!=std::string::npos,"public JudasJS save completed durable Unicode metadata");Check(captured.participants.size()==12&&captured.participants.count("sleep")==1,"all required participants plus optional M65 sleep/session/streaming captured");Check(std::abs(world.Liquids().Accounting("water").error)<=world.Liquids().Accounting("water").tolerance,"saving leaves conserved quantity unchanged");Check(world.RagdollActive(6100),"saving does not deactivate articulation");Check(world.Scripts()->Diagnostics().empty(),"public slot request from project UI lifecycle healthy");std::printf("SNAPSHOT bytes=%zu participants=%zu bodies=%zu owners=%zu parcels=%zu root=%s\n",EncodeGameSnapshot(captured).size(),captured.participants.size(),world.Physics().AliveBodyCount(),world.Liquids().States().size(),world.Liquids().Parcels().size(),service->Root().c_str());for(uint64_t id=1;id<64;++id)if(auto* status=service->Status(id))std::printf("REQUEST %llu %s capture_ms=%.5f worker_ms=%.5f restore_ms=%.5f bytes=%zu error=%s\n",(unsigned long long)id,status->state.c_str(),status->captureMs,status->workerMs,status->restoreMs,status->bytes,status->error.c_str());Quit();phase=3;}}
   if(reading&&restoredFrame&&frame>restoredFrame+1){Check(world.Scripts()&&world.Scripts()->Capture().size()==2,"restore-aware scripts instantiated once with saved state");AudioGroupSettings master;host.Audio().GetGroup("master",master);Check(std::abs(master.gain-1)<1e-6,"load retains current machine master volume, not saved preference");AudioVoiceSnapshot voice;for(auto& e:world.AudioEmitters())if(e.id==6200)host.Audio().Snapshot(e.voice,voice);host.Audio().AdvanceWithoutDevice(128);Check(voice.positionSeconds>=3.99&&voice.positionSeconds<4.01,"persistent music resumes selected cursor, not zero");frozen=false;phase=4;}
  }else if(phase==4&&frame>=restoredFrame+12){auto ledger=world.Liquids().Accounting("water");Check(std::abs(ledger.error)<=ledger.tolerance,"first resumed steps retain exact M54 ledger");Check(world.Liquids().Errors().empty(),"first resumed disturbed water updates remain healthy");Check(world.RagdollActive(6100)&&std::isfinite(world.Physics().GetTransform(world.RuntimeBody(world.RagdollBody(6100,"Tip"))).position.x),"first resumed physical articulation finite");Check(world.RuntimeAnimation(6101)->mixer.elapsed>.4f,"resumed animation transition advances");Check(world.Scripts()->Diagnostics().empty(),"restore callback avoids new-game resets and script faults");Quit();phase=3;}
  if(frame%100==0)for(uint64_t id=1;id<64;++id)if(auto* status=service->Status(id))std::printf("STATUS %llu %s %s\n",(unsigned long long)id,status->state.c_str(),status->error.c_str());
  std::this_thread::sleep_for(std::chrono::milliseconds(1));if(frame>900){Check(false,"bounded save/load application deadline");Quit();}
 };
 Application app;char name[]="judas";char* arguments[]={name,project.data()};int result=app.Run(2,arguments,&control);Check(result==0&&phase==3,"ordinary standalone process startup/save or restore/shutdown");std::printf("SUMMARY mode=%s checks=%d failures=%d frames=%u\n",mode.c_str(),checks,failures,frame);return failures?1:0;
}
