#include "RuntimeWorld.h"
#include "ResourceManager.h"
#include "ScriptSystem.h"
#include "CoarseSimulation.h"
#include "WorldStreaming.h"
#include "SceneSerialization.h"
#include "PerformanceProfiler.h"
#include "../third_party/nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <chrono>
#include <thread>
#include <iostream>
#include <algorithm>
using J=nlohmann::json;namespace fs=std::filesystem;using Clock=std::chrono::steady_clock;
namespace {unsigned checks=0;bool measureOnly=false;void check(bool v,const char* label){++checks;if(!v&&!measureOnly)throw std::runtime_error(label);}double elapsed(Clock::time_point t){return std::chrono::duration<double,std::milli>(Clock::now()-t).count();}J summary(std::vector<double> v){std::sort(v.begin(),v.end());return {{"median",v[v.size()/2]},{"p95",v[size_t((v.size()-1)*.95)]},{"max",v.back()}};}}
int main(int argc,char** argv){if(argc<2||argc>3){std::cerr<<"usage: judas_scalability_tests NEW-owned-output [--measure-baseline]\n";return 2;}try{measureOnly=argc==3&&std::string(argv[2])=="--measure-baseline";if(argc==3&&!measureOnly)throw std::runtime_error("unknown option");auto out=fs::absolute(argv[1]);if(fs::exists(out))throw std::runtime_error("output exists; choose a fresh owned directory");fs::create_directories(out/"Assets");std::ofstream(out/"Assets/tick.js")<<R"JS(import {input} from 'judas';export const properties={ref:{type:'entity',default:null}};export default class {constructor({entity}){this.entity=entity;this.state={ticks:0};}fixedUpdate(){this.state.ticks++;const t=this.entity.transform;input.axis('move_x');}})JS";
 AssetDatabase db;db.Scan(out.string(),(out/"Assets").string());AssetRecord script;std::string error;check(db.Track((out/"Assets/tick.js").string(),script,error),"registered ordinary script");ResourceManager resources(nullptr,&db);auto& profiler=PerformanceProfiler::Get();profiler.Enable(true);profiler.RegisterThread("M68 runtime");J results;results["runtime"]=J::array();
 for(int n:{0,400,800,6400})for(int active:{0,1,8}){Scene scene;for(int i=0;i<active;++i)scene.CreateObject("script").scripts={{1,script.id,true,"{}"}};for(int i=0;i<n;++i)scene.CreateObject("inert");RuntimeWorld w;auto start=Clock::now();check(w.Build(scene,&resources,error),"world builds");double startup=elapsed(start);w.FixedScripts(nullptr,1.f/60);auto before=w.MetadataStats();std::vector<double> samples;
 for(int i=0;i<1000;++i){ProfileFrame pf("M68 fixed");start=Clock::now();ApplyCoarseCelestialForces(w,1.f/60);w.FixedScripts(nullptr,1.f/60);w.UpdateCharacters(1.f/60);w.Physics().Step(1.f/60);StepCoarseEntities(w,1.f/60);w.DispatchPhysicsEvents(nullptr,1.f/60);samples.push_back(elapsed(start));}
 auto after=w.MetadataStats();check(after.indexRebuilds==before.indexRebuilds,"ordinary motion does not invalidate entity identity index");check(after.definitionsCopied-before.definitionsCopied<=uint64_t(active*2000),"inert scenery never copied into fixed event bookkeeping");check(w.ScriptObjects().size()==size_t(n+active),"explicit whole-world query still enumerates inert objects");check(!w.Scripts()||w.Scripts()->Diagnostics().empty(),"actual script work executes without faults");results["runtime"].push_back({{"inert",n},{"activeScripts",active},{"steps",1000},{"startupMs",startup},{"fixedMs",summary(samples)},{"definitionCopies",after.definitionsCopied-before.definitionsCopied},{"indexRebuilds",after.indexRebuilds-before.indexRebuilds},{"scriptSlotsCopied",after.scriptSlotsCopied-before.scriptSlotsCopied},{"touchBodyResolutions",after.touchBodyResolutions-before.touchBodyResolutions},{"lookups",after.lookups-before.lookups}});
 if(active){auto records=w.Scripts()->Capture();check(records.size()==size_t(active)&&J::parse(records[0].json)["ticks"]==1001,"unchanged active callbacks execute exactly once per step");for(int i=0;i<80;++i){SceneObject spawn;spawn.scripts={{2,script.id,true,"{}"}};auto id=w.CreateEntity(spawn,nullptr,&error);check(id&&w.RuntimeDefinition(id),"churn publishes script membership");w.FixedScripts(nullptr,.016f);check(w.DestroyEntity(id),"churn removes entity safely");w.FixedScripts(nullptr,.016f);check(!w.RuntimeDefinition(id),"destroyed identity not reused by next slot");}check(w.Scripts()->Capture().size()==size_t(active),"churn leaves no phantom script instances");}
 w.Destroy();}
 results["streaming"]=J::array();Project project;check(Project::CreateNew((out/"stream-project").string(),"M68 streaming",project,error),"owned ordinary streaming project");Scene region;for(int i=0;i<100;++i)region.CreateObject("static");check(SaveSceneToFile(region,project.Resolve("Scenes/part.judas"),error),"region scene saved");AssetDatabase regionAssets;regionAssets.Scan(project.RootDir(),project.AssetsDir());JobSystem jobs(2);ResourceManager regionResources(nullptr,&regionAssets,&jobs);
 for(int total:{4,128})for(int resident:{1,4}){RuntimeWorld w;Scene empty;check(w.Build(empty,&regionResources,error),"stream root");WorldManifest manifest;for(int i=0;i<total;++i){WorldRegion r;r.id="r"+std::to_string(i);r.scene="Scenes/part.judas";manifest.regions[r.id]=r;}WorldStreaming stream(w,regionResources,project,manifest);std::vector<uint64_t> requests;for(int i=0;i<resident;++i)requests.push_back(stream.Request("r"+std::to_string(i),false,error));auto start=Clock::now();auto pump=[&](auto condition){for(int i=0;i<5000;++i){regionResources.Pump();stream.Advance(false);if(condition())return true;std::this_thread::sleep_for(std::chrono::milliseconds(1));}return false;};check(pump([&]{return stream.Stats().active==unsigned(resident);}),"required regions atomically become active");double ready=elapsed(start);auto before=w.MetadataStats();std::vector<double> samples;double largest=0;for(int i=0;i<1000;++i){ProfileFrame pf("M68 streaming residency");start=Clock::now();stream.Advance(false);samples.push_back(elapsed(start));largest=std::max(largest,stream.Stats().largestUnitMs);}auto after=w.MetadataStats();auto stats=stream.Stats();results["streaming"].push_back({{"authoredRegions",total},{"residentRegions",resident},{"liveObjects",w.ScriptObjects().size()},{"readyMs",ready},{"advanceMs",summary(samples)},{"definitionCopies",after.definitionsCopied-before.definitionsCopied},{"pendingBytes",stats.pendingBytes},{"residentBytes",stats.liveBytes},{"largestUnitMs",largest}});check(after.definitionsCopied==before.definitionsCopied,"steady region pins do not copy entire world");for(auto request:requests)stream.Release(request);check(pump([&]{return stream.Stats().active==0&&stream.Stats().pending==0;}),"unload makes progress without lost state");auto cancel=stream.Request("r0",false,error);stream.Advance(false);stream.Release(cancel);check(pump([&]{return stream.Stats().active==0&&stream.Stats().pending==0;}),"cancelled preparation retires only its own request");for(int lap=0;lap<3;++lap){auto q=stream.Request("r0",false,error);check(pump([&]{auto s=stream.Status(q);return s&&s->state=="active";}),"backtracking republishes coherent region");check(stream.Resolve("r0",1)!=0,"revisit identity resolved normally");stream.Release(q);check(pump([&]{return stream.Stats().active==0;}),"revisit retirement bounded");}}
 profiler.Export((out/"m56-profile.json").string(),error);results["checks"]=checks;results["baseline"]=measureOnly;std::ofstream(out/"results.json")<<results.dump(2)<<'\n';std::cout<<results.dump(2)<<'\n';return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<" after "<<checks<<" checks\n";return 1;}}
