#include "TerrainAuthoring.h"
#include "Scene.h"
#include "SceneSerialization.h"
#include "NavigationAsset.h"
#include "NavigationSystem.h"
#include "Prefab.h"
#include "ModelArchive.h"
#include "SceneFingerprint.h"
#include <filesystem>
#include <fstream>
#include <iostream>
namespace fs=std::filesystem;
int count=0;
void Check(bool ok,const char* what){++count;if(!ok)throw std::runtime_error(what);std::cout<<"PASS "<<what<<'\n';}
void Save(const fs::path& p,const TerrainSource& source){fs::create_directories(p.parent_path());std::ofstream f(p);f<<SerializeTerrain(source);}
int main(int argc,char** argv){try{auto root=fs::absolute(argc>1?argv[1]:".cache/m75/pipeline");fs::create_directories(root/"Assets");auto path=root/"Imports/patch.judasterrain";auto t=CreateTerrain(33,33,32,32);for(unsigned z=0;z<33;++z)for(unsigned x=0;x<33;++x)t.heights[z*33+x]=.04f*(float(x)-16);Save(path,t);AssetDatabase assets;assets.Scan(root.string(),(root/"Assets").string());std::string error;TerrainCookResult result;Check(CookTerrain(t,path.string(),root.string(),assets,result,error),error.c_str());assets.Scan(root.string(),(root/"Assets").string());Check(assets.Find(t.meshId)&&assets.Find(t.collisionId)&&assets.Find(t.textureId)&&assets.Problems().empty(),"normal three-product asset registration");
 Scene scene;auto& terrain=scene.CreateObject("ordinary terrain");terrain.render.emplace();terrain.render->shape=SceneShape::Mesh;terrain.render->meshAsset=t.meshId;terrain.render->textureAsset=t.textureId;terrain.body.emplace();terrain.body->shape=SceneShape::TriangleMesh;terrain.body->collisionAsset=t.collisionId;auto terrainId=terrain.id;auto& nav=scene.CreateObject("advisory navigation");nav.navigationSurface.emplace();nav.navigationSurface->halfExtents={16,5,16};auto navId=nav.id;ProjectNavigation configuration;NavigationGeometry before;Check(CollectNavigationGeometry(scene,*scene.Find(navId),configuration,before,error,&assets),error.c_str());NavigationData baked;Check(BakeNavigation(scene,*scene.Find(navId),configuration,baked,error,&assets)&&!baked.layers.empty(),"normal Recast bake on edited terrain triangles");
 auto paint=t;paint.textureSize=256;Save(path,paint);Check(CookTerrain(paint,path.string(),root.string(),assets,result,error)&&!result.geometryChanged,"appearance settings leave geometry unchanged");assets.Scan(root.string(),(root/"Assets").string());NavigationGeometry after;Check(CollectNavigationGeometry(scene,*scene.Find(navId),configuration,after,error,&assets)&&after.fingerprint==before.fingerprint,"paint appearance does not invalidate navigation");auto sculpt=paint;sculpt.heights[16*33+16]+=1;Save(path,sculpt);Check(CookTerrain(sculpt,path.string(),root.string(),assets,result,error)&&result.geometryChanged,"sculpt accepted geometry publication");assets.Scan(root.string(),(root/"Assets").string());Check(CollectNavigationGeometry(scene,*scene.Find(navId),configuration,after,error,&assets)&&after.fingerprint!=baked.fingerprint,"old navigation bake becomes stale after sculpt");Check(BakeNavigation(scene,*scene.Find(navId),configuration,baked,error,&assets)&&baked.fingerprint==after.fingerprint,"offline rebake refreshes normal navigation");
 NavigationSystem queries(configuration);Check(queries.LoadSurface(navId,scene.Find(navId)->transform,std::make_shared<NavigationData>(baked),error),"ordinary Detour surface publication");auto route=queries.FindPath({-10,0,0},{10,0,0});Check(route.status==NavigationPath::Status::Complete&&route.corners.size()>=2,"usable navigation path across newly sculpted terrain");
 auto rotated=scene;rotated.Find(terrainId)->transform.rotation=rotated.Find(navId)->transform.rotation=glm::angleAxis(.7f,glm::normalize(glm::vec3(1,2,3)));rotated.Find(terrainId)->transform.position=rotated.Find(navId)->transform.position={23,-9,41};NavigationGeometry r;Check(CollectNavigationGeometry(rotated,*rotated.Find(navId),configuration,r,error,&assets)&&r.vertices.size()==after.vertices.size(),"navigation extracts same source in arbitrary local frame");float maxDifference=0;for(size_t i=0;i<r.vertices.size();++i)maxDifference=std::max(maxDifference,std::abs(r.vertices[i]-after.vertices[i]));Check(maxDifference<1e-5,"rotated navigation geometry equivalent within float precision");
 std::string text;SaveSceneToString(scene,text);Scene reloaded;Check(LoadSceneFromString(text,reloaded,error)&&reloaded.Find(terrainId)->body->collisionAsset==t.collisionId,"scene roundtrip preserves ordinary terrain references");auto invalid=scene;invalid.Find(terrainId)->transform.scale={2,1,1};SaveSceneToString(invalid,text);Check(!LoadSceneFromString(text,reloaded,error),"unsupported scaled triangle-mesh terrain rejected by normal validator");
 std::cout<<count<<" pipeline checks passed\n";return 0;}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<'\n';return 1;}}
