#include "TerrainAuthoring.h"
#include "CollisionAsset.h"
#include "CollisionGeometry.h"
#include "PhysicsWorld.h"
#include "CharacterMotor.h"
#include "UniformGravity.h"
#include "ModelArchive.h"
#include "SceneFingerprint.h"
#include <iostream>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <limits>
#include <chrono>
namespace fs=std::filesystem;
int checks=0,failed=0;
void Check(bool v,const char* name){++checks;if(!v){++failed;std::cerr<<"FAIL "<<name<<'\n';}else std::cout<<"PASS "<<name<<'\n';}
void Write(const fs::path& p,const std::string& s){fs::create_directories(p.parent_path());std::ofstream f(p,std::ios::binary);f<<s;}
std::string Read(const fs::path& p){std::ifstream f(p,std::ios::binary);return {std::istreambuf_iterator<char>(f),{}};}
int main(int argc,char** argv){auto root=fs::absolute(argc>1?argv[1]:".cache/m75/unit");root/="case-"+MintAssetId();fs::create_directories(root);std::cout<<"FIXTURE "<<root.generic_string()<<'\n';std::string error;auto t=CreateTerrain(17,17,16,16);Check(ValidateTerrain(t,error),"bounded flat source");TerrainSource round;Check(ParseTerrain(SerializeTerrain(t),round,error)&&round.heights==t.heights&&round.identity==t.identity,"versioned exact source roundtrip");auto invalid=t;invalid.heights[0]=std::numeric_limits<float>::infinity();Check(!ValidateTerrain(invalid,error),"nonfinite height rejected");invalid=t;invalid.weights[0]={.2f,0,0,0};Check(!ValidateTerrain(invalid,error),"unnormalized paint rejected");invalid=t;invalid.version=999;Check(!ValidateTerrain(invalid,error),"unknown version rejected");bool bounds=false;try{CreateTerrain(257,257,10,10);}catch(...){bounds=true;}Check(bounds,"oversized allocation rejected before samples");auto fork=ForkTerrain(t);Check(fork.meshId!=t.meshId&&fork.collisionId!=t.collisionId&&fork.identity!=t.identity&&fork.heights==t.heights,"fork preserves data with new identities");
 TerrainDraft draft;draft.source=t;TerrainBrush b;b.radius=3;b.strength=.5f;Check(draft.Begin({0,0,0},b,error),"raise begin");draft.End();Check(draft.source.heights[8*17+8]==.5f&&draft.source.heights[0]==0,"analytic center delta and finite footprint");Check(draft.Undo()&&draft.source.heights==t.heights,"one stroke undo");Check(draft.Redo()&&draft.source.heights[8*17+8]==.5f,"stroke redo");auto saved=draft.source.heights;draft.Begin({0,.5f,0},b,error);draft.Continue({4,0,0},error);draft.Cancel();Check(draft.source.heights==saved,"escape restores entire gesture");
 TerrainDraft sparse,dense;sparse.source=dense.source=t;sparse.Begin({-5,0,0},b,error);dense.Begin({-5,0,0},b,error);sparse.Continue({5,0,0},error);for(int i=1;i<=100;++i)dense.Continue({-5+.1f*i,0,0},error);sparse.End();dense.End();float difference=0;for(size_t i=0;i<t.heights.size();++i)difference=std::max(difference,std::abs(sparse.source.heights[i]-dense.source.heights[i]));Check(difference<2e-5,"sparse/dense collinear pointer schedules equivalent");
 b.kind=TerrainBrushKind::Smooth;draft.source=t;for(auto& h:draft.source.heights)h=2;draft.Begin({0,2,0},b,error);draft.End();Check(std::all_of(draft.source.heights.begin(),draft.source.heights.end(),[](float h){return h==2;}),"smoothing constant plane unchanged");b.kind=TerrainBrushKind::Flatten;draft.source=t;draft.Begin({0,3,0},b,error);draft.Continue({1,99,0},error);draft.End();Check(draft.source.heights[8*17+8]<3&&draft.source.heights[8*17+8]>0,"flatten level frozen at gesture press");
 auto mesh=BuildTerrainMesh(draft.source);glm::vec3 hit;Check(PickTerrain(mesh,{.17f,20,.31f},{0,-1,0},hit)&&hit.y>0,"pick edited triangles off grid");Check(!PickTerrain(mesh,{30,20,0},{0,-1,0},hit),"finite edge miss has no flat fallback");TerrainDraft miss;miss.source=t;Check(!miss.Begin({30,0,0},b,error)&&miss.source.heights==t.heights&&!miss.Active(),"out-of-patch brush rejects without mutation");Check(mesh.vertices.size()==289&&mesh.indices.size()==1536,"mesh triangle dimensions");bool normals=true;for(auto& v:mesh.vertices)normals&=std::isfinite(v.normal.x)&&std::abs(glm::length(v.normal)-1)<1e-5&&v.normal.y>0;Check(normals,"derived finite normalized normals face local height axis");CollisionAsset collision;Check(CookCollision(mesh,{},collision,error)&&collision.faces.size()==512,"normal collision cooker accepts exact terrain triangles");Check(collision.vertices.size()==mesh.vertices.size(),"collision vertex population matches mesh");
 auto path=root/"Imports/terrain.judasterrain";TerrainDraft disk;disk.source=t;disk.SetPath(path.string());if(fs::exists(path))fs::remove(path);Check(disk.Save(error)&&!disk.Dirty(),"save source atomically");TerrainDraft reopen;Check(reopen.Open(path.string(),error)&&reopen.source.meshId==t.meshId,"fresh source reopening stable identity");Write(path,Read(path)+" ");Check(reopen.ExternalChanged()&&!reopen.Save(error),"external source conflict refuses overwrite");Write(path,SerializeTerrain(t));AssetDatabase assets;fs::create_directories(root/"Assets");assets.Scan(root.string(),(root/"Assets").string());TerrainCookResult first;Check(CookTerrain(t,path.string(),root.string(),assets,first,error)&&first.geometryChanged&&first.appearanceChanged,"guarded ordinary product publication");auto model=root/t.productDirectory/"terrain.judasmodel",collider=root/t.productDirectory/"terrain.judascollision";auto original=Read(model),originalCollision=Read(collider);Check(VerifyImportedModelFresh(root.string(),model.string(),error),"terrain export provenance fresh");TerrainCookResult second;Check(CookTerrain(t,path.string(),root.string(),assets,second,error)&&!second.geometryChanged&&!second.appearanceChanged,"unchanged cook does not rebuild products");auto changed=t;changed.heights[144]=2;Write(path,SerializeTerrain(changed));Check(!VerifyImportedModelFresh(root.string(),model.string(),error),"uncooked edited source rejects export");TerrainCookResult cancelled;Check(!CookTerrain(changed,path.string(),root.string(),assets,cancelled,error,[]{return true;})&&Read(model)==original&&Read(collider)==originalCollision,"cancelled cook retains exact last-good geometry/collider");Check(CookTerrain(changed,path.string(),root.string(),assets,second,error)&&second.geometryChanged,"sculpt publishes new geometry/collider");
 auto bad=changed;bad.layers.push_back({"missing",MintAssetId(),4});Write(path,SerializeTerrain(bad));original=Read(model);Check(!CookTerrain(bad,path.string(),root.string(),assets,second,error)&&Read(model)==original,"missing layer failure preserves last good products");

 // Independent analytic ramp expectations at off-grid locations. These values
 // do not call the terrain picker or derive an answer from cooked triangles.
 auto ramp=CreateTerrain(17,17,16,16);for(unsigned z=0;z<17;++z)for(unsigned x=0;x<17;++x)ramp.heights[z*17+x]=.12f*(float(x)-8)+.08f*(float(z)-8)+1;
 CollisionAsset rampAsset;Check(CookCollision(BuildTerrainMesh(ramp),{},rampAsset,error),"analytic ramp collision cook");
 auto shared=std::make_shared<CollisionAsset>(rampAsset);auto shape=Shape::Cooked(shared,"terrain-analytic");
 for(auto rotation:{glm::quat(1,0,0,0),glm::angleAxis(.9f,glm::normalize(glm::vec3(1,2,3)))}){
  PhysicsWorld p;p.Init();glm::vec3 offset{13,-7,19},point{.37f,.12f*.37f+.08f*.23f+1,.23f},normal=glm::normalize(glm::vec3(-.12f,1,-.08f));
  auto body=p.CreateShape(shape,{offset,rotation},false,0,.6f,0);auto worldPoint=offset+rotation*point,worldNormal=rotation*normal;
  auto ray=p.Raycast(worldPoint+rotation*glm::vec3(0,5,0),rotation*glm::vec3(0,-1,0),10);
  Check(ray.hit&&ray.body.id==body.id&&glm::length(ray.point-worldPoint)<2e-4&&glm::length(ray.normal-worldNormal)<2e-4&&std::abs(ray.distance-5)<2e-4,"off-grid ray independent analytic point/normal/distance under rigid placement");
  auto sphere=p.SphereCast(worldPoint+worldNormal*5.f,.3f,-worldNormal,10);Check(sphere.hit&&std::abs(sphere.distance-4.7f)<.003&&glm::length(sphere.normal-worldNormal)<.003,"sphere cast uses edited physical surface");
  auto capsule=p.CapsuleCast({worldPoint+worldNormal*5.f,rotation},.3f,.6f,-worldNormal,10);float capsuleDistance=5-.3f-.6f*normal.y;Check(capsule.hit&&std::abs(capsule.distance-capsuleDistance)<.005,"capsule cast independent support extent");
  auto box=p.BoxCast({worldPoint+worldNormal*5.f,rotation},{.2f,.3f,.4f},-worldNormal,10);float extent=.2f*std::abs(normal.x)+.3f*normal.y+.4f*std::abs(normal.z);Check(box.hit&&std::abs(box.distance-(5-extent))<.005,"box cast matches analytic oriented extent");
  auto close=p.ClosestPoint(worldPoint+worldNormal*2.f,4);Check(close.hit&&std::abs(close.distance-2)<.005&&glm::length(close.point-worldPoint)<.005,"closest point uses true finite ramp");
  Check(!p.Raycast(offset+rotation*glm::vec3(20,20,20),rotation*glm::vec3(0,-1,0),40).hit,"physics finite patch has no hidden infinite floor");
  Check(!p.Raycast(worldPoint-worldNormal,worldNormal,.5f).hit,"one-sided patch rejects below-surface short cast");
  UniformGravity gravity(rotation*glm::vec3(0,-9.81f,0));CharacterMotor motor;motor.Reset(worldPoint+rotation*glm::vec3(0,.95f,0),rotation);for(int i=0;i<10;++i){p.Step(1.f/60);motor.Step(p,gravity,1.f/60);}Check(motor.result.supported&&motor.result.support.id==body.id&&glm::length(motor.result.supportNormal-worldNormal)<.01,"motor rests on edited ramp under independently rotated gravity");
  auto ball=p.CreateDynamicSphere(worldPoint+rotation*glm::vec3(-2,3,0),.25f,2,.8f,0);auto crate=p.CreateShape(Shape::Box({.3f,.3f,.3f}),{worldPoint+rotation*glm::vec3(2,3,0),rotation},true,4,.8f,0);
  for(int i=0;i<180;++i){p.ApplyLinearAcceleration(ball,gravity.Sample({}),1.f/60);p.ApplyLinearAcceleration(crate,gravity.Sample({}),1.f/60);p.Step(1.f/60);}auto localBall=glm::inverse(rotation)*(p.GetTransform(ball).position-offset),localBox=glm::inverse(rotation)*(p.GetTransform(crate).position-offset);auto ground=[](glm::vec3 v){return .12f*v.x+.08f*v.z+1;};Check(localBall.y-ground(localBall)>.20f&&localBall.y-ground(localBall)<.4f,"real dynamic sphere settles on ramp without helper floor");Check(localBox.y-ground(localBox)>.20f&&localBox.y-ground(localBox)<.5f,"real dynamic box contact rests on ramp");
  PhysicsWorld stale;stale.Init();CollisionAsset flatAsset;CookCollision(BuildTerrainMesh(t),{},flatAsset,error);stale.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(flatAsset),"stale"),{offset,rotation},false,0,.6f,0);auto wrong=stale.Raycast(worldPoint+rotation*glm::vec3(0,5,0),rotation*glm::vec3(0,-1,0),10);Check(wrong.hit&&glm::length(wrong.point-worldPoint)>.8f,"negative control detects intentionally stale flat collider");
 }

 // Independent 3x3 peak fixture exercises both diagonal halves, a crease,
 // and a finite edge. Expected heights/normals are analytic, not the generator.
 auto peak=CreateTerrain(3,3,4,4);peak.heights[4]=2;auto peakMesh=BuildTerrainMesh(peak);CollisionAsset peakAsset;Check(CookCollision(peakMesh,{},peakAsset,error),"asymmetric peak collision cook");PhysicsWorld peakWorld;peakWorld.Init();peakWorld.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(peakAsset),"peak"),{{0,0,0},glm::quat(1,0,0,0)},false,0,.5f,0);
 float worstPoint=0,worstNormal=0;for(auto sample:std::vector<glm::vec3>{{-.5f,1,-.5f},{.5f,1,.5f},{-1.99f,.01f,.01f},{-.99f,.02f,-.99f}}){auto hit=peakWorld.Raycast(sample+glm::vec3(0,3,0),{0,-1,0},6);auto expectedNormal=glm::normalize(sample.x>0?glm::vec3(1,1,1):sample.z>0?glm::vec3(-1,1,0):glm::vec3(-1,1,-1));float pe=glm::length(hit.point-sample),ne=glm::length(hit.normal-expectedNormal);worstPoint=std::max(worstPoint,pe);worstNormal=std::max(worstNormal,ne);Check(hit.hit&&pe<2e-4f&&ne<2e-4f,"off-grid peak/crease/edge physical point and face normal match independent expectation");glm::vec3 visible;Check(PickTerrain(peakMesh,sample+glm::vec3(0,3,0),{0,-1,0},visible)&&glm::length(visible-sample)<2e-4f,"visible emitted peak triangles match independent off-grid expectation");}
 std::cout<<"AGREEMENT worst_point_m "<<worstPoint<<" worst_normal_vector "<<worstNormal<<" tolerance 0.0002\n";

 // Real palette resources and paint-only publication keep geometry identity stable.
 auto image=[&](const fs::path& path,unsigned char r,unsigned char g,unsigned char b){std::string bytes(18,'\0');bytes[2]=2;bytes[12]=bytes[14]=2;bytes[16]=32;bytes[17]=8;for(int i=0;i<4;++i){bytes+=char(b);bytes+=char(g);bytes+=char(r);bytes+=char(-1);}Write(path,bytes);};
 auto texA=root/"Assets/a.tga",texB=root/"Assets/b.tga";image(texA,80,120,50);image(texB,170,80,30);assets.Scan(root.string(),(root/"Assets").string());AssetRecord a,basset;Check(assets.Track(texA.string(),a,error)&&assets.Track(texB.string(),basset,error),"register real terrain palette textures");
 auto painted=changed;painted.layers={{"grass",a.id,2},{"soil",basset.id,3}};Write(path,SerializeTerrain(painted));Check(CookTerrain(painted,path.string(),root.string(),assets,second,error),"publish registered two-layer terrain");auto meshBefore=Read(model),collisionBefore=Read(collider);TerrainDraft paint;paint.source=painted;TerrainBrush pb;pb.kind=TerrainBrushKind::Paint;pb.radius=3;pb.strength=.75;pb.layer=1;auto revision=paint.GeometryRevision();paint.Begin({0,2,0},pb,error);paint.End();Check(paint.GeometryRevision()==revision&&paint.source.heights==painted.heights,"paint never edits geometry revision or heights");bool weights=true;for(auto w:paint.source.weights)weights&=std::abs(w[0]+w[1]-1)<1e-6&&w[2]==0&&w[3]==0;Check(weights&&std::abs(paint.source.weights[144][1]-.75f)<1e-6,"analytic spatial paint blend normalized");TextureData blended;Check(PaintTerrainTexture(paint.source,assets,blended,error)&&blended.pixels[3]==255,"real texture blend produces opaque base color");Write(path,SerializeTerrain(paint.source));Check(CookTerrain(paint.source,path.string(),root.string(),assets,second,error)&&!second.geometryChanged&&second.appearanceChanged&&Read(model)==meshBefore&&Read(collider)==collisionBefore,"paint-only cook preserves exact mesh/collider bytes");Check(VerifyImportedModelFresh(root.string(),model.string(),error),"updated paint receipt validates export");

 // Lifetime/conflict and independent-source controls use real bytes, not mtimes.
 Check(reopen.Open(path.string(),error)&&reopen.source.weights==paint.source.weights,"saved source reopens exact paint values");b.kind=TerrainBrushKind::Raise;b.strength=.5f;reopen.Begin({0,0,0},b,error);reopen.End();Check(reopen.Save(error)&&reopen.Undo()&&reopen.Dirty(),"undo after Save is dirty and does not rewrite disk");Check(reopen.Redo()&&reopen.Save(error),"redo and source publication remain usable");auto sharedSource=reopen.source;auto independent=ForkTerrain(sharedSource);TerrainDraft independentDraft;independentDraft.source=independent;independentDraft.Begin({0,0,0},b,error);independentDraft.End();Check(sharedSource.heights!=independentDraft.source.heights&&sharedSource.heights==reopen.source.heights,"independent fork editing cannot change original source");
 auto good=Read(model);auto metaPath=texA.string()+".judasmeta",originalMeta=Read(metaPath);Write(path,SerializeTerrain(paint.source));bool changedMeta=false;Check(!CookTerrain(paint.source,path.string(),root.string(),assets,second,error,[&]{if(!changedMeta){changedMeta=true;Write(metaPath,originalMeta+"\n");}return false;})&&Read(model)==good,"changed layer registration during cook retains last good geometry");Write(metaPath,originalMeta);Check(CookTerrain(paint.source,path.string(),root.string(),assets,second,error),"restore dependency and recook succeeds");
 auto retained=Read(collider);auto receiptFile=root/paint.source.productDirectory/"terrain.receipt.json";auto receiptBefore=Read(receiptFile);bool replaced=false;Check(!CookTerrain(paint.source,path.string(),root.string(),assets,second,error,[&]{if(!replaced){replaced=true;Write(collider,retained+"changed");}return false;})&&Read(receiptFile)==receiptBefore&&Read(collider)==retained+"changed","concurrent retained collider change rejects cook and preserves external edit/old receipt");Write(collider,retained);
 auto invalidCounts=SerializeTerrain(t);auto nxAt=invalidCounts.find("\"nx\": 17");invalidCounts.replace(nxAt,8,"\"nx\": 17.5");Check(!ParseTerrain(invalidCounts,round,error),"fractional sample count rejected rather than truncated");invalidCounts=SerializeTerrain(t);nxAt=invalidCounts.find("\"nx\": 17");invalidCounts.replace(nxAt,8,"\"nx\": 4294967313");Check(!ParseTerrain(invalidCounts,round,error),"overflowing sample count rejected before unsigned narrowing/allocation");
 auto custom=CreateTerrain(17,17,16,16);custom.productDirectory="Content/Terrain/"+custom.identity;auto customPath=root/"Imports/custom.judasterrain";Write(customPath,SerializeTerrain(custom));fs::create_directories(root/"Content");AssetDatabase customAssets;customAssets.Scan(root.string(),(root/"Content").string());Check(CookTerrain(custom,customPath.string(),root.string(),customAssets,second,error),"cook respects ordinary project custom asset directory");customAssets.Scan(root.string(),(root/"Content").string());Check(customAssets.Find(custom.meshId)&&customAssets.Find(custom.textureId)&&customAssets.Find(custom.collisionId),"custom asset directory registers all normal products");auto customFork=ForkTerrain(custom);Check(fs::path(customFork.productDirectory).parent_path()==fs::path("Content/Terrain"),"fork preserves owning asset-directory convention");custom.productDirectory="Assets/not-discoverable";Write(customPath,SerializeTerrain(custom));Check(!CookTerrain(custom,customPath.string(),root.string(),customAssets,second,error),"cook rejects output outside normal configured asset discovery");
 Check(!ParseTerrain(std::string(32,'[')+"0"+std::string(32,']'),round,error),"excessive JSON nesting rejected before DOM allocation");Check(!ParseTerrain("{bad",round,error),"malformed source rejected without substitute flat surface");

 auto large=CreateTerrain(65,65,64,64);CollisionAsset largeAsset;Check(CookCollision(BuildTerrainMesh(large),{},largeAsset,error),"representative large mesh cook");PhysicsWorld motorGeometry;motorGeometry.Init();motorGeometry.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(largeAsset),"large"),{{0,0,0},glm::quat(1,0,0,0)},false,0,.5f,0);ResetCollisionGeometryStats();auto sweep=motorGeometry.SweepCapsuleMotion(.3f,.6f,{.17f,1,.31f},glm::quat(1,0,0,0),{0,-.3f,0});auto geometryWork=GetCollisionGeometryStats();Check(sweep.hit&&std::abs(sweep.distance-.1f)<2e-4,"motor sampled sweep retains analytic overlap boundary");Check(geometryWork.nodes>0&&geometryWork.triangles<2000,"motor sweep uses BVH bounded triangles rather than full mesh per sample");std::cout<<"MOTOR_BVH nodes "<<geometryWork.nodes<<" triangles "<<geometryWork.triangles<<" / mesh 8192\n";
 for(unsigned size:{65u,129u}){auto start=std::chrono::steady_clock::now();auto stress=CreateTerrain(size,size,float(size-1),float(size-1));TerrainDraft work;work.source=stress;b.kind=TerrainBrushKind::Raise;b.radius=5;work.Begin({-10,0,0},b,error);work.Continue({10,0,0},error);work.End();auto m=BuildTerrainMesh(work.source);auto ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();std::cout<<"PERF "<<size<<" grid stroke+normals "<<ms<<" ms / "<<m.vertices.size()<<" vertices\n";}
 std::cout<<checks<<" checks / "<<failed<<" failures\n";return failed?1:0;}
