#include "NamedAuthoring.h"
#include "WorldBuilder.h"
#include "AuthoringDocument.h"
#include "RecipePreview.h"
#include "SkeletonAuthoring.h"
#include "CollisionAsset.h"
#include "ModelLoader.h"
#include "AuthoringNumeric.h"
#include <chrono>
#include <clocale>
#include "SceneSerialization.h"
#include "SceneFingerprint.h"
#include "Project.h"
#include "RuntimeUI.h"
#include "Prefab.h"
#include "CameraProjection.h"
#include "CharacterMotor.h"
#include "UniformGravity.h"
#include "ContentReferences.h"
#include "WorldStreaming.h"
#include "ModelArchive.h"
#include "editor/EditorDocument.h"
#include "../third_party/nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <iostream>
namespace {int count=0,failures=0;void check(bool ok,const std::string& what){++count;if(!ok)++failures;std::cout<<(ok?"PASS ":"FAIL ")<<what<<'\n';}}
int main(int argc,char** argv){if(argc!=2){std::cerr<<"usage: "<<argv[0]<<" <output-dir>\n";return 2;}auto dir=std::filesystem::path(argv[1]);std::filesystem::create_directories(dir);std::string error,named,legacy;Scene s;auto& root=s.CreateObject("Parent 日本語");root.transform.position={3,0,0};auto rootId=root.id;auto& child=s.CreateObject("Child");child.parent=rootId;child.transform.position={2,0,0};auto childId=child.id;SaveSceneToString(s,legacy);
check(LegacyToNamed(legacy,"scene",named,error),"named scene conversion: "+error);Scene reloaded;check(LoadSceneFromString(named,reloaded,error),"normal loader reads named scene");std::string roundtrip;SaveSceneToString(reloaded,roundtrip);check(legacy==roundtrip,"legacy bytes unchanged through named roundtrip");auto json=nlohmann::json::parse(named);auto reordered=json.dump();Scene formatted;check(LoadSceneFromString(reordered,formatted,error)&&ScenesEqual(s,formatted),"property ordering and whitespace preserve authored meaning");std::string fingerprint,formattedFingerprint;ComputeSceneFingerprint(s,fingerprint,error);ComputeSceneFingerprint(formatted,formattedFingerprint,error);check(formattedFingerprint==fingerprint,"canonical fingerprint 5 unaffected by named formatting");
check(!NamedToLegacy("{\"kind\":\"scene\",\"kind\":\"scene\",\"schema\":1,\"data\":{}}","scene",roundtrip,error)&&error.find("duplicate")!=std::string::npos,"duplicate JSON keys reject");auto bad=json;bad["schema"]=2;check(!NamedToLegacy(bad.dump(),"scene",roundtrip,error),"unknown authoring version rejects");bad=json;bad["data"]["objects"][0]["fields"]["unknown.field"]=7;check(!NamedToLegacy(bad.dump(),"scene",roundtrip,error),"unknown component field rejects");check(ScenesEqual(reloaded,s),"failed decode preserves last-good scene");
bad=json;bad["data"]["objects"][1]["id"]=bad["data"]["objects"][0]["id"];check(!NamedToLegacy(bad.dump(),"scene",roundtrip,error),"duplicate stable entity ID rejects");
bad=json;bad["data"]["objects"][0]["id"]=-1;check(!NamedToLegacy(bad.dump(),"scene",roundtrip,error),"negative stable entity ID rejects");
ProjectSettings p;p.name="Unicode café";p.legacyGameplay=false;unsigned tagId=0;p.classification.tags.Add("pickup",tagId);p.input.entries[0].bindings[0].deadzone=.12f;p.exportScenes={"Scenes/main.judas"};auto projectLegacy=Project::SerializeToString(p);check(LegacyToNamed(projectLegacy,"project",named,error),"full project named fields");ProjectSettings q;check(Project::ParseFromString(named,q,error)&&Project::SerializeToString(q)==projectLegacy,"project input registries settings roundtrip");
UIDocument ui;UIElement canvas;canvas.id="canvas";canvas.kind=UIKind::Canvas;UIElement button;button.id="button";button.parent="canvas";button.kind=UIKind::Button;button.offset={30,50};button.size={100,40};button.text="مرحبا";button.direction=TextDirection::RTL;ui.elements={canvas,button};auto uiLegacy=SerializeUIDocument(ui);check(LegacyToNamed(uiLegacy,"ui",named,error),"named UI complete fields");UIDocument uiCopy;check(ParseUIDocument(named,uiCopy,error)&&SerializeUIDocument(uiCopy)==uiLegacy,"UI Unicode/layout/localization roundtrip");RuntimeUI runtime;auto h=runtime.Add(ui,"demo",0,error);runtime.Layout(1280,720);check(runtime.LayoutOf(h,"button")->rect.position==glm::vec2(30,50),"runtime layout origin");check(runtime.SetElementLayout(h,"button",{{"offset",{210,70}},{"size",{120,45}}},error),"batched UI layout mutation");runtime.Layout(1280,720);check(runtime.LayoutOf(h,"button")->rect.Contains({220,80})&&!runtime.LayoutOf(h,"button")->rect.Contains({40,60}),"layout and hit geometry move together");check(!runtime.SetElementLayout(h,"button",{{"size",{-1,2}}},error),"negative size rejects atomically");runtime.Unload(h);check(!runtime.SetElementLayout(h,"button",{{"offset",{0,0}}},error),"stale UI handles reject");
auto view=glm::mat4(1);auto projection=glm::perspective(glm::radians(70.f),16.f/9,.1f,2000.f);auto projected=ProjectViewport(view,projection,{0,0,-1000});check(projected.inside&&!projected.behind&&projected.position==glm::vec2(.5f),"extended camera range projects distant object");check(ProjectViewport(view,projection,{0,0,4}).behind,"behind-camera point identified");check(!ProjectViewport(view,projection,{0,0,-2100}).inside&&!ValidCameraRange(1,1),"clipping range validates and rejects far point");
std::string sceneText;SaveSceneToString(s,sceneText);check(WriteAuthoredDocument((dir/"scene.judas").string(),sceneText,"scene",error,true),"named source staged publication");EditorDocument doc;check(doc.Load((dir/"scene.judas").string(),error),"editor opens named source");doc.Select(rootId);doc.Select(childId,true);check(doc.BatchTransform({1,0,0},{1,0,0,0},{1,1,1},error,true,true),"parent and child batch world delta");Scene flat;FlattenHierarchy(doc.GetScene(),flat,error);check(flat.Find(childId)->transform.position==glm::vec3(6,0,0),"selected child inherits delta exactly once");doc.Undo();check(ScenesEqual(doc.GetScene(),s),"undo restores whole authored transaction");doc.BeginEdit();doc.GetScene().Find(rootId)->name="cancelled";doc.CancelEdit();check(doc.GetScene().Find(rootId)->name=="Parent 日本語","cancel restores snapshot");auto parents=doc.GetScene().Find(childId)->parent;check(doc.GroupSelection(error)&&doc.GetScene().Find(childId)->parent==parents,"organizational folder does not change transform parent");check(doc.Save(error),"editor saves same named source");std::ifstream file(dir/"scene.judas");std::string saved((std::istreambuf_iterator<char>(file)),{});check(IsNamedDocument(saved),"editor save keeps selected named format");{std::ofstream f(dir/"scene.judas");f<<"external invalid source";}check(doc.ExternalChanged()&&!doc.Save(error),"external divergence prevents silent overwrite");check(!doc.ApplySource("{broken",error)&&doc.GetScene().Find(rootId),"invalid source edit retains last-good document");

// Shared services, with independent expected outcomes for placement/topology.
Scene course;auto& templateObject=course.CreateObject("Template");templateObject.render=SceneRenderComponent{};templateObject.body=SceneBodyComponent{};auto templateId=templateObject.id;
WorldRecipe recipe;recipe.id="rails";recipe.templateId=templateId;recipe.count=4;recipe.spacing=3;RecipeProduct product;
check(EvaluateWorldRecipe(recipe,course,nullptr,product,error),"linear recipe: "+error);
if(product.recipe.elements.size()==4){auto a=product.recipe.elements[0].object,b=product.recipe.elements[1].object;check(product.scene.Find(b)->transform.position==glm::vec3(3,0,0),"linear spacing independent expectation");product.scene.Find(b)->render->color={1,0,0};auto revised=product.recipe;revised.spacing=4;revised.count=5;RecipeProduct next;check(EvaluateWorldRecipe(revised,product.scene,nullptr,next,error),"regeneration succeeds");check(next.recipe.elements[0].object==a&&next.recipe.elements[1].object==b,"surviving generated IDs retain identity");check(next.scene.Find(b)->render->color==glm::vec3(1,0,0)&&next.scene.Find(b)->transform.position==glm::vec3(4,0,0),"instance override survives regenerated spacing");revised=next.recipe;revised.count=3;RecipeProduct removed;check(EvaluateWorldRecipe(revised,next.scene,nullptr,removed,error)&&removed.removed.size()==2,"explicit removal list");}
WorldRecipe arc;arc.id="ramp";arc.type="arc";arc.segments=16;arc.radius=4;check(EvaluateWorldRecipe(arc,course,nullptr,product,error),"closed arc passes actual M64 cooker: "+error);
RecipeProduct repeated;check(EvaluateWorldRecipe(arc,course,nullptr,repeated,error)&&product.recipe.renderAsset==repeated.recipe.renderAsset&&product.recipe.proxyAsset==repeated.recipe.proxyAsset&&product.recipe.collisionAsset==repeated.recipe.collisionAsset,"same recipe inputs produce deterministic immutable revision asset identities");
if(!product.mesh.vertices.empty()){CollisionAsset collision;CollisionCookSettings settings;check(CookCollision(product.mesh,settings,collision,error)&&!collision.faces.empty(),"coherent ramp winding/caps accepted by actual cooker");PhysicsWorld geometry;geometry.Init();geometry.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(collision),"ramp"),{},false,0,.6f,0);auto hit=geometry.Raycast({0,3,-.5f},{0,-1,0},5);check(hit.hit&&hit.normal.y>.8f&&hit.point.y>.1f&&hit.point.y<.5f,"actual ramp triangle query reaches expected surface");CharacterMotor traverser;traverser.Reset({0,.95f,0},{1,0,0,0});UniformGravity gravity({0,-9.81f,0});int supported=0;
for(int step=0;step<90;++step){traverser.velocity={0,traverser.velocity.y,-1.5f};geometry.Step(1.f/60);traverser.Step(geometry,gravity,1.f/60);supported+=traverser.result.supported;}
check(traverser.position.z<-1.5f&&traverser.position.y>1.2f&&supported>60,"normal CharacterMotor traverses generated curved collision, not presentation-only geometry");
auto changed=product.recipe;changed.profile[0].x=-3;RecipeProduct invalid;check(!EvaluateWorldRecipe(changed,course,nullptr,invalid,error)||invalid.mesh.vertices.size()==product.mesh.vertices.size(),"edited convex profile validates with unchanged topology size");}
WorldRecipe path;path.id="path";path.type="path";path.templateId=templateId;path.path={{0,0,0},{0,0,-10}};path.spacing=2;path.count=6;check(EvaluateWorldRecipe(path,course,nullptr,product,error)&&product.recipe.elements.size()==6,"spacing-based path placement");if(product.recipe.elements.size()==6)check(glm::length(product.scene.Find(product.recipe.elements.back().object)->transform.position-glm::vec3(0,0,-10))<1e-5f,"path endpoint independent expectation");auto badRecipe=path;badRecipe.path={{0,0,0},{0,0,0}};check(!EvaluateWorldRecipe(badRecipe,course,nullptr,product,error),"zero tangent rejected; no publication");badRecipe=arc;badRecipe.profile={{0,0},{1,0},{.2f,.2f},{1,1},{0,1}};check(!EvaluateWorldRecipe(badRecipe,course,nullptr,product,error),"concave/invalid physical profile rejected");
JobSystem jobs(1);AssetDatabase database;auto preview=PreviewRecipe(jobs,path,course,database,42,"test-project");check(jobs.Wait(preview->job)==JobState::Completed&&preview->product.documentGeneration==42,"worker preview carries source/document revision");check(preview->parameters==SerializeWorldRecipe(path),"accepted preview parameters match exact request");auto cancelled=PreviewRecipe(jobs,path,course,database,43,"test-project");jobs.Cancel(cancelled->job);auto cancelledState=jobs.Wait(cancelled->job);check(cancelledState==JobState::Cancelled||cancelledState==JobState::Completed,"cooperative cancellation leaves no live document mutation");jobs.Shutdown();
std::string templateLegacy,templateNamed;SaveSceneToString(course,templateLegacy);WriteAuthoredDocument((dir/"source.judas").string(),templateLegacy,"scene",error,true);AuthoringDocument source;
check(source.Load("scene",(dir/"source.judas").string(),error),"shared source document");auto beforeSource=source.Source();check(!source.Replace("{bad",error)&&source.Source()==beforeSource,"invalid draft preserves validated source");auto sourceJSON=nlohmann::json::parse(beforeSource);sourceJSON["data"]["objects"][0]["name"]="Changed";check(source.Replace(sourceJSON.dump(),error)&&source.Dirty(),"validated source one undo action");check(source.Undo()&&source.Source()==beforeSource&&source.Redo(),"source undo/redo stable");check(source.Save(error),"shared source staged save");{std::ofstream f(dir/"source.judas");f<<"external";}check(source.ExternalChanged()&&!source.Save(error),"source external conflict retains dirty/last-good state");
const auto transactionPath=(dir/"transaction.txt").string();{std::ofstream f(transactionPath);f<<"old";}check(PublishAuthoringOutputs((dir/"recovery").string(),{{transactionPath,"new","old",true}},error),"recoverable publication succeeds");check(!PublishAuthoringOutputs((dir/"recovery").string(),{{transactionPath,"lost","old",true}},error),"publication rejects external mismatched baseline");
EditorDocument edits;edits.GetScene()=course;auto& extra=edits.GetScene().CreateObject("Second");auto secondId=extra.id;extra.transform.position={5,2,0};edits.Select(templateId);edits.Select(secondId,true);check(edits.AlignSelection(1,false,error),"alignment one transaction");check(edits.GetScene().Find(templateId)->transform.position.y==2,"align uses primary world coordinate");edits.Undo();check(edits.GetScene().Find(templateId)->transform.position.y==0,"alignment undo");check(edits.SnapSelection(.5f,15,.1f,error),"numeric snap validates");check(edits.RenameSelection("Batch",error)&&edits.GetScene().Find(secondId)->name=="Batch 2","batch rename document order");
Skeleton skeleton;skeleton.names={"Base","Armature/SegmentA","Armature/SegmentB"};skeleton.parents={-1,0,1};skeleton.order={0,1,2};skeleton.rest.local.resize(3);skeleton.rest.local[1].translation={0,2,0};skeleton.rest.local[2].translation={0,1,0};RagdollDefinition definition;RagdollBone existing;existing.joint="Base";existing.mass=8;existing.constraint.rotationalResistance=.17f;definition.bones={existing};RagdollDefinition fit;check(FitSkeletonChain(skeleton,definition,{"Base","Armature/SegmentA"},.2f,fit,error),"generic selected-chain fit: "+error);check(fit.bones.size()==2&&fit.bones[0].mass==8&&fit.bones[0].constraint.rotationalResistance==.17f,"fit preserves authored mass/resistance and unmapped joints");check(fit.bones.size()==2&&glm::length(fit.bones[0].offset-glm::vec3(0,1,0))<1e-5f&&fit.bones[1].parent=="Base","fit offsets and parent independent expectation");
// All ordinary registered scene families, covering current component writers.
size_t currentScenes=0;for(auto& entry:std::filesystem::recursive_directory_iterator("projects")){if(entry.path().extension()!=".judas"&&entry.path().extension()!=".judasprefab")continue;Scene scene;if(!LoadSceneFromFile(entry.path().string(),scene,error))continue;std::string a,b,c;SaveSceneToString(scene,a);Scene normal;auto kind=entry.path().extension()==".judasprefab"?"prefab":"scene";if(!LegacyToNamed(a,kind,b,error)||!LoadSceneFromString(b,normal,error)){check(false,"current field coverage "+entry.path().string()+": "+error);continue;}SaveSceneToString(normal,c);if(a!=c){std::ofstream(dir/"legacy-failure.txt")<<a;std::ofstream(dir/"named-failure.txt")<<b;std::ofstream(dir/"roundtrip-failure.txt")<<c;}check(a==c,"current writer roundtrip "+entry.path().string());++currentScenes;}check(currentScenes>30,"current-component coverage across ordinary projects, not historical evidence");
// Public document-family and rejection coverage beyond the selected demo.
auto inputLegacy=p.input.Serialize();check(LegacyToNamed(inputLegacy,"input",named,error),"standalone named input");InputMap im;check(InputMap::Parse(named,im,error)&&im.Serialize()==inputLegacy,"input ordering/deadzones complete roundtrip");
const std::string worldLegacy="JudasWorld 1\nbudget 2 16 2 33554432 67108864 4194304 67108864\nregion \"a\" \"Scenes/a.judas\" 1 2 3 0 0 0 1 5 6 7 2 \"snapshot\" 65536 \"\"\nregion \"b\" \"Scenes/b.judas\" 4 5 6 0 0 0 1 5 6 7 2 \"snapshot\" 65536 \"\"\nreference \"a\" 1 \"textureCamera\" \"b\" 2 soft\n";
check(LegacyToNamed(worldLegacy,"world",named,error),"world named budgets/qualified references");WorldManifest manifest;check(ParseWorldManifest(named,manifest,error)&&manifest.regions.at("a").origin==glm::dvec3(1,2,3)&&manifest.references[0].targetLocal==2&&!manifest.references[0].hard,"qualified region reference independent expected identity");
auto editorial=s;editorial.Find(rootId)->authoringFolder="Folder";editorial.Settings().authoringRecipes["r"]=SerializeWorldRecipe(path);std::string editorialFingerprint;check(ComputeSceneFingerprint(editorial,editorialFingerprint,error)&&editorialFingerprint==fingerprint,"editor folders/recipes do not change canonical gameplay fingerprint");
struct DecimalComma:std::numpunct<char>{char do_decimal_point()const override{return ',';}};auto previousLocale=std::locale();std::locale::global(std::locale(std::locale::classic(),new DecimalComma));std::string localeScene;SaveSceneToString(s,localeScene);check(localeScene==sceneText&&LegacyToNamed(localeScene,"scene",named,error),"numeric parsing/writing ignores process C++ decimal-comma locale");std::locale::global(previousLocale);
auto invalidJSON=nlohmann::json::parse(SerializeWorldRecipe(path));invalidJSON["data"]["frame"]["typo"]=1;WorldRecipe noRecipe;check(!ParseWorldRecipe(invalidJSON.dump(),noRecipe,error)&&error.find("frame")!=std::string::npos,"recipe nested unknown fields fail with context");invalidJSON=nlohmann::json::parse(SerializeWorldRecipe(path));invalidJSON["data"]["templateId"]=-1;check(!ParseWorldRecipe(invalidJSON.dump(),noRecipe,error),"negative stable recipe identity rejects before unsigned wrapping");
auto scaledArc=arc;scaledArc.frame.scale={2,1,1};RecipeProduct scaledProduct;check(!EvaluateWorldRecipe(scaledArc,course,nullptr,scaledProduct,error)&&error.find("scale")!=std::string::npos,"physical geometry rejects unsupported entity scale instead of visual/collision disagreement");
arc.collisionSegments=4;RecipeProduct proxyProduct;check(EvaluateWorldRecipe(arc,course,nullptr,proxyProduct,error)&&proxyProduct.collisionMesh.vertices.size()<proxyProduct.mesh.vertices.size(),"lower-resolution physical proxy uses same valid recipe without relaxing cooker");
EditorDocument invalidBatch;invalidBatch.GetScene()=s;invalidBatch.Select(rootId);invalidBatch.Select(childId,true);auto beforeInvalid=invalidBatch.GetScene();check(!invalidBatch.BatchProperties({{"parent",std::to_string(childId)}},error)&&ScenesEqual(beforeInvalid,invalidBatch.GetScene()),"batch identity/link fields reject rather than silently ignoring the edit");invalidBatch.BeginEdit();invalidBatch.GetScene().Find(rootId)->parent=childId;invalidBatch.CommitEdit();check(ScenesEqual(invalidBatch.GetScene(),beforeInvalid)&&!invalidBatch.ValidationError().empty(),"continuous invalid edit rejects and restores last good on commit");
check(!invalidBatch.ReparentSelection(childId,error,false)&&ScenesEqual(beforeInvalid,invalidBatch.GetScene()),"dedicated hierarchy command rejects cycle atomically");
check(!ScenesEqual(editorial,s),"editor-only recipe/folder changes participate in undo equality while retaining gameplay fingerprint");
std::set<AssetId> direct;auto testAssets=s;SceneRenderComponent rr;rr.meshAsset="67676767676767676767676700000001";testAssets.Find(rootId)->render=rr;SaveSceneToString(testAssets,localeScene);check(DirectDocumentAssets("scene",localeScene,direct,error)&&direct.count(rr.meshAsset),"typed asset dependency discovery without constructing script VM");
MeshData imported;if(LoadModelMesh("projects/world_workshop/Assets/models/figure.judasmodel",imported,error)&&imported.skeletal){RagdollDefinition mapping;check(FitSkeletonChain(imported.skeletal->skeleton,{}, {"Spindle","Fork","Branch-A","Tip-A","Branch-B","Tip-B"},.18f,mapping,error)&&mapping.bones.size()==6,"real imported multipart non-humanoid skeleton fit through shared service");}
else check(false,"workshop imported skeletal fixture available");
// The original accepted M66 imported rig is local-only and is never rewritten.
if(LoadModelMesh("projects/import_lab/Assets/models/skate_original.judasmodel",imported,error)&&imported.skeletal){RagdollDefinition originalFit;check(FitSkeletonChain(imported.skeletal->skeleton,{}, {"mixamorig:Hips","mixamorig:Spine","mixamorig:RightArm"},.1f,originalFit,error)&&originalFit.bones.size()==3,"original M66 multipart rig resolves selected stable joints without name-specific fitter");}
std::cout<<"SUMMARY "<<count<<" checks "<<failures<<" failures\n";return failures?1:0;}
