#!/usr/bin/env python3
"""Read-only M67 candidate check; never replaces recorded expected hashes."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--allow-staged", action="store_true",
                        help="Allow reviewed checkpoint staging; still verify HEAD, bytes and scope.")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[3]
    manifest = json.loads((Path(__file__).parent / "FINAL_FINGERPRINTS.json").read_text())

    def git(*arguments):
        return subprocess.check_output(["git", *arguments], cwd=root)

    failures = []
    head = git("rev-parse", "HEAD").decode().strip()
    if head != manifest["startingHead"]:
        failures.append("HEAD differs from the recorded starting checkpoint")
    changed = set(git("diff", "--name-only", "-z", "HEAD").decode().split("\0"))
    changed.update(git("ls-files", "--others", "--exclude-standard", "-z").decode().split("\0"))
    changed.discard("")
    expected = set(manifest["changedFiles"])
    for name in sorted(changed - expected):
        failures.append("Unexpected changed/untracked file: " + name)
    for name in sorted(expected - changed):
        failures.append("Recorded change is absent: " + name)
    staged = git("diff", "--cached", "--name-only").decode().splitlines()
    if staged and not args.allow_staged:
        failures.append("Index is not empty (use --allow-staged only for an authorized checkpoint)")
    for name, expected_hash in manifest["sha256"].items():
        path = root / name
        if not path.is_file():
            failures.append("Missing file: " + name)
        elif hashlib.sha256(path.read_bytes()).hexdigest() != expected_hash:
            failures.append("SHA256 mismatch: " + name)
    result = {
        "pass": not failures,
        "head": head,
        "filesChecked": len(manifest["sha256"]),
        "changedFiles": len(expected),
        "stagedFiles": staged,
        "hashExclusions": manifest["hashExclusions"],
        "failures": failures,
        "policy": "Read-only comparison; expected hashes are never regenerated by this checker.",
    }
    print(json.dumps(result, indent=2))
    return 0 if not failures else 1


if __name__ == "__main__":
    raise SystemExit(main())
