#include "AuthoringDocument.h"
#include "NamedAuthoring.h"
#include "WorldBuilder.h"
#include "SceneFingerprint.h"
#include "../..//third_party/nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <set>
namespace {std::string read(const std::string& p){std::ifstream f(p,std::ios::binary);std::ostringstream s;s<<f.rdbuf();return s.str();}bool write(const std::string& p,const std::string& s){std::ofstream f(p,std::ios::binary);f.write(s.data(),std::streamsize(s.size()));return bool(f);}bool normalize(const std::string& kind,const std::string& text,std::string& result,std::string& error){if(kind=="recipe"){WorldRecipe r;if(!ParseWorldRecipe(text,r,error))return false;result=SerializeWorldRecipe(r);return true;}std::string legacy=text;if(IsNamedDocument(text)&&!NamedToLegacy(text,kind,legacy,error,false))return false;return LegacyToNamed(legacy,kind,result,error);}}
bool AuthoringDocument::Load(const std::string& kind,const std::string& path,std::string& error){auto disk=read(path);std::string source;if(!normalize(kind,disk,source,error)){error=path+": "+error;return false;}m_kind=kind;m_path=path;m_source=m_loaded=source;m_disk=disk;m_undo.clear();m_redo.clear();++m_generation;return true;}
bool AuthoringDocument::Replace(const std::string& text,std::string& error){if(text==m_source){error.clear();return true;}std::string candidate;if(!normalize(m_kind,text,candidate,error))return false;if(candidate!=m_source){m_undo.push_back(m_source);if(m_undo.size()>200)m_undo.erase(m_undo.begin());m_redo.clear();m_source=std::move(candidate);++m_generation;}return true;}
bool AuthoringDocument::ExternalChanged()const{return read(m_path)!=m_disk;}
bool AuthoringDocument::Save(std::string& error){if(ExternalChanged()){error="source changed externally; keep dirty work and reload or save a reviewed copy";return false;}if(!PublishAuthoringOutputs(std::filesystem::path(m_path).parent_path().string()+"/.authoring-recovery",{{m_path,m_source,m_disk,true}},error))return false;m_disk=m_source;m_loaded=m_source;return true;}
bool AuthoringDocument::Undo(){if(m_undo.empty())return false;m_redo.push_back(m_source);m_source=std::move(m_undo.back());m_undo.pop_back();++m_generation;return true;}
bool AuthoringDocument::Redo(){if(m_redo.empty())return false;m_undo.push_back(m_source);m_source=std::move(m_redo.back());m_redo.pop_back();++m_generation;return true;}
bool PublishAuthoringOutputs(const std::string& directory,const std::vector<AuthoringOutput>& outputs,std::string& error){namespace fs=std::filesystem;auto stamp=MintAssetId();auto recovery=fs::path(directory)/stamp;size_t published=0;try{std::set<std::string> paths;for(auto& o:outputs){if(!paths.insert(fs::absolute(o.path).lexically_normal().string()).second)throw std::runtime_error("duplicate publication destination");if(fs::exists(o.path)!=o.existed||(o.existed&&read(o.path)!=o.expected))throw std::runtime_error("external change at "+o.path);}fs::create_directories(recovery);nlohmann::ordered_json journal={{"state","staged"},{"outputs",nlohmann::ordered_json::array()}};for(size_t i=0;i<outputs.size();++i){auto& o=outputs[i];if(!write((recovery/(std::to_string(i)+".new")).string(),o.bytes)||!write((recovery/(std::to_string(i)+".old")).string(),o.expected))throw std::runtime_error("cannot stage authoring output");journal["outputs"].push_back({{"path",fs::absolute(o.path).string()},{"existed",o.existed},{"oldHash",SceneFingerprintSha256(o.expected)},{"newHash",SceneFingerprintSha256(o.bytes)}});}if(!write((recovery/"journal.json").string(),journal.dump(2)))throw std::runtime_error("cannot write recovery journal");for(auto& o:outputs){if(fs::exists(o.path)!=o.existed||(o.existed&&read(o.path)!=o.expected))throw std::runtime_error("external change before publication at "+o.path);}for(auto& o:outputs){if(fs::exists(o.path)!=o.existed||(o.existed&&read(o.path)!=o.expected))throw std::runtime_error("external change at publication boundary: "+o.path);fs::create_directories(fs::absolute(o.path).parent_path());auto stage=o.path+".authoring-stage-"+stamp;if(!write(stage,o.bytes))throw std::runtime_error("cannot stage "+o.path);fs::rename(stage,o.path);++published;}journal["state"]="complete";write((recovery/"journal.json").string(),journal.dump(2));fs::remove_all(recovery);return true;}catch(const std::exception& e){bool clean=true;for(size_t i=published;i>0;--i){auto& o=outputs[i-1];if(!fs::exists(o.path)||read(o.path)!=o.bytes){clean=false;continue;}if(o.existed){auto rollback=o.path+".authoring-rollback-"+stamp;if(!write(rollback,o.expected)){clean=false;continue;}std::error_code ec;fs::rename(rollback,o.path,ec);clean&=!ec;}else{std::error_code ec;fs::remove(o.path,ec);clean&=!ec;}}for(auto& o:outputs){std::error_code ignored;fs::remove(o.path+".authoring-stage-"+stamp,ignored);}error=std::string(e.what())+(clean?"; prior outputs restored":"; external edit retained")+"; recovery journal: "+recovery.string();return false;}}
