#include "RecipePreview.h"
#include "SceneFingerprint.h"
#include <filesystem>
#include <fstream>
#include <sstream>
namespace {std::string read(const std::string& p){std::ifstream f(p,std::ios::binary);std::ostringstream s;s<<f.rdbuf();return s.str();}AuthoringOutput output(const std::string& p,const std::string& bytes){bool exists=std::filesystem::exists(p);auto expected=exists?read(p):"";if(exists&&expected!=bytes)throw std::runtime_error("Generated revision changed externally: "+p);return {p,bytes,expected,exists};}}
RecipePreviewTask::~RecipePreviewTask(){std::error_code ignored;std::filesystem::remove_all(stage,ignored);}
std::shared_ptr<RecipePreviewTask> PreviewRecipe(JobSystem& jobs,const WorldRecipe& recipe,const Scene& scene,const AssetDatabase& assets,uint64_t generation,const std::string& project){auto task=std::make_shared<RecipePreviewTask>();task->generation=generation;task->project=project;task->parameters=SerializeWorldRecipe(recipe);task->stage=(std::filesystem::temp_directory_path()/("judas-recipe-"+MintAssetId())).string();if(!recipe.prefabAsset.empty())for(auto& [_,record]:assets.Records())if(record.type==AssetType::Prefab&&!record.missing){task->sourceHashes[record.path]=SceneFingerprintSha256(read(record.path));task->sourceHashes[record.path+".judasmeta"]=SceneFingerprintSha256(read(record.path+".judasmeta"));}task->job=jobs.Submit([task,recipe,scene,assets](JobContext& ctx){if(!EvaluateWorldRecipe(recipe,scene,&assets,task->product,task->error,&ctx)){if(ctx.CancelRequested())ctx.ReportCancelled();else ctx.SetError(task->error);return;}task->product.documentGeneration=task->generation;task->product.sourceRevision=SceneFingerprintSha256(task->parameters);if(!task->product.mesh.vertices.empty()){std::filesystem::create_directories(task->stage);auto mesh=task->stage+"/mesh.judasmodel",collision=task->stage+"/mesh.judascollision";if(!BakeRecipeGeometry(task->product,mesh,collision,task->error)){ctx.SetError(task->error);return;}task->meshBytes=read(mesh);task->proxyBytes=read(mesh+".proxy.judasmodel");task->collisionBytes=read(collision);}if(ctx.CancelRequested())ctx.ReportCancelled();},JobPriority::Low,"Authoring recipe preview");return task;}
bool PublishRecipeResources(const RecipePreviewTask& task,const Project& project,AssetDatabase& assets,std::string& error){try{namespace fs=std::filesystem;for(auto& [path,hash]:task.sourceHashes)if(SceneFingerprintSha256(read(path))!=hash){error="Recipe source changed externally during preview: "+path;return false;}if(task.meshBytes.empty())return true;if(task.project!=project.ProjectFile()){error="stale project generation";return false;}auto& r=task.product.recipe;auto base=r.id+"-"+r.geometryRevision.substr(0,16)+"-"+r.renderAsset.substr(0,8);auto dir=fs::path(project.AssetsDir())/"Generated";auto mesh=(dir/(base+".judasmodel")).string(),collision=(dir/(base+".judascollision")).string();auto proxy=(dir/(base+"-proxy.judasmodel")).string();std::vector<AuthoringOutput> outputs={output(mesh,task.meshBytes),output(proxy,task.proxyBytes),output(collision,task.collisionBytes)};for(auto [path,id,type]:{std::make_tuple(mesh,r.renderAsset,AssetType::Mesh),std::make_tuple(proxy,r.proxyAsset,AssetType::Mesh),std::make_tuple(collision,r.collisionAsset,AssetType::Collision)}){auto meta=task.stage+"/"+id+".judasmeta";if(!AssetDatabase::WriteMeta(meta,id,type,"",error))return false;outputs.push_back(output(path+".judasmeta",read(meta)));}if(!PublishAuthoringOutputs((fs::path(project.RootDir())/"Authoring/recovery").string(),outputs,error))return false;assets.Scan(project.RootDir(),project.AssetsDir());return true;}catch(const std::exception& e){error=e.what();return false;}}
