#include "TerrainAuthoring.h"
#include "AuthoringDocument.h"
#include "CollisionAsset.h"
#include "ModelArchive.h"
#include "SceneFingerprint.h"
#include "TextureLoader.h"
#include "../../third_party/nlohmann/json.hpp"
#include <filesystem>
#include <fstream>
#include <cmath>
#include <chrono>
#include <algorithm>
#include <stdexcept>
namespace fs=std::filesystem;using Json=nlohmann::json;
namespace {
// Preflight bounds the DOM itself, before allocating sample arrays from counts.
struct TerrainSax : nlohmann::json_sax<Json> {
 size_t events=0,depth=0;
 bool Next(){return ++events<=700000;}
 bool null() override{return Next();}bool boolean(bool) override{return Next();}
 bool number_integer(number_integer_t) override{return Next();}
 bool number_unsigned(number_unsigned_t) override{return Next();}
 bool number_float(number_float_t v,const string_t&) override{return Next()&&std::isfinite(v);}
 bool string(string_t& v) override{return Next()&&v.size()<=4096;}
 bool binary(binary_t&) override{return false;}
 bool key(string_t& v) override{return string(v);}
 bool start_object(std::size_t n) override{return Next()&&++depth<16&&(n==size_t(-1)||n<=65536);}
 bool end_object() override{--depth;return Next();}
 bool start_array(std::size_t n) override{return start_object(n);}
 bool end_array() override{return end_object();}
 bool parse_error(std::size_t,const std::string&,const nlohmann::detail::exception&) override{return false;}
};
std::string Read(const std::string& p,size_t bound=16*1024*1024){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f||f.tellg()<0||uint64_t(f.tellg())>bound)throw std::runtime_error("missing/bounded terrain file: "+p);std::string s(size_t(f.tellg()),'\0');f.seekg(0);f.read(s.data(),s.size());if(!f)throw std::runtime_error("terrain read: "+p);return s;}
bool Finite(float v){return std::isfinite(v);}
void Require(bool value,const std::string& error){if(!value)throw std::runtime_error(error);}
fs::path Owned(const fs::path& root,const fs::path& p){auto base=fs::weakly_canonical(root),file=fs::weakly_canonical(p.is_absolute()?p:base/p);auto rel=file.lexically_relative(base);Require(!rel.empty()&&!rel.is_absolute()&&*rel.begin()!="..","terrain path escapes project");return file;}
std::string Tga(const TextureData& t){std::string b(18,'\0');b[2]=2;b[12]=char(t.width&255);b[13]=char(t.width>>8);b[14]=char(t.height&255);b[15]=char(t.height>>8);b[16]=32;b[17]=8;for(size_t i=0;i<t.pixels.size();i+=4){b+=char(t.pixels[i+2]);b+=char(t.pixels[i+1]);b+=char(t.pixels[i]);b+=char(t.pixels[i+3]);}return b;}
}
bool ValidateTerrain(const TerrainSource& t,std::string& e){
 auto fail=[&](const char* s){e=s;return false;};
 if(t.version!=1)return fail("unsupported terrain version");
 if(t.nx<2||t.nz<2||t.nx>257||t.nz>257||uint64_t(t.nx)*t.nz>65536||uint64_t(t.nx-1)*(t.nz-1)*2>65536)return fail("terrain sample/triangle bounds");
 if(!Finite(t.width)||!Finite(t.depth)||t.width<.1f||t.depth<.1f||t.width>10000||t.depth>10000)return fail("terrain dimensions .1..10000 metres");
 if(t.textureSize<16||t.textureSize>1024)return fail("terrain texture size 16..1024");
 if(!IsValidAssetId(t.identity)||!IsValidAssetId(t.meshId)||!IsValidAssetId(t.textureId)||!IsValidAssetId(t.collisionId)||t.meshId==t.textureId||t.meshId==t.collisionId||t.textureId==t.collisionId)return fail("terrain stable identities");
 if(t.productDirectory.empty()||fs::path(t.productDirectory).is_absolute()||t.productDirectory.find("..")!=std::string::npos)return fail("terrain product directory");
 if(t.heights.size()!=size_t(t.nx)*t.nz||t.weights.size()!=t.heights.size())return fail("terrain sample count");
 if(t.layers.size()>4)return fail("terrain supports at most four base-color layers");
 for(size_t k=0;k<t.layers.size();++k){auto& l=t.layers[k];if(l.key.empty()||!IsValidAssetId(l.texture)||!Finite(l.tileMetres)||l.tileMetres<.05f||l.tileMetres>10000)return fail("terrain layer identity/tiling");for(size_t j=0;j<k;++j)if(l.key==t.layers[j].key)return fail("duplicate terrain layer identity");}
 for(size_t i=0;i<t.heights.size();++i){if(!Finite(t.heights[i])||std::abs(t.heights[i])>10000)return fail("terrain finite height bound");float sum=0;for(unsigned k=0;k<4;++k){float w=t.weights[i][k];if(!Finite(w)||w<0||w>1||(k>=std::max(size_t(1),t.layers.size())&&w!=0))return fail("terrain layer weights");sum+=w;}if(std::abs(sum-1)>1e-5)return fail("terrain weights must normalize to one");}e.clear();return true;
}
TerrainSource CreateTerrain(unsigned nx,unsigned nz,float w,float d){TerrainSource t;t.nx=nx;t.nz=nz;t.width=w;t.depth=d;t.identity=MintAssetId();t.meshId=MintAssetId();t.textureId=MintAssetId();t.collisionId=MintAssetId();t.productDirectory="Assets/Terrain/"+t.identity;Require(nx>=2&&nz>=2&&nx<=257&&nz<=257&&uint64_t(nx)*nz<=65536&&uint64_t(nx-1)*(nz-1)*2<=65536,"terrain allocation bounds");t.heights.resize(size_t(nx)*nz);t.weights.resize(t.heights.size(),{1,0,0,0});std::string e;Require(ValidateTerrain(t,e),e);return t;}
TerrainSource ForkTerrain(const TerrainSource& s){auto t=s;t.identity=MintAssetId();t.meshId=MintAssetId();t.textureId=MintAssetId();t.collisionId=MintAssetId();t.productDirectory=(fs::path(s.productDirectory).parent_path()/t.identity).generic_string();return t;}
std::string SerializeTerrain(const TerrainSource& t){std::string e;Require(ValidateTerrain(t,e),e);Json j={{"format","JudasTerrain"},{"version",t.version},{"nx",t.nx},{"nz",t.nz},{"width",t.width},{"depth",t.depth},{"textureSize",t.textureSize},{"identity",t.identity},{"meshId",t.meshId},{"textureId",t.textureId},{"collisionId",t.collisionId},{"productDirectory",t.productDirectory},{"heights",t.heights},{"weights",t.weights},{"layers",Json::array()}};for(auto& l:t.layers)j["layers"].push_back({{"key",l.key},{"texture",l.texture},{"tileMetres",l.tileMetres}});return j.dump(2)+"\n";}
bool ParseTerrain(const std::string& s,TerrainSource& out,std::string& e){try{Require(s.size()<=16*1024*1024,"terrain source byte bound");TerrainSax guard;Require(Json::sax_parse(s,&guard),"malformed/bounded terrain source");auto j=Json::parse(s,[](int depth,Json::parse_event_t,const Json&){Require(depth<16,"terrain nesting bound");return true;});Require(j.at("format")=="JudasTerrain","terrain format");auto integer=[&](const char* key,uint64_t low,uint64_t high){const auto& value=j.at(key);Require(value.is_number_integer(),std::string("terrain integral field: ")+key);auto n=value.get<uint64_t>();Require(n>=low&&n<=high,std::string("terrain integer bounds: ")+key);return unsigned(n);};auto nx=integer("nx",2,257),nz=integer("nz",2,257);auto version=integer("version",1,1),textureSize=integer("textureSize",16,1024);auto t=CreateTerrain(nx,nz,j.at("width"),j.at("depth"));Require(j.at("heights").size()==t.heights.size()&&j.at("weights").size()==t.weights.size()&&j.at("layers").size()<=4,"terrain container bounds");t.version=version;t.textureSize=textureSize;t.identity=j.at("identity");t.meshId=j.at("meshId");t.textureId=j.at("textureId");t.collisionId=j.at("collisionId");t.productDirectory=j.at("productDirectory");t.heights=j.at("heights").get<std::vector<float>>();t.weights=j.at("weights").get<std::vector<std::array<float,4>>>();for(auto& l:j.at("layers"))t.layers.push_back({l.at("key"),l.at("texture"),l.at("tileMetres")});Require(ValidateTerrain(t,e),e);out=std::move(t);e.clear();return true;}catch(const std::exception& x){e=x.what();return false;}}
bool LoadTerrain(const std::string& path,TerrainSource& out,std::string& e){try{return ParseTerrain(Read(path),out,e);}catch(const std::exception& x){e=x.what();return false;}}
MeshData BuildTerrainMesh(const TerrainSource& t){std::string e;Require(ValidateTerrain(t,e),e);MeshData m;m.vertices.resize(t.heights.size());for(unsigned z=0;z<t.nz;++z)for(unsigned x=0;x<t.nx;++x){auto& v=m.vertices[z*t.nx+x];v.position={float(x)*t.width/(t.nx-1)-t.width*.5f,t.heights[z*t.nx+x],float(z)*t.depth/(t.nz-1)-t.depth*.5f};v.normal={0,0,0};v.uv={float(x)/(t.nx-1),float(z)/(t.nz-1)};}
 for(unsigned z=0;z+1<t.nz;++z)for(unsigned x=0;x+1<t.nx;++x){unsigned a=z*t.nx+x,b=a+1,c=a+t.nx,d=c+1;m.indices.insert(m.indices.end(),{a,c,b,b,c,d});}
 for(size_t i=0;i<m.indices.size();i+=3){auto a=m.indices[i],b=m.indices[i+1],c=m.indices[i+2];auto n=glm::cross(m.vertices[b].position-m.vertices[a].position,m.vertices[c].position-m.vertices[a].position);for(auto k:{a,b,c})m.vertices[k].normal+=n;}
 for(auto& v:m.vertices){v.normal=glm::normalize(v.normal);auto tangent=glm::normalize(glm::vec3(1,0,0)-v.normal*v.normal.x);v.tangent={tangent,-1};}m.primitives.emplace_back(0,unsigned(m.indices.size()),-1,"terrain");return m;
}
bool PaintTerrainTexture(const TerrainSource& t,const AssetDatabase& assets,TextureData& out,std::string& e){try{Require(ValidateTerrain(t,e),e);std::vector<TextureData> textures;for(auto& l:t.layers){auto* a=assets.Find(l.texture);Require(a&&a->type==AssetType::Texture&&!a->missing,"terrain layer missing texture "+l.texture);TextureData tex;auto encoded=Read(a->path,16*1024*1024);Require(DecodeTextureFromMemory(reinterpret_cast<const uint8_t*>(encoded.data()),encoded.size(),a->path,tex,e),e);Require(uint64_t(tex.width)*tex.height<=2048*2048,"terrain layer image bound");textures.push_back(std::move(tex));}TextureData result;result.width=result.height=int(t.textureSize);result.pixels.resize(size_t(t.textureSize)*t.textureSize*4);
 for(unsigned z=0;z<t.textureSize;++z)for(unsigned x=0;x<t.textureSize;++x){float u=float(x)/(t.textureSize-1),v=float(z)/(t.textureSize-1),gx=u*(t.nx-1),gz=v*(t.nz-1);unsigned ix=std::min(unsigned(gx),t.nx-2),iz=std::min(unsigned(gz),t.nz-2);float fx=gx-ix,fz=gz-iz;glm::vec3 color{.35f,.5f,.25f};if(!textures.empty()){color={0,0,0};for(unsigned k=0;k<textures.size();++k){float w=(1-fz)*((1-fx)*t.weights[iz*t.nx+ix][k]+fx*t.weights[iz*t.nx+ix+1][k])+fz*((1-fx)*t.weights[(iz+1)*t.nx+ix][k]+fx*t.weights[(iz+1)*t.nx+ix+1][k]);auto& tex=textures[k];float tx=u*t.width/t.layers[k].tileMetres,tz=v*t.depth/t.layers[k].tileMetres;unsigned px=std::min(unsigned((tx-std::floor(tx))*tex.width),unsigned(tex.width-1)),pz=std::min(unsigned((tz-std::floor(tz))*tex.height),unsigned(tex.height-1));size_t p=(size_t(pz)*tex.width+px)*4;for(unsigned c=0;c<3;++c)color[c]+=w*std::pow(float(tex.pixels[p+c])/255,2.2f);}for(unsigned c=0;c<3;++c)color[c]=std::pow(std::clamp(color[c],0.f,1.f),1/2.2f);}size_t p=(size_t(z)*t.textureSize+x)*4;for(unsigned c=0;c<3;++c)result.pixels[p+c]=uint8_t(std::round(std::clamp(color[c],0.f,1.f)*255));result.pixels[p+3]=255;}
 out=std::move(result);e.clear();return true;}catch(const std::exception& x){e=x.what();return false;}}
// Exact interpolation of the emitted a-c-b / b-c-d grid triangles, for
// editor footprint points. This is not a parallel runtime physics query.
bool TerrainPoint(const TerrainSource& t,float x,float z,glm::vec3& point){
 if(!Finite(x)||!Finite(z)||x<-t.width*.5f||x>t.width*.5f||z<-t.depth*.5f||z>t.depth*.5f)return false;
 float gx=(x/t.width+.5f)*(t.nx-1),gz=(z/t.depth+.5f)*(t.nz-1);
 unsigned ix=std::min(unsigned(gx),t.nx-2),iz=std::min(unsigned(gz),t.nz-2);float fx=gx-ix,fz=gz-iz;
 auto a=t.heights[iz*t.nx+ix],b=t.heights[iz*t.nx+ix+1],c=t.heights[(iz+1)*t.nx+ix],d=t.heights[(iz+1)*t.nx+ix+1];
 float height=fx+fz<=1?a+(b-a)*fx+(c-a)*fz:d+(c-d)*(1-fx)+(b-d)*(1-fz);point={x,height,z};return true;
}
bool PickTerrain(const MeshData& m,glm::vec3 o,glm::vec3 d,glm::vec3& hit){float nearest=INFINITY;for(size_t i=0;i<m.indices.size();i+=3){auto a=m.vertices[m.indices[i]].position,b=m.vertices[m.indices[i+1]].position,c=m.vertices[m.indices[i+2]].position;auto e1=b-a,e2=c-a,p=glm::cross(d,e2);float det=glm::dot(e1,p);if(std::abs(det)<1e-8f)continue;float inv=1/det;auto t=o-a;float u=glm::dot(t,p)*inv;if(u<0||u>1)continue;auto q=glm::cross(t,e1);float v=glm::dot(d,q)*inv;if(v<0||u+v>1)continue;float dist=glm::dot(e2,q)*inv;if(dist>=0&&dist<nearest)nearest=dist;}if(!std::isfinite(nearest))return false;hit=o+d*nearest;return true;}
TerrainDraft::Snapshot TerrainDraft::Capture()const{return {source.heights,source.weights};}
void TerrainDraft::Restore(const Snapshot& s){if(source.heights!=s.heights)++m_geometryRevision;source.heights=s.heights;source.weights=s.weights;++m_revision;}
void TerrainDraft::Push(std::vector<Snapshot>& list,Snapshot s){size_t bytes=s.heights.size()*20;size_t bound=std::min(size_t(64),std::max(size_t(1),size_t(32*1024*1024)/std::max(size_t(1),bytes)));if(list.size()>=bound)list.erase(list.begin());list.push_back(std::move(s));}
bool TerrainDraft::Open(const std::string& p,std::string& e){try{
 // Parse and guard the same bytes. A second read could accidentally accept an
 // intervening external edit as the baseline for an older in-memory draft.
 auto bytes=Read(p);TerrainSource t;if(!ParseTerrain(bytes,t,e))return false;
 source=std::move(t);m_path=p;m_disk=std::move(bytes);m_saved=SerializeTerrain(source);
 m_active=false;m_dirty=false;m_undo.clear();m_redo.clear();++m_revision;++m_geometryRevision;e.clear();return true;
 }catch(const std::exception& x){e=x.what();return false;}}
bool TerrainDraft::ExternalChanged()const{try{return !m_path.empty()&&Read(m_path)!=m_disk;}catch(...){return true;}}
bool TerrainDraft::Dirty()const{return m_dirty;}
bool TerrainDraft::Save(std::string& e){if(m_active){e="finish terrain gesture before saving";return false;}try{auto bytes=SerializeTerrain(source);bool exists=fs::exists(m_path);Require(!exists||Read(m_path)==m_disk,"terrain source changed externally; reopen or save an independent copy");auto directory=fs::absolute(m_path).parent_path();fs::create_directories(directory);if(!PublishAuthoringOutputs(directory.string(),{{m_path,bytes,m_disk,exists}},e))return false;m_disk=m_saved=bytes;m_dirty=false;e.clear();return true;}catch(const std::exception& x){e=x.what();return false;}}
bool TerrainDraft::Begin(glm::vec3 p,const TerrainBrush& b,std::string& e){if(m_active){e="terrain stroke already active";return false;}if(!Finite(b.radius)||b.radius<.05f||b.radius>1000||!Finite(b.strength)||b.strength<0||b.strength>100||!Finite(b.falloff)||b.falloff<.1f||b.falloff>8||b.layer>=std::max(size_t(1),source.layers.size())||!Finite(p.x)||!Finite(p.y)||!Finite(p.z)||std::abs(p.x)>source.width*.5f||std::abs(p.z)>source.depth*.5f||std::abs(p.y)>10000){e="terrain brush bounds";return false;}m_before=Capture();m_dirtyBefore=m_dirty;m_brush=b;m_last=p;m_remainder=0;m_flatten=p.y;m_active=true;Dab(p);e.clear();return true;}
bool TerrainDraft::Continue(glm::vec3 p,std::string& e){if(!m_active||!Finite(p.x)||!Finite(p.y)||!Finite(p.z)||std::abs(p.x)>source.width*.5f||std::abs(p.z)>source.depth*.5f||std::abs(p.y)>10000){e="invalid terrain stroke sample";return false;}auto delta=p-m_last;delta.y=0;float length=glm::length(delta),spacing=m_brush.radius*.2f;if(length/spacing>4096){e="terrain stroke segment exceeds 4096 scheduled dabs; submit bounded segments";return false;}if(length>0){float next=spacing-m_remainder;for(;next<=length;next+=spacing){auto at=m_last+delta*(next/length);Dab(at);}m_remainder=std::fmod(m_remainder+length,spacing);}m_last=p;e.clear();return true;}
void TerrainDraft::Dab(glm::vec3 p){auto& t=source;std::vector<float> old;if(m_brush.kind==TerrainBrushKind::Smooth)old=t.heights;float dx=t.width/(t.nx-1),dz=t.depth/(t.nz-1);int minX=std::max(0,int(std::floor((p.x-m_brush.radius+t.width*.5f)/dx))),maxX=std::min(int(t.nx)-1,int(std::ceil((p.x+m_brush.radius+t.width*.5f)/dx)));int minZ=std::max(0,int(std::floor((p.z-m_brush.radius+t.depth*.5f)/dz))),maxZ=std::min(int(t.nz)-1,int(std::ceil((p.z+m_brush.radius+t.depth*.5f)/dz)));for(int z=minZ;z<=maxZ;++z)for(int x=minX;x<=maxX;++x){float distance=glm::length(glm::vec2(x*dx-t.width*.5f-p.x,z*dz-t.depth*.5f-p.z));if(distance>=m_brush.radius)continue;float f=std::pow(1-distance/m_brush.radius,m_brush.falloff),amount=m_brush.strength*f;size_t i=size_t(z)*t.nx+x;switch(m_brush.kind){case TerrainBrushKind::Raise:t.heights[i]+=amount;break;case TerrainBrushKind::Lower:t.heights[i]-=amount;break;case TerrainBrushKind::Flatten:t.heights[i]=glm::mix(t.heights[i],m_flatten,std::min(amount,1.f));break;case TerrainBrushKind::Smooth:{float sum=0;int count=0;for(int zz=std::max(z-1,0);zz<=std::min(z+1,int(t.nz)-1);++zz)for(int xx=std::max(x-1,0);xx<=std::min(x+1,int(t.nx)-1);++xx){sum+=old[size_t(zz)*t.nx+xx];++count;}t.heights[i]=glm::mix(old[i],sum/count,std::min(amount,1.f));break;}case TerrainBrushKind::Paint:{float blend=std::min(amount,1.f);for(unsigned k=0;k<4;++k)t.weights[i][k]*=1-blend;t.weights[i][m_brush.layer]+=blend;break;}}t.heights[i]=std::clamp(t.heights[i],-10000.f,10000.f);}MarkChanged(m_brush.kind!=TerrainBrushKind::Paint);}
void TerrainDraft::End(){if(!m_active)return;Push(m_undo,std::move(m_before));m_redo.clear();m_active=false;m_dirty=SerializeTerrain(source)!=m_saved;}
void TerrainDraft::Cancel(){if(m_active){Restore(m_before);m_active=false;m_dirty=m_dirtyBefore;}}
bool TerrainDraft::Undo(){if(m_active||m_undo.empty())return false;Push(m_redo,Capture());Restore(m_undo.back());m_undo.pop_back();m_dirty=SerializeTerrain(source)!=m_saved;return true;}
bool TerrainDraft::Redo(){if(m_active||m_redo.empty())return false;Push(m_undo,Capture());Restore(m_redo.back());m_redo.pop_back();m_dirty=SerializeTerrain(source)!=m_saved;return true;}
bool CookTerrain(const TerrainSource& t,const std::string& path,const std::string& root,const AssetDatabase& assets,TerrainCookResult& result,std::string& e,const std::function<bool()>& cancelled){auto start=std::chrono::steady_clock::now();try{Require(ValidateTerrain(t,e),e);auto sourcePath=Owned(root,path),dir=Owned(root,t.productDirectory);auto assetRoot=Owned(root,assets.AssetsDir());auto outputRelative=dir.lexically_relative(assetRoot);Require(!outputRelative.empty()&&!outputRelative.is_absolute()&&*outputRelative.begin()!="..","terrain products must belong to the project asset directory");auto sourceBytes=Read(sourcePath.string());TerrainSource disk;Require(ParseTerrain(sourceBytes,disk,e)&&SerializeTerrain(disk)==SerializeTerrain(t),"save current terrain source before cooking");std::map<std::string,AuthoringOutput> expected;for(const char* name:{"terrain.judasmodel","terrain.tga","terrain.judascollision","terrain.judasmodel.judasmeta","terrain.tga.judasmeta","terrain.judascollision.judasmeta","terrain.receipt.json"}){auto p=Owned(root,dir/name);AuthoringOutput o;o.path=p.string();o.existed=fs::exists(p);if(o.existed)o.expected=Read(o.path,64*1024*1024);expected[o.path]=std::move(o);}
 std::vector<AuthoringOutput> outputs;auto output=[&](const fs::path& p,const std::string& bytes){auto o=expected.at(Owned(root,p).string());o.bytes=bytes;outputs.push_back(std::move(o));};
 auto receiptPath=dir/"terrain.receipt.json";Json inputs=Json::object();inputs[sourcePath.lexically_relative(fs::weakly_canonical(root)).generic_string()]=SceneFingerprintSha256(sourceBytes);for(auto& l:t.layers){auto* a=assets.Find(l.texture);Require(a&&a->type==AssetType::Texture&&!a->missing,"missing terrain layer texture");auto owned=Owned(root,a->path);std::string digest;Require(SceneFingerprintSha256File(owned.string(),digest,e),e);inputs[owned.lexically_relative(fs::weakly_canonical(root)).generic_string()]=digest;auto meta=Owned(root,a->path+".judasmeta");Require(SceneFingerprintSha256File(meta.string(),digest,e),e);inputs[meta.lexically_relative(fs::weakly_canonical(root)).generic_string()]=digest;}
 auto mesh=BuildTerrainMesh(t);Json layerIds=Json::array();for(auto& layer:t.layers)layerIds.push_back(layer.texture);mesh.importRecord=Json({{"kind","terrain"},{"source",sourcePath.lexically_relative(fs::weakly_canonical(root)).generic_string()},{"receipt",receiptPath.lexically_relative(fs::weakly_canonical(root)).generic_string()},{"layers",layerIds},{"appearance",t.textureId}}).dump();std::vector<uint8_t> model;Require(EncodeModelArchive(mesh,model,e),e);std::string meshBytes(model.begin(),model.end());auto modelPath=dir/"terrain.judasmodel",collisionPath=dir/"terrain.judascollision",texturePath=dir/"terrain.tga";
 for(auto pair:{std::make_pair(t.meshId,modelPath),std::make_pair(t.textureId,texturePath),std::make_pair(t.collisionId,collisionPath)}){auto* existing=assets.Find(pair.first);Require(!existing||fs::weakly_canonical(existing->path)==fs::weakly_canonical(pair.second),"terrain product identity belongs to another asset; fork first");}
 bool geometryChanged=!fs::exists(modelPath)||Read(modelPath.string(),64*1024*1024)!=meshBytes;TextureData texture;Require(PaintTerrainTexture(t,assets,texture,e),e);auto textureBytes=Tga(texture);bool appearanceChanged=!fs::exists(texturePath)||Read(texturePath.string(),64*1024*1024)!=textureBytes;Json products=Json::object();products[modelPath.lexically_relative(fs::weakly_canonical(root)).generic_string()]=SceneFingerprintSha256(meshBytes);products[texturePath.lexically_relative(fs::weakly_canonical(root)).generic_string()]=SceneFingerprintSha256(textureBytes);
 fs::create_directories(dir);if(geometryChanged||!fs::exists(collisionPath)){CollisionAsset collision;CollisionCookSettings settings;Require(CookCollision(mesh,settings,collision,e),e);collision.sourceAsset=t.meshId;collision.sourceFingerprint=SceneFingerprintSha256(meshBytes);collision.settingsFingerprint=CollisionSettingsFingerprint(settings);auto temporary=dir/(".terrain-"+MintAssetId()+".tmp");if(!SaveCollisionAsset(temporary.string(),collision,e))throw std::runtime_error(e);auto bytes=Read(temporary.string(),64*1024*1024);fs::remove(temporary);output(collisionPath,bytes);products[collisionPath.lexically_relative(fs::weakly_canonical(root)).generic_string()]=SceneFingerprintSha256(bytes);}else {std::string digest;Require(SceneFingerprintSha256File(collisionPath.string(),digest,e),e);products[collisionPath.lexically_relative(fs::weakly_canonical(root)).generic_string()]=digest;}
 if(geometryChanged)output(modelPath,meshBytes);
 if(appearanceChanged)output(texturePath,textureBytes);
 auto meta=[&](const fs::path& p,const std::string& id,const char* type){output(p.string()+".judasmeta","JudasAssetMeta 1\nid \""+id+"\"\ntype "+type+"\nsource \"terrain-authoring\"\n");};meta(modelPath,t.meshId,"mesh");meta(texturePath,t.textureId,"texture");meta(collisionPath,t.collisionId,"collision");
 output(receiptPath,Json({{"format","JudasTerrainCook"},{"version",1},{"revision","M75-1"},{"inputs",inputs},{"products",products}}).dump(2)+"\n");
 Require(!cancelled||!cancelled(),"terrain cook cancelled; last good products retained");for(auto it=inputs.begin();it!=inputs.end();++it){std::string hash;Require(SceneFingerprintSha256File(Owned(root,it.key()).string(),hash,e)&&hash==it.value(),"terrain source/dependency changed during cook");}
 // Guard retained products too: paint-only/unchanged cooks must not issue a
 // new receipt for geometry another author replaced during preparation.
 for(const auto& [file,previous]:expected)Require(fs::exists(file)==previous.existed&&(!previous.existed||Read(file,64*1024*1024)==previous.expected),"terrain product changed during cook: "+file);
 Require(PublishAuthoringOutputs(dir.string(),outputs,e),e);result.geometryChanged=geometryChanged;result.appearanceChanged=appearanceChanged;for(auto& o:outputs)result.bytes+=o.bytes.size();result.milliseconds=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();e.clear();return true;}catch(const std::exception& x){e=x.what();return false;}}
