#define GLM_ENABLE_EXPERIMENTAL
#include "WorldBuilder.h"
#include "NamedAuthoring.h"
#include "CollisionAsset.h"
#include "ModelArchive.h"
#include "SceneSerialization.h"
#include "SceneFingerprint.h"
#include "ScriptSystem.h"
#include "PerformanceProfiler.h"
#include "../..//third_party/nlohmann/json.hpp"
#include <glm/gtx/quaternion.hpp>
#include <fstream>
#include <sstream>
#include <cmath>
#include <set>
#include <type_traits>
#include <limits>
using J=nlohmann::ordered_json;
namespace {
bool fail(std::string& e,const std::string& s){e=s;return false;}
J xyz(glm::vec3 v){return {v.x,v.y,v.z};}
J xy(glm::vec2 v){return {v.x,v.y};}
glm::vec3 xyz(const J& j){if(!j.is_array()||j.size()!=3)throw std::runtime_error("vec3 needs three numbers");return {j[0].get<float>(),j[1].get<float>(),j[2].get<float>()};}
template<class T>T typed(const J& j,const char* name){if constexpr(std::is_integral_v<T>&&!std::is_same_v<T,bool>){if(!j.is_number_integer()||j.get<long double>()<0||j.get<long double>()>std::numeric_limits<T>::max())throw std::runtime_error(std::string("recipe/data/")+name+": bounded unsigned integer required");}return j.get<T>();}
bool valid(const WorldRecipe& r,std::string& error){if(r.id.empty()||r.id.size()>128||r.id.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.")!=std::string::npos||r.id=="."||r.id==".."||r.count>2048||!r.count||r.segments<1||r.segments>512||r.collisionSegments>512||!std::isfinite(r.spacing)||r.spacing<=0||!std::isfinite(r.radius)||r.radius<=0||!std::isfinite(r.startDegrees)||!std::isfinite(r.endDegrees)||std::abs(r.endDegrees-r.startDegrees)>360||!std::isfinite(r.twistDegrees)||r.path.size()<2||r.path.size()>256||r.profile.size()<3||r.profile.size()>64||size_t(r.segments)*(r.path.size()-1)*r.profile.size()>100000)return fail(error,"recipe bounds/finite settings invalid");if(r.type!="linear"&&r.type!="radial"&&r.type!="path"&&r.type!="sweep"&&r.type!="arc")return fail(error,"unsupported recipe type "+r.type);for(auto p:r.path)if(!std::isfinite(glm::dot(p,p)))return fail(error,"nonfinite path point");float sign=0;for(size_t i=0;i<r.profile.size();++i){auto a=r.profile[i],b=r.profile[(i+1)%r.profile.size()],c=r.profile[(i+2)%r.profile.size()];if(!std::isfinite(glm::dot(a,a)))return fail(error,"nonfinite profile point");auto x=b-a,y=c-b;float cross=x.x*y.y-x.y*y.x;if(std::abs(cross)<1e-6f)return fail(error,"profile has collinear/duplicate vertices");if(!i)sign=cross;if(cross*sign<0)return fail(error,"M67 supports convex closed profiles; split concave profiles explicitly");}Scene o;auto& object=o.CreateObject("frame");object.transform=r.frame;std::string t;SaveSceneToString(o,t);Scene check;return LoadSceneFromString(t,check,error);}
std::vector<glm::vec3> samplePath(const WorldRecipe& r){std::vector<glm::vec3> points;if(r.type=="arc"){for(unsigned i=0;i<=r.segments;++i){float a=glm::radians(glm::mix(r.startDegrees,r.endDegrees,float(i)/r.segments));points.push_back({0,r.radius*(1-std::cos(a)),-r.radius*std::sin(a)});}return points;}for(size_t i=0;i+1<r.path.size();++i){auto a=r.path[i?i-1:i],b=r.path[i],c=r.path[i+1],d=r.path[std::min(i+2,r.path.size()-1)];for(unsigned n=0;n<r.segments;++n){float t=float(n)/r.segments;auto p=r.smooth?.5f*((2.f*b)+(-a+c)*t+(2.f*a-5.f*b+4.f*c-d)*t*t+(-a+3.f*b-3.f*c+d)*t*t*t):glm::mix(b,c,t);points.push_back(p);}}points.push_back(r.path.back());return points;}
struct Frame {glm::vec3 p,t,x,y;};
std::vector<Frame> frames(const std::vector<glm::vec3>& points,float twist){std::vector<Frame> result;glm::vec3 x(1,0,0),last(0,0,-1);for(size_t i=0;i<points.size();++i){auto delta=points[i+1<points.size()?i+1:i]-points[i?i-1:i];if(glm::length(delta)<1e-6f)throw std::runtime_error("path contains a zero-length tangent");auto t=glm::normalize(delta);if(i){auto q=glm::rotation(last,t);x=q*x;}else {if(std::abs(glm::dot(x,t))>.99f)x={0,0,1};}x=glm::normalize(x-t*glm::dot(x,t));auto y=glm::normalize(glm::cross(x,t));auto q=glm::angleAxis(glm::radians(twist)*float(i)/std::max(size_t(1),points.size()-1),t);result.push_back({points[i],t,q*x,q*y});last=t;}return result;}
SceneTransform placement(const WorldRecipe& r,glm::vec3 p,glm::quat q){return {r.frame.position+r.frame.rotation*(r.frame.scale*p),glm::normalize(r.frame.rotation*q),r.frame.scale};}
void triangle(MeshData& m,unsigned a,unsigned b,unsigned c){m.indices.insert(m.indices.end(),{a,b,c});}
bool sweep(const WorldRecipe& r,MeshData& mesh,std::string& error){auto fs=frames(samplePath(r),r.twistDegrees);unsigned n=unsigned(r.profile.size());mesh={};for(auto f:fs)for(auto p:r.profile){MeshVertex v;v.position=f.p+f.x*p.x+f.y*p.y;v.uv={p.x,glm::length(f.p-fs.front().p)};mesh.vertices.push_back(v);mesh.sourceVertexIds.push_back(unsigned(mesh.sourceVertexIds.size()));}for(unsigned i=0;i+1<fs.size();++i)for(unsigned j=0;j<n;++j){auto a=i*n+j,b=i*n+(j+1)%n,c=(i+1)*n+j,d=(i+1)*n+(j+1)%n;triangle(mesh,a,c,b);triangle(mesh,b,c,d);}if(r.closed){for(unsigned j=1;j+1<n;++j){triangle(mesh,0,j,j+1);auto base=unsigned(fs.size()-1)*n;triangle(mesh,base,base+j+1,base+j);}}double volume=0;for(size_t i=0;i<mesh.indices.size();i+=3){auto a=glm::dvec3(mesh.vertices[mesh.indices[i]].position),b=glm::dvec3(mesh.vertices[mesh.indices[i+1]].position),c=glm::dvec3(mesh.vertices[mesh.indices[i+2]].position);volume+=glm::dot(a,glm::cross(b,c))/6;}if(volume<0)for(size_t i=0;i<mesh.indices.size();i+=3)std::swap(mesh.indices[i+1],mesh.indices[i+2]);for(auto& v:mesh.vertices)v.normal={0,0,0};for(size_t i=0;i<mesh.indices.size();i+=3){auto a=mesh.indices[i],b=mesh.indices[i+1],c=mesh.indices[i+2];auto normal=glm::cross(mesh.vertices[b].position-mesh.vertices[a].position,mesh.vertices[c].position-mesh.vertices[a].position);mesh.vertices[a].normal+=normal;mesh.vertices[b].normal+=normal;mesh.vertices[c].normal+=normal;}for(auto& v:mesh.vertices){if(glm::length(v.normal)<1e-8f)return fail(error,"degenerate sweep normal");v.normal=glm::normalize(v.normal);}mesh.primitives.emplace_back(0,unsigned(mesh.indices.size()),-1,r.id);CollisionAsset proof;CollisionCookSettings settings;settings.twoSided=!r.closed;return CookCollision(mesh,settings,proof,error);}
}
bool ParseWorldRecipe(const std::string& text,WorldRecipe& out,std::string& error){try{if(text.size()>4*1024*1024)throw std::runtime_error("recipe exceeds 4 MiB");std::vector<std::set<std::string>> stack;auto j=J::parse(text,[&](int depth,J::parse_event_t event,J& v){if(depth>32)throw std::runtime_error("recipe nesting limit");if(event==J::parse_event_t::object_start)stack.emplace_back();if(event==J::parse_event_t::key&&!stack.back().insert(v.get<std::string>()).second)throw std::runtime_error("duplicate recipe key");if(event==J::parse_event_t::object_end)stack.pop_back();return true;});if(j.at("kind")!="recipe"||j.at("schema")!=1||j.size()!=3)throw std::runtime_error("unsupported recipe kind/schema");auto& d=j.at("data");std::set<std::string> allowed={"id","type","templateId","prefabAsset","renderAsset","collisionAsset","proxyAsset","geometryRevision","count","segments","collisionSegments","spacing","radius","startDegrees","endDegrees","twistDegrees","smooth","closed","frame","path","profile","elements"};for(auto it=d.begin();it!=d.end();++it)if(!allowed.count(it.key()))throw std::runtime_error("recipe/data/"+it.key()+": unknown property");WorldRecipe r;
#define GET(K) if(d.contains(#K))r.K=typed<decltype(r.K)>(d[#K],#K);
GET(id) GET(type) GET(templateId) GET(prefabAsset) GET(renderAsset) GET(collisionAsset) GET(proxyAsset) GET(geometryRevision) GET(count) GET(segments) GET(collisionSegments) GET(spacing) GET(radius) GET(startDegrees) GET(endDegrees) GET(twistDegrees) GET(smooth) GET(closed)
#undef GET
if(d.contains("frame")){auto& f=d["frame"];if(!f.is_object()||f.size()!=3||!f.contains("position")||!f.contains("scale")||!f.contains("rotation"))throw std::runtime_error("recipe/data/frame: position, scale and rotation required; unknown fields rejected");r.frame.position=xyz(f.at("position"));r.frame.scale=xyz(f.at("scale"));auto& q=f.at("rotation");if(!q.is_array()||q.size()!=4)throw std::runtime_error("recipe/data/frame/rotation: quaternion [w,x,y,z] required");r.frame.rotation={q[0].get<float>(),q[1].get<float>(),q[2].get<float>(),q[3].get<float>()};}if(d.contains("path")){if(!d["path"].is_array())throw std::runtime_error("recipe/data/path: array required");r.path.clear();for(auto p:d["path"])r.path.push_back(xyz(p));}if(d.contains("profile")){if(!d["profile"].is_array())throw std::runtime_error("recipe/data/profile: array required");r.profile.clear();for(auto p:d["profile"]){if(!p.is_array()||p.size()!=2)throw std::runtime_error("profile vec2");r.profile.push_back({p[0].get<float>(),p[1].get<float>()});}}if(d.contains("elements")){if(!d["elements"].is_array()||d["elements"].size()>2048)throw std::runtime_error("recipe/data/elements: bounded array required");for(auto& e:d["elements"]){if(!e.is_object()||e.size()!=3||!e.contains("key")||!e.contains("object")||!e.contains("generated"))throw std::runtime_error("recipe/data/elements: unknown or missing field");RecipeElement element;element.key=e.at("key").get<std::string>();element.object=typed<uint64_t>(e.at("object"),"elements/object");element.generated=e.at("generated").get<PrefabProperties>();r.elements.push_back(element);}}if(!valid(r,error))return false;out=std::move(r);return true;}catch(const std::exception& e){error=e.what();return false;}}
std::string SerializeWorldRecipe(const WorldRecipe& r){J d;
#define PUT(K) d[#K]=r.K;
PUT(id) PUT(type) PUT(templateId) PUT(prefabAsset) PUT(renderAsset) PUT(collisionAsset) PUT(proxyAsset) PUT(geometryRevision) PUT(count) PUT(segments) PUT(collisionSegments) PUT(spacing) PUT(radius) PUT(startDegrees) PUT(endDegrees) PUT(twistDegrees) PUT(smooth) PUT(closed)
#undef PUT
d["frame"]={{"position",xyz(r.frame.position)},{"scale",xyz(r.frame.scale)},{"rotation",{r.frame.rotation.w,r.frame.rotation.x,r.frame.rotation.y,r.frame.rotation.z}}};d["path"]=J::array();for(auto p:r.path)d["path"].push_back(xyz(p));d["profile"]=J::array();for(auto p:r.profile)d["profile"].push_back(xy(p));d["elements"]=J::array();for(auto& e:r.elements)d["elements"].push_back({{"key",e.key},{"object",e.object},{"generated",e.generated}});return J{{"kind","recipe"},{"schema",1},{"data",d}}.dump(2)+"\n";}
bool EvaluateWorldRecipe(const WorldRecipe& r,const Scene& source,const AssetDatabase* assets,RecipeProduct& out,std::string& error,const JobContext* context){JUDAS_PROFILE_SCOPE("Authoring recipe evaluation");try{if(!valid(r,error))return false;RecipeProduct product;product.scene=source;product.recipe=r;product.recipe.elements.clear();auto cancelled=[&]{return context&&context->CancelRequested();};std::map<std::string,RecipeElement> old;for(auto& e:r.elements)if(!old.emplace(e.key,e).second)return fail(error,"duplicate recipe element key");std::vector<SceneTransform> places;bool geometry=r.type=="sweep"||r.type=="arc";if(geometry){if(r.frame.scale!=glm::vec3(1))return fail(error,"recipe/frame/scale: physical sweep/arc requires unit entity scale; edit profile/path/radius dimensions instead");if(!sweep(r,product.mesh,error))return false;auto proxy=r;if(r.collisionSegments)proxy.segments=r.collisionSegments;if(!sweep(proxy,product.collisionMesh,error))return false;std::vector<uint8_t> proxyBytes;if(!EncodeModelArchive(product.collisionMesh,proxyBytes,error))return false;std::vector<uint8_t> bytes;if(!EncodeModelArchive(product.mesh,bytes,error))return false;auto digest=SceneFingerprintSha256(std::string_view(reinterpret_cast<const char*>(bytes.data()),bytes.size()));digest=SceneFingerprintSha256(digest+std::string(reinterpret_cast<const char*>(proxyBytes.data()),proxyBytes.size()));if(r.geometryRevision!=digest||r.renderAsset.empty()||r.collisionAsset.empty()||r.proxyAsset.empty()){// Immutable product identity is deterministic for the recipe and both meshes.
 auto revisionId=[&](const char* kind){return SceneFingerprintSha256(std::string("Judas recipe 1\n")+r.id+"\n"+kind+"\n"+digest).substr(0,32);};product.recipe.renderAsset=revisionId("render");product.recipe.collisionAsset=revisionId("collision");product.recipe.proxyAsset=revisionId("proxy");}product.recipe.geometryRevision=digest;places.push_back(r.frame);}else if(r.type=="linear")for(unsigned i=0;i<r.count;++i)places.push_back(placement(r,{float(i)*r.spacing,0,0},{1,0,0,0}));else if(r.type=="radial")for(unsigned i=0;i<r.count;++i){float a=glm::radians(glm::mix(r.startDegrees,r.endDegrees,float(i)/r.count));places.push_back(placement(r,{std::cos(a)*r.radius,0,std::sin(a)*r.radius},glm::angleAxis(-a,glm::vec3(0,1,0))));}else{auto fs=frames(samplePath(r),r.twistDegrees);float distance=0,next=0;for(size_t i=1;i<fs.size();++i){float length=glm::length(fs[i].p-fs[i-1].p);while(next<=distance+length&&places.size()<r.count){float t=(next-distance)/std::max(length,1e-9f);auto f=fs[i];glm::mat3 basis(f.x,f.y,-f.t);places.push_back(placement(r,glm::mix(fs[i-1].p,f.p,std::clamp(t,0.f,1.f)),glm::quat_cast(basis)));next+=r.spacing;}distance+=length;}}
Scene prefab;const SceneObject* model=source.Find(r.templateId);if(!geometry&&!r.prefabAsset.empty()){if(!assets||!LoadPrefab(*assets,r.prefabAsset,prefab,error))return false;}else if(!geometry&&!model)return fail(error,"recipe template entity is missing");for(size_t i=0;i<places.size();++i){if(cancelled())return fail(error,"cancelled recipe");std::string key=r.id+"/"+std::to_string(i);SceneObject object;if(geometry){object.name=r.id;SceneRenderComponent render;render.shape=SceneShape::Mesh;render.meshAsset=product.recipe.renderAsset;object.render=render;SceneBodyComponent body;body.shape=SceneShape::TriangleMesh;body.collisionAsset=product.recipe.collisionAsset;object.body=body;}else if(model)object=*model;object.parent=0;object.transform=places[i];auto generated=ObjectProperties(object);SceneObjectId id=0;auto found=old.find(key);if(found!=old.end()){id=found->second.object;auto* live=product.scene.Find(id);if(!live)return fail(error,"generated entity removed externally; detach or regenerate explicitly");auto actual=ObjectProperties(*live);PrefabProperties changes;for(auto& [field,value]:generated){auto prior=found->second.generated.find(field);if(prior!=found->second.generated.end()&&actual.count(field)&&actual.at(field)==prior->second)changes[field]=value;}if(!ApplyObjectProperties(*live,changes,error))return false;old.erase(found);}else if(!r.prefabAsset.empty()){if(!InstantiatePrefab(product.scene,prefab,r.prefabAsset,places[i],id,error))return false;generated=ObjectProperties(*product.scene.Find(id));}else {id=product.scene.CreateObject(object.name).id;object.id=id;std::map<SceneObjectId,SceneObjectId> remap{{r.templateId,id}};for(auto& slot:object.scripts)slot.properties=ScriptSystem::RemapPropertyEntities(slot.properties,remap);if(object.socket&&object.socket->target==r.templateId)object.socket->target=id;if(r.templateId&&object.render&&object.render->textureCamera==r.templateId)object.render->textureCamera=id;if(r.templateId&&object.liquidConnection){if(object.liquidConnection->source==r.templateId)object.liquidConnection->source=id;if(object.liquidConnection->destination==r.templateId)object.liquidConnection->destination=id;}if(r.templateId&&object.deformable)for(auto& a:object.deformable->attachments)if(a.target==r.templateId)a.target=id;if(r.templateId&&object.joint){if(object.joint->bodyA==r.templateId)object.joint->bodyA=id;if(object.joint->bodyB==r.templateId)object.joint->bodyB=id;}object.prefabAsset.clear();object.prefabRoot=object.prefabSource=0;object.prefabIds.clear();object.prefabOverrides.clear();*product.scene.Find(id)=object;}product.recipe.elements.push_back({key,id,generated});}
for(auto& [key,e]:old){product.removed.push_back(e.object);product.scene.DestroyObject(e.object);}product.scene.Settings().authoringRecipes[r.id]=SerializeWorldRecipe(product.recipe);if(!ValidateHierarchy(product.scene,error))return false;std::string legacy;SaveSceneToString(product.scene,legacy);Scene check;if(!LoadSceneFromString(legacy,check,error))return false;out=std::move(product);return true;}catch(const std::exception& e){return fail(error,e.what());}}
bool BakeRecipeGeometry(const RecipeProduct& p,const std::string& meshPath,const std::string& collisionPath,std::string& error){JUDAS_PROFILE_SCOPE("Authoring geometry cook");std::vector<uint8_t> bytes;if(p.mesh.vertices.empty())return fail(error,"recipe has no generated mesh");if(!EncodeModelArchive(p.mesh,bytes,error))return false;{std::ofstream f(meshPath,std::ios::binary);f.write(reinterpret_cast<const char*>(bytes.data()),std::streamsize(bytes.size()));if(!f)return fail(error,"cannot write generated mesh");}std::vector<uint8_t> proxy;if(!EncodeModelArchive(p.collisionMesh,proxy,error))return false;auto proxyPath=meshPath+".proxy.judasmodel";{std::ofstream f(proxyPath,std::ios::binary);f.write(reinterpret_cast<const char*>(proxy.data()),std::streamsize(proxy.size()));if(!f)return fail(error,"cannot write generated proxy");}CollisionAsset collider;CollisionCookSettings settings;settings.twoSided=!p.recipe.closed;return CookCollisionFile(proxyPath,p.recipe.proxyAsset,settings,collisionPath,collider,error);}
