#include "RecipeCLI.h"
#include "WorldBuilder.h"
#include "AuthoringDocument.h"
#include "NamedAuthoring.h"
#include "SceneSerialization.h"
#include "Project.h"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
namespace {std::string bytes(const std::string& p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot read "+p);std::ostringstream out;out<<f.rdbuf();return out.str();}AuthoringOutput output(const std::string& path,const std::string& data){bool exists=std::filesystem::exists(path);auto expected=exists?bytes(path):"";if(exists&&expected!=data)throw std::runtime_error("Generated immutable revision changed externally: "+path);return {path,data,expected,exists};}}
int RunRecipeCLI(int argc,char** argv){if(argc<2)return -1;std::string command=argv[1];if(command!="--generate")return -1;try{std::string error;
if(argc<6)throw std::runtime_error("--generate recipe.judasrecipe scene.judas project.judasproj output.judas [--overwrite] [--accept-removal] [--dry-run]");
bool overwrite=false,removal=false,dry=false;for(int i=6;i<argc;++i){overwrite|=std::string(argv[i])=="--overwrite";removal|=std::string(argv[i])=="--accept-removal";dry|=std::string(argv[i])=="--dry-run";}auto recipePath=std::string(argv[2]),scenePath=std::string(argv[3]),destination=std::string(argv[5]);auto inputRecipe=bytes(recipePath),inputScene=bytes(scenePath);bool destinationExisted=std::filesystem::exists(destination);auto expectedDestination=destinationExisted?bytes(destination):"";Project project;if(!project.Load(argv[4],error))throw std::runtime_error(error);WorldRecipe recipe;if(!ParseWorldRecipe(inputRecipe,recipe,error))throw std::runtime_error(error);Scene scene;if(!LoadSceneFromFile(scenePath,scene,error))throw std::runtime_error(error);auto owned=scene.Settings().authoringRecipes.find(recipe.id);if(owned!=scene.Settings().authoringRecipes.end()){WorldRecipe previous;if(!ParseWorldRecipe(owned->second,previous,error))throw std::runtime_error(error);recipe.elements=previous.elements;recipe.renderAsset=previous.renderAsset;recipe.collisionAsset=previous.collisionAsset;recipe.proxyAsset=previous.proxyAsset;recipe.geometryRevision=previous.geometryRevision;}AssetDatabase assets;assets.Scan(project.RootDir(),project.AssetsDir());std::map<std::string,std::string> prefabSources;if(!recipe.prefabAsset.empty())for(auto& [_,record]:assets.Records())if(record.type==AssetType::Prefab&&!record.missing){prefabSources[record.path]=bytes(record.path);if(std::filesystem::exists(record.path+".judasmeta"))prefabSources[record.path+".judasmeta"]=bytes(record.path+".judasmeta");}bool geometry=recipe.type=="arc"||recipe.type=="sweep";if(geometry){if(recipe.renderAsset.empty())recipe.renderAsset=MintAssetId();if(recipe.collisionAsset.empty())recipe.collisionAsset=MintAssetId();}RecipeProduct product;if(!EvaluateWorldRecipe(recipe,scene,&assets,product,error))throw std::runtime_error(error);if(!product.removed.empty()){std::cout<<"removed authored identities:";for(auto id:product.removed)std::cout<<' '<<id;std::cout<<'\n';if(!removal&&!dry)throw std::runtime_error("review removals and use --accept-removal");}if(dry){std::cout<<"validated preview: "<<product.recipe.elements.size()<<" recipe elements, "<<product.scene.Objects().size()<<" objects; no publication\n";return 0;}if(std::filesystem::exists(destination)&&!overwrite)throw std::runtime_error("destination exists; use --overwrite");auto stage=std::filesystem::path(project.RootDir())/".authoring-stage"/MintAssetId();std::filesystem::create_directories(stage);std::vector<AuthoringOutput> outputs;
if(geometry){auto mesh=(stage/"mesh.judasmodel").string(),collision=(stage/"mesh.judascollision").string();if(!BakeRecipeGeometry(product,mesh,collision,error))throw std::runtime_error(error);auto dir=std::filesystem::path(project.AssetsDir())/"Generated";auto meshDest=(dir/(recipe.id+"-"+product.recipe.geometryRevision.substr(0,16)+"-"+product.recipe.renderAsset.substr(0,8)+".judasmodel")).string(),collisionDest=(dir/(recipe.id+"-"+product.recipe.geometryRevision.substr(0,16)+"-"+product.recipe.renderAsset.substr(0,8)+".judascollision")).string();auto proxyDest=(dir/(recipe.id+"-"+product.recipe.geometryRevision.substr(0,16)+"-"+product.recipe.renderAsset.substr(0,8)+"-proxy.judasmodel")).string();outputs.push_back(output(proxyDest,bytes(mesh+".proxy.judasmodel")));outputs.push_back(output(meshDest,bytes(mesh)));outputs.push_back(output(collisionDest,bytes(collision)));for(auto item:{std::make_tuple(meshDest,product.recipe.renderAsset,AssetType::Mesh),std::make_tuple(proxyDest,product.recipe.proxyAsset,AssetType::Mesh),std::make_tuple(collisionDest,product.recipe.collisionAsset,AssetType::Collision)}){auto meta=(stage/(std::get<1>(item)+".judasmeta")).string();if(!AssetDatabase::WriteMeta(meta,std::get<1>(item),std::get<2>(item),"",error))throw std::runtime_error(error);outputs.push_back(output(std::get<0>(item)+".judasmeta",bytes(meta)));}}
std::string legacy,named;SaveSceneToString(product.scene,legacy);if(!LegacyToNamed(legacy,"scene",named,error))throw std::runtime_error(error);if(bytes(recipePath)!=inputRecipe||bytes(scenePath)!=inputScene)throw std::runtime_error("recipe or scene changed externally during evaluation");for(auto& [path,expected]:prefabSources)if(bytes(path)!=expected)throw std::runtime_error("prefab changed externally during generation: "+path);outputs.push_back({destination,named,expectedDestination,destinationExisted});if(!PublishAuthoringOutputs((std::filesystem::path(project.RootDir())/"Authoring/recovery").string(),outputs,error))throw std::runtime_error(error);std::filesystem::remove_all(stage);std::cout<<"published "<<product.recipe.elements.size()<<" elements / "<<product.scene.Objects().size()<<" objects\n";return 0;
}catch(const std::exception& e){std::cerr<<"recipe authoring: "<<e.what()<<'\n';return 1;}}
