#include "TerrainAuthoring.h"
#include "Project.h"
#include <iostream>
#include <filesystem>
namespace {unsigned Count(const char* value){std::string text=value;size_t consumed=0;auto count=std::stoull(text,&consumed);if(consumed!=text.size()||count<2||count>257)throw std::runtime_error("terrain sample count must be an integer in 2..257");return unsigned(count);}}
int main(int argc,char** argv){try{std::string error;if(argc<3)throw std::runtime_error("usage: judas_terrain_author create SOURCE [nx nz width depth [product-directory]] | validate SOURCE | brush SOURCE raise/lower/flatten/smooth/paint x y z radius strength [layer] | fork SOURCE DEST | cook PROJECT SOURCE");std::string command=argv[1];TerrainDraft draft;
 if(command=="create"){draft.source=CreateTerrain(argc>3?Count(argv[3]):65,argc>4?Count(argv[4]):65,argc>5?std::stof(argv[5]):64,argc>6?std::stof(argv[6]):64);if(argc>7)draft.source.productDirectory=argv[7];draft.SetPath(argv[2]);if(std::filesystem::exists(argv[2]))throw std::runtime_error("create will not overwrite a source");if(!draft.Save(error))throw std::runtime_error(error);}
 else if(command=="cook"){if(argc!=4)throw std::runtime_error("cook PROJECT SOURCE");Project project;if(!project.Load(argv[2],error))throw std::runtime_error(error);AssetDatabase assets;assets.Scan(project.RootDir(),project.Resolve(project.Settings().assetsDir));auto source=project.Resolve(argv[3]);TerrainSource t;if(!LoadTerrain(source,t,error))throw std::runtime_error(error);TerrainCookResult r;if(!CookTerrain(t,source,project.RootDir(),assets,r,error))throw std::runtime_error(error);std::cout<<"cook "<<r.milliseconds<<" ms, "<<r.bytes<<" bytes; geometry "<<r.geometryChanged<<", appearance "<<r.appearanceChanged<<"\n";}
 else {if(!draft.Open(argv[2],error))throw std::runtime_error(error);if(command=="validate")std::cout<<"valid terrain "<<draft.source.nx<<" x "<<draft.source.nz<<"\n";
 else if(command=="fork"){if(argc!=4||std::filesystem::exists(argv[3]))throw std::runtime_error("fork requires a new destination");TerrainDraft independent;independent.source=ForkTerrain(draft.source);independent.SetPath(argv[3]);if(!independent.Save(error))throw std::runtime_error(error);}
 else if(command=="brush"){if(argc<9)throw std::runtime_error("brush arguments");std::string kind=argv[3];TerrainBrush brush;if(kind=="raise")brush.kind=TerrainBrushKind::Raise;else if(kind=="lower")brush.kind=TerrainBrushKind::Lower;else if(kind=="flatten")brush.kind=TerrainBrushKind::Flatten;else if(kind=="smooth")brush.kind=TerrainBrushKind::Smooth;else if(kind=="paint")brush.kind=TerrainBrushKind::Paint;else throw std::runtime_error("unknown brush");brush.radius=std::stof(argv[7]);brush.strength=std::stof(argv[8]);brush.layer=argc>9?unsigned(std::stoul(argv[9])):0;if(!draft.Begin({std::stof(argv[4]),std::stof(argv[5]),std::stof(argv[6])},brush,error))throw std::runtime_error(error);draft.End();if(!draft.Save(error))throw std::runtime_error(error);}
 else throw std::runtime_error("unknown terrain command");}return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
