#include "Material.h"
#include "AssetDatabase.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <cmath>
namespace {template<class T>bool Range(T x,T a,T b){return std::isfinite(x)&&x>=a&&x<=b;}
void Vec(std::ostream& s,glm::vec4 v){s<<v.x<<' '<<v.y<<' '<<v.z<<' '<<v.w;}
void Vec(std::ostream& s,glm::vec3 v){s<<v.x<<' '<<v.y<<' '<<v.z;}}
bool ValidateMaterial(const MaterialDefinition& m,std::string& e){
 bool ok=int(m.model)>=0&&int(m.model)<=2&&int(m.alpha)>=0&&int(m.alpha)<=2&&Range(m.metallic,0.f,1.f)&&Range(m.roughness,0.f,1.f)&&Range(m.normalStrength,0.f,8.f)&&Range(m.occlusionStrength,0.f,1.f)&&Range(m.emissiveIntensity,0.f,100000.f)&&Range(m.alphaCutoff,0.f,1.f);
 for(int i=0;i<4;++i)ok&=Range(m.baseColor[i],0.f,1.f);
 for(int i=0;i<3;++i)ok&=Range(m.emissive[i],0.f,100000.f);
 for(int i=0;i<2;++i)ok&=std::isfinite(m.uvScale[i])&&std::isfinite(m.uvOffset[i]);
 for(const auto& map:m.maps){ok&=map.asset.empty()||IsValidAssetId(map.asset);ok&=map.uvSet>=0&&map.uvSet<=1&&std::isfinite(map.rotation);for(int i=0;i<2;++i)ok&=std::isfinite(map.scale[i])&&std::isfinite(map.offset[i]);auto& s=map.sampler;ok&=(s.wrapS==10497||s.wrapS==33071||s.wrapS==33648)&&(s.wrapT==10497||s.wrapT==33071||s.wrapT==33648)&&(s.magFilter==9728||s.magFilter==9729)&&(s.minFilter==9728||s.minFilter==9729||(s.minFilter>=9984&&s.minFilter<=9987));}
 if(!ok)e="invalid material factors, texture identity or sampler";else e.clear();return ok;
}
std::string SerializeMaterial(const MaterialDefinition& m){std::ostringstream s;s<<std::setprecision(9)<<"JudasMaterial 1\nmodel "<<int(m.model)<<"\nalpha "<<int(m.alpha)<<"\nbase ";Vec(s,m.baseColor);s<<"\nmetallic "<<m.metallic<<"\nroughness "<<m.roughness<<"\nemissive ";Vec(s,m.emissive);s<<"\nemission "<<m.emissiveIntensity<<"\nnormal "<<m.normalStrength<<"\nocclusion "<<m.occlusionStrength<<"\ncutoff "<<m.alphaCutoff<<"\ndoubleSided "<<m.doubleSided<<"\nflipV "<<m.flipV<<"\nuv "<<m.uvScale.x<<' '<<m.uvScale.y<<' '<<m.uvOffset.x<<' '<<m.uvOffset.y<<'\n';for(size_t i=0;i<m.maps.size();++i){auto& map=m.maps[i];s<<"map "<<i<<' '<<std::quoted(map.asset)<<' '<<map.sampler.wrapS<<' '<<map.sampler.wrapT<<' '<<map.sampler.minFilter<<' '<<map.sampler.magFilter<<'\n';if(map.uvSet||map.scale!=glm::vec2(1)||map.offset!=glm::vec2(0)||map.rotation!=0)s<<"mapUV "<<i<<' '<<map.uvSet<<' '<<map.scale.x<<' '<<map.scale.y<<' '<<map.offset.x<<' '<<map.offset.y<<' '<<map.rotation<<'\n';}return s.str();}
bool ParseMaterial(const std::string& text,MaterialDefinition& out,std::string& e){std::istringstream s(text);std::string k;int version;MaterialDefinition m;if(!(s>>k>>version)||k!="JudasMaterial"||version!=1){e="expected JudasMaterial 1";return false;}while(s>>k){if(k=="model"||k=="alpha"){int v=0;s>>v;if(k=="model")m.model=MaterialModel(v);else m.alpha=MaterialAlpha(v);}else if(k=="base")s>>m.baseColor.x>>m.baseColor.y>>m.baseColor.z>>m.baseColor.w;else if(k=="metallic")s>>m.metallic;else if(k=="roughness")s>>m.roughness;else if(k=="emissive")s>>m.emissive.x>>m.emissive.y>>m.emissive.z;else if(k=="emission")s>>m.emissiveIntensity;else if(k=="normal")s>>m.normalStrength;else if(k=="occlusion")s>>m.occlusionStrength;else if(k=="cutoff")s>>m.alphaCutoff;else if(k=="doubleSided")s>>m.doubleSided;else if(k=="flipV")s>>m.flipV;else if(k=="uv")s>>m.uvScale.x>>m.uvScale.y>>m.uvOffset.x>>m.uvOffset.y;else if(k=="mapUV"){size_t i;if(!(s>>i)||i>=5){e="invalid map UV index";return false;}auto& map=m.maps[i];s>>map.uvSet>>map.scale.x>>map.scale.y>>map.offset.x>>map.offset.y>>map.rotation;}else if(k=="map"){size_t i;if(!(s>>i)||i>=5){e="invalid material map index";return false;}auto& map=m.maps[i];s>>std::quoted(map.asset)>>map.sampler.wrapS>>map.sampler.wrapT>>map.sampler.minFilter>>map.sampler.magFilter;}else{e="unknown material property "+k;return false;}if(!s){e="malformed material property "+k;return false;}}if(!ValidateMaterial(m,e))return false;out=std::move(m);return true;}
bool LoadMaterial(const std::string& path,MaterialDefinition& m,std::string& e){std::ifstream f(path);if(!f){e="cannot read material "+path;return false;}std::ostringstream s;s<<f.rdbuf();return ParseMaterial(s.str(),m,e);}
bool SaveMaterial(const std::string& path,const MaterialDefinition& m,std::string& e){if(!ValidateMaterial(m,e))return false;std::ofstream f(path);f<<SerializeMaterial(m);if(!f){e="cannot write material "+path;return false;}return true;}
MaterialDefinition ApplyMaterialOverride(const MaterialDefinition& src,const MaterialOverride& o){auto m=src;if(o.baseColor)m.baseColor=*o.baseColor;if(o.metallic)m.metallic=*o.metallic;if(o.roughness)m.roughness=*o.roughness;if(o.emissive)m.emissive=*o.emissive;if(o.emissiveIntensity)m.emissiveIntensity=*o.emissiveIntensity;if(o.uvScale)m.uvScale=*o.uvScale;if(o.uvOffset)m.uvOffset=*o.uvOffset;return m;}
std::string EncodeMaterialSlots(const std::vector<MaterialSlot>& slots){std::ostringstream s;s<<std::setprecision(9)<<slots.size();for(auto& slot:slots){auto& o=slot.overrides;unsigned flags=(o.baseColor?1:0)|(o.metallic?2:0)|(o.roughness?4:0)|(o.emissive?8:0)|(o.emissiveIntensity?16:0)|(o.uvScale?32:0)|(o.uvOffset?64:0);s<<' '<<std::quoted(slot.asset)<<' '<<flags;if(o.baseColor){s<<' ';Vec(s,*o.baseColor);}if(o.metallic)s<<' '<<*o.metallic;if(o.roughness)s<<' '<<*o.roughness;if(o.emissive){s<<' ';Vec(s,*o.emissive);}if(o.emissiveIntensity)s<<' '<<*o.emissiveIntensity;if(o.uvScale)s<<' '<<o.uvScale->x<<' '<<o.uvScale->y;if(o.uvOffset)s<<' '<<o.uvOffset->x<<' '<<o.uvOffset->y;}return s.str();}
bool DecodeMaterialSlots(const std::string& text,std::vector<MaterialSlot>& out,std::string& e){std::istringstream s(text);size_t count;if(!(s>>count)||count>64){e="material slot limit is 64";return false;}std::vector<MaterialSlot> slots(count);for(auto& slot:slots){unsigned flags;if(!(s>>std::quoted(slot.asset)>>flags)||flags>127||(!slot.asset.empty()&&!IsValidAssetId(slot.asset))){e="invalid material slot";return false;}auto& o=slot.overrides;if(flags&1){glm::vec4 v(0);s>>v.x>>v.y>>v.z>>v.w;o.baseColor=v;}if(flags&2){float v=0;s>>v;o.metallic=v;}if(flags&4){float v=0;s>>v;o.roughness=v;}if(flags&8){glm::vec3 v(0);s>>v.x>>v.y>>v.z;o.emissive=v;}if(flags&16){float v=0;s>>v;o.emissiveIntensity=v;}if(flags&32){glm::vec2 v(0);s>>v.x>>v.y;o.uvScale=v;}if(flags&64){glm::vec2 v(0);s>>v.x>>v.y;o.uvOffset=v;}if(!s||!ValidateMaterial(ApplyMaterialOverride(MaterialDefinition{},o),e))return false;}s>>std::ws;if(!s.eof()){e="trailing material slot data";return false;}out=std::move(slots);return true;}

#include "PhysicalMaterial.h"
bool ValidPhysicalMaterial(const PhysicalMaterial& m,std::string& error){if(!std::isfinite(m.friction)||m.friction<0||!std::isfinite(m.restitution)||m.restitution<0||m.restitution>1){error="physical material requires friction >= 0 and restitution 0..1";return false;}return true;}
std::string SerializePhysicalMaterial(const PhysicalMaterial& m){std::ostringstream s;s<<std::setprecision(9)<<"JudasPhysicalMaterial 1\nfriction "<<m.friction<<"\nrestitution "<<m.restitution<<'\n';return s.str();}
bool ParsePhysicalMaterial(const std::string& text,PhysicalMaterial& out,std::string& error){std::istringstream s(text);std::string k;int v;PhysicalMaterial m;bool f=false,r=false;if(!(s>>k>>v)||k!="JudasPhysicalMaterial"||v!=1){error="expected JudasPhysicalMaterial 1";return false;}while(s>>k){if(k=="friction"&&!f){s>>m.friction;f=true;}else if(k=="restitution"&&!r){s>>m.restitution;r=true;}else{error="unknown/duplicate physical material field "+k;return false;}if(!s){error="invalid physical material "+k;return false;}}if(!f||!r){error="physical material requires friction and restitution";return false;}if(!ValidPhysicalMaterial(m,error))return false;out=m;return true;}
bool LoadPhysicalMaterial(const std::string& path,PhysicalMaterial& m,std::string& error){std::ifstream f(path);if(!f){error="cannot read physical material "+path;return false;}std::ostringstream text;text<<f.rdbuf();return ParsePhysicalMaterial(text.str(),m,error);}
