#include "SaveStorage.h"
#include "SceneFingerprint.h"
#include "ScriptSystem.h"
#include "PerformanceProfiler.h"
#include <filesystem>
#include <algorithm>
#include <atomic>
#include <cerrno>
#ifndef _WIN32
#include <fcntl.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <unistd.h>
#include <dirent.h>
#endif
#include <limits>

namespace {
#ifndef _WIN32
struct FD {int fd=-1;explicit FD(int value):fd(value){}~FD(){if(fd>=0)close(fd);}operator int()const{return fd;}};
struct Lock {FD fd;explicit Lock(int dir):fd(openat(dir,".lock",O_RDWR|O_CREAT|O_NOFOLLOW|O_CLOEXEC,0600)){struct stat st{};if(fd.fd<0||fstat(fd,&st)||!S_ISREG(st.st_mode)||flock(fd,LOCK_EX|LOCK_NB))throw std::runtime_error("save storage busy or lock unavailable");}~Lock(){if(fd.fd>=0)flock(fd,LOCK_UN);}};
std::atomic<uint64_t> nextTemporary{1};
void Error(std::string& e,const char* operation){e=std::string(operation)+": "+std::strerror(errno);}
#endif
void Validate(GameSnapshot& s){std::string error;if(s.project.empty()||s.scene.empty()||s.content.size()!=64||s.diagnosticBuild.size()>256||s.displayName.size()>1024||s.participants.size()>16||s.gameVersion==0||!ScriptSystem::ValidateJson(s.metadata,error))throw std::runtime_error("invalid save metadata: "+error);}
}
std::string EncodeGameSnapshot(const GameSnapshot& source){JUDAS_PROFILE_SCOPE("Save encode");auto s=source;Validate(s);SaveArchive payload;payload(s.participants);SaveArchive header;uint32_t version=2;std::string hash=SceneFingerprintSha256(payload.bytes);header(version,s.project,s.scene,s.content,s.displayName,s.metadata,s.timestamp,s.gameVersion,hash,s.diagnosticBuild);SaveArchive envelope;std::string magic="JudasGameSave";envelope(magic,header.bytes,payload.bytes);return envelope.bytes;}
bool DecodeGameSnapshot(const std::string& bytes,GameSnapshot& result,std::string& error,bool metadataOnly){try{JUDAS_PROFILE_SCOPE("Save decode");SaveArchive in(bytes);std::string magic,head,data;in(magic,head,data);in.Finish();if(magic!="JudasGameSave")throw std::runtime_error("invalid save signature");SaveArchive header(head);uint32_t version=0;GameSnapshot s;std::string hash;header(version,s.project,s.scene,s.content,s.displayName,s.metadata,s.timestamp,s.gameVersion,hash);if(header.position<header.bytes.size())header(s.diagnosticBuild);header.Finish();if(version!=1&&version!=2)throw std::runtime_error("unsupported newer save container version");if(version==1){if(s.timestamp>std::numeric_limits<uint64_t>::max()/1000)throw std::runtime_error("legacy timestamp overflow");s.timestamp*=1000;}if(SceneFingerprintSha256(data)!=hash)throw std::runtime_error("save checksum mismatch");if(!metadataOnly){SaveArchive payload(data);payload(s.participants);payload.Finish();}Validate(s);result=std::move(s);return true;}catch(const std::exception& e){error=e.what();return false;}}
#ifndef _WIN32
SaveStorage::SaveStorage(std::string root):m_root(std::move(root)){}
SaveStorage::~SaveStorage(){if(m_directory>=0)close(m_directory);}
bool SaveStorage::ValidSlot(const std::string& s){return !s.empty()&&s.size()<=64&&std::all_of(s.begin(),s.end(),[](char c){return (c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='_'||c=='-';});}
bool SaveStorage::Open(std::string& error){if(m_directory>=0)return true;auto path=std::filesystem::absolute(m_root).lexically_normal();int parent=open("/",O_RDONLY|O_DIRECTORY|O_CLOEXEC);if(parent<0){Error(error,"open root");return false;}for(auto& component:path.relative_path()){auto name=component.string();if(name==".."||name.empty()){close(parent);error="invalid save root";return false;}if(mkdirat(parent,name.c_str(),0700)&&errno!=EEXIST){Error(error,"create save directory");close(parent);return false;}int child=openat(parent,name.c_str(),O_RDONLY|O_DIRECTORY|O_NOFOLLOW|O_CLOEXEC);close(parent);if(child<0){Error(error,"save root contains inaccessible/symlink component");return false;}parent=child;}m_directory=parent;return true;}
bool SaveStorage::ReadFile(const std::string& file,GameSnapshot& s,std::string& error,bool metadataOnly){JUDAS_PROFILE_SCOPE("Save read");FD fd(openat(m_directory,file.c_str(),O_RDONLY|O_NOFOLLOW|O_CLOEXEC));if(fd.fd<0){Error(error,errno==ENOENT?"missing slot":"read slot");return false;}struct stat st{};if(fstat(fd,&st)){Error(error,"stat slot");return false;}if(!S_ISREG(st.st_mode)||st.st_size<0||uint64_t(st.st_size)>SaveArchive::Limit){error="invalid/oversized save file";return false;}std::string bytes(size_t(st.st_size),'\0');size_t offset=0;while(offset<bytes.size()){auto n=read(fd,bytes.data()+offset,bytes.size()-offset);if(n<0&&errno==EINTR)continue;if(n<=0){error="truncated/failed slot read";return false;}offset+=size_t(n);}return DecodeGameSnapshot(bytes,s,error,metadataOnly);}
bool SaveStorage::Publish(const std::string& file,const std::string& bytes,std::string& error){JUDAS_PROFILE_SCOPE("Save write and synchronize");std::string tmp=".tmp-"+std::to_string(getpid())+"-"+std::to_string(nextTemporary.fetch_add(1));FD fd(openat(m_directory,tmp.c_str(),O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC,0600));if(fd.fd<0){Error(error,"create temporary");return false;}bool published=false;try{if(boundary)boundary("temporary");size_t offset=0;while(offset<bytes.size()){auto n=write(fd,bytes.data()+offset,bytes.size()-offset);if(n<0&&errno==EINTR)continue;if(n<=0)throw std::runtime_error("write save: "+std::string(std::strerror(errno)));offset+=size_t(n);}if(([&]{JUDAS_PROFILE_SCOPE("Save file sync");return fsync(fd);})())throw std::runtime_error("sync save: "+std::string(std::strerror(errno)));if(boundary)boundary("file-synced");int closing=fd.fd;fd.fd=-1;if(close(closing))throw std::runtime_error("close synchronized save failed");if(renameat(m_directory,tmp.c_str(),m_directory,file.c_str()))throw std::runtime_error("publish save: "+std::string(std::strerror(errno)));published=true;if(boundary)boundary("published");if(([&]{JUDAS_PROFILE_SCOPE("Save directory sync");return fsync(m_directory);})())throw std::runtime_error("directory sync failed");if(boundary)boundary("directory-synced");return true;}catch(const std::exception& e){error=published?"published; durability uncertain: "+std::string(e.what()):e.what();if(!published)unlinkat(m_directory,tmp.c_str(),0);return false;}}
bool SaveStorage::Write(const std::string& id,const GameSnapshot& s,std::string& error){error.clear();if(!ValidSlot(id)){error="invalid slot ID";return false;}if(!Open(error))return false;try{Lock lock(m_directory);for(auto suffix:{".save",".previous"}){struct stat st{};if(fstatat(m_directory,(id+suffix).c_str(),&st,AT_SYMLINK_NOFOLLOW)==0&&!S_ISREG(st.st_mode)){error="refusing nonregular slot";return false;}}struct stat existing{};bool newSlot=fstatat(m_directory,(id+".save").c_str(),&existing,AT_SYMLINK_NOFOLLOW)!=0&&fstatat(m_directory,(id+".previous").c_str(),&existing,AT_SYMLINK_NOFOLLOW)!=0;if(newSlot){FD scan(openat(m_directory,".",O_RDONLY|O_DIRECTORY|O_CLOEXEC));DIR* dir=fdopendir(dup(scan));if(!dir)throw std::runtime_error("cannot count slots");std::set<std::string> ids;unsigned entries=0;while(auto* entry=readdir(dir)){std::string name=entry->d_name;auto dot=name.rfind('.');if(dot!=std::string::npos&&(name.substr(dot)==".save"||name.substr(dot)==".previous")&&ValidSlot(name.substr(0,dot)))ids.insert(name.substr(0,dot));if(++entries>4096||ids.size()>=128){closedir(dir);throw std::runtime_error("save slot limit (128); delete an existing slot first");}}closedir(dir);}auto bytes=EncodeGameSnapshot(s);GameSnapshot previous;std::string oldError;bool goodPrevious=ReadFile(id+".save",previous,oldError);if(!goodPrevious&&(oldError.rfind("read slot:",0)==0||oldError.rfind("stat slot:",0)==0||oldError=="truncated/failed slot read")){error=oldError;return false;}if(goodPrevious&&!Publish(id+".previous",EncodeGameSnapshot(previous),error))return false;if(boundary)boundary("previous-committed");return Publish(id+".save",bytes,error);}catch(const std::exception& e){error=e.what();return false;}}
bool SaveStorage::Read(const std::string& id,GameSnapshot& s,bool& recovered,std::string& error){error.clear();recovered=false;if(!ValidSlot(id)){error="invalid slot ID";return false;}if(!Open(error))return false;try{Lock lock(m_directory);if(ReadFile(id+".save",s,error))return true;std::string original=error;if(ReadFile(id+".previous",s,error)){recovered=true;error.clear();return true;}error=original;return false;}catch(const std::exception& e){error=e.what();return false;}}
bool SaveStorage::Delete(const std::string& id,std::string& error){error.clear();if(!ValidSlot(id)){error="invalid slot ID";return false;}if(!Open(error))return false;try{Lock lock(m_directory);for(auto suffix:{".save",".previous"}){auto file=id+suffix;struct stat st{};if(fstatat(m_directory,file.c_str(),&st,AT_SYMLINK_NOFOLLOW)==0&&!S_ISREG(st.st_mode)){error="refusing nonregular slot";return false;}}for(auto suffix:{".save",".previous"})if(unlinkat(m_directory,(id+suffix).c_str(),0)&&errno!=ENOENT){Error(error,"delete slot");return false;}if(([&]{JUDAS_PROFILE_SCOPE("Save directory sync");return fsync(m_directory);})()){Error(error,"delete published; durability uncertain");return false;}return true;}catch(const std::exception& e){error=e.what();return false;}}
std::vector<SaveSlotInfo> SaveStorage::List(const std::string& project,const std::string& content,std::string& error){error.clear();std::vector<SaveSlotInfo> result;if(!Open(error))return result;try{Lock lock(m_directory);FD scan(openat(m_directory,".",O_RDONLY|O_DIRECTORY|O_CLOEXEC));DIR* dir=fdopendir(dup(scan));if(!dir)throw std::runtime_error("cannot list slots");std::set<std::string> names;unsigned entries=0;while(auto* entry=readdir(dir)){if(++entries>4096){closedir(dir);throw std::runtime_error("save directory entry bound exceeded");}std::string name=entry->d_name;auto dot=name.rfind('.');if(dot!=std::string::npos&&(name.substr(dot)==".save"||name.substr(dot)==".previous")&&ValidSlot(name.substr(0,dot)))names.insert(name.substr(0,dot));if(names.size()>128){closedir(dir);throw std::runtime_error("slot listing exceeds 128");}}closedir(dir);for(auto& id:names){SaveSlotInfo info;info.id=id;GameSnapshot s;if(!ReadFile(id+".save",s,info.error,true)){if(ReadFile(id+".previous",s,info.error,true))info.recovered=true;else {info.status=info.error.find("unsupported")!=std::string::npos?"incompatible":"corrupt";result.push_back(info);continue;}}info.error.clear();info.name=s.displayName;info.scene=s.scene;info.metadata=s.metadata;info.timestamp=s.timestamp;info.status=s.gameVersion!=1||s.project!=project||(!content.empty()&&s.content!=content)?"incompatible":"compatible";result.push_back(info);}}catch(const std::exception& e){error=e.what();}return result;}

#endif
